### ISSUE TITLE
Nodes - Duplicate Linked operator for node trees, new operator (ALT+D and SHIFT+D)

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3285] opened 2022-10-22 22:50 UTC
![bforartists_0jIYxGt2ZZ](https://user-images.githubusercontent.com/35357409/197364955-30197772-4a9d-4fe5-927e-bc9e536ebb48.png)

New Nodes operator in all Node Editors (Shader, Geometry Nodes and Compositor) has a new operator to duplicate linked node groups. 

This also has a new hotkey `ALT+D` but I'll make a new task for this. 

**Relevant Blender Task**
https://developer.blender.org/D16210

**Comment by ReinerBforartists** [comment] 2022-11-04 18:09
Duplicate of Nodes - New Duplicate Linked operator hotkey ALT+D #3286

Makes no sense to make two separate tasks here. We can and should tackle it as one.

**Closed by ReinerBforartists** 2022-11-04 18:09 UTC
Labels: 0 - task
