### ISSUE TITLE
Dopesheet - Grease Pencil Object - Grease Pencil track theme bug

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3240] opened 2022-09-18 20:24 UTC
![image](https://user-images.githubusercontent.com/35357409/190926864-9eeefcc6-0c9d-4d97-ac09-06c17a616090.png)

The grease pencil keyframes is now in the one and the same dopesheet - which is nice. But the theme hasn't been updated there so black on dark grey is hard to read on unselected tracks.

**Comment by ReinerBforartists** [comment] 2022-09-27 08:57
Just checked, when switching to the Blender theme, then we end in the same situation. So it is a bug under the hood. Haven't found a related commit so far though.

Blender theme is another issue then. It needs an update. But i will make a task for it.

**Comment by ReinerBforartists** [comment] 2022-09-27 09:16
Related - Update Blender themes #3250

**Comment by ReinerBforartists** [comment] 2022-10-14 08:49
Still not sure if my python installation is still troubled or if we have a bigger problem here. I was under the impression that i got it fixed. Icon creation is back working. But here i get error messages. 

@iyadahmed , could you please check if creating the userdef_default_theme.c works for you? The error message points towards a problem in the code.

![prompt](https://user-images.githubusercontent.com/13919702/195804800-21b46150-a9d8-496c-a1a2-1fc1c8b99c10.jpg)

**Comment by ReinerBforartists** [comment] 2022-10-14 09:01
It's a problem in the code. I switched to an earlier build back in 2021. And here the script works fine. So it's not my Python installation. 

We haz a bug :)

And these two things can even be connected. So i leave it one task for now.

![works](https://user-images.githubusercontent.com/13919702/195807400-1b319728-20b0-4016-9ff4-9456bdce8057.jpg)

**Comment by ReinerBforartists** [comment] 2022-10-14 09:10
Hmmm, at the end i can read something about an utf8 encoding problem. Maybe we have a wrong encoded file somewhere? This would be the super worst case though. I have no idea how to check for encoding ...

**Comment by ReinerBforartists** [comment] 2022-10-14 09:15
Hmmm. Seems that massive changes slipped through. Complete files are replaced. We may need to compare the code base against Blender again. But i'll wait for the next merge here. Can be that i am simpyl one merge behind here.

![consolidate](https://user-images.githubusercontent.com/13919702/195810076-06534d3c-22a1-4fa5-8670-96f9da4056d1.jpg)

**Comment by iyadahmed** [comment] 2022-10-19 10:57
how does one exactly reproduce this bug

**Comment by ReinerBforartists** [comment] 2022-10-19 11:36
Which one? It's two :D

I just think they could be connected.

First the theme creation. Go to source\tools\utils and run the blender_theme_as_c.py

Instructions can be found in the script. Line 17 ...

**Comment by ReinerBforartists** [comment] 2022-10-19 11:37
And the other one i can't explain at the moment since i first need to recompile BFA. Already deleted for the compilation ...

**Comment by iyadahmed** [comment] 2022-10-19 12:39
Awesome them will try it

**Comment by ReinerBforartists** [comment] 2022-10-19 12:59
Good bughunting !

**Comment by iyadahmed** [comment] 2022-10-20 18:15
I have to do it indeed

**Comment by ReinerBforartists** [comment] 2022-10-21 06:43
As a note, i just realized that there are a few hours between your merge and my pull of the newest Blender code. So this could explain the new files. Just wanted to make sure to lead your eye at comparing the code base first before investigating into the actual bug. Since this could fix it already.

**Comment by iyadahmed** [comment] 2022-11-02 17:38
> Still not sure if my python installation is still troubled or if we have a bigger problem here. I was under the impression that i got it fixed. Icon creation is back working. But here i get error messages.
> 
> @iyadahmed , could you please check if creating the userdef_default_theme.c works for you? The error message points towards a problem in the code.
> 
> ![prompt](https://user-images.githubusercontent.com/13919702/195804800-21b46150-a9d8-496c-a1a2-1fc1c8b99c10.jpg)

it fails here as well

**Comment by ReinerBforartists** [comment] 2022-11-02 18:08
Go catch it tiger !

**Comment by ReinerBforartists** [comment] 2022-11-03 17:19
Code comparison did not fix this problem.

What still makes me scratch my head is the utf8 error that we get at the end of the list. How can we check for wrong encoded files?

**Comment by iyadahmed** [comment] 2022-11-03 22:52
an idea for this is to search for "ThemeUI" in both Blender and BFA source,

as for preventing the issue of "missing changes", there's an idea to maintain bfa as a diff on top of Blender, experimenting with it now, after that you need to re clone bfa from scratch or force pull

**Comment by ReinerBforartists** [comment] 2022-11-04 06:41
A diff would quickly become a maintaining nightmare imo. Wer have too many own changes. But you can of course have a look how far you can push it.

I already searched for the terms. And i did a code comparison. So any vital difference should have vanished now. I have the feeling that the problem is not in the code, but in a document formatting. I just have no idea how to find this one.

**Comment by ReinerBforartists** [comment] 2022-11-04 07:34
Hmm. Now i get the same error in Blender. Seems that it is time to call for help.

**Comment by ReinerBforartists** [comment] 2022-11-04 07:56
Asked at Blender Developers now. Fingers crossed.

**Comment by ReinerBforartists** [comment] 2022-11-04 16:56
No answer yet. May take a few days. Maybe we never get an answer ...

For the initial issue, i have used the Blender userdef_default_theme.c file to compile. And now we have our colors, with the Blender theme. The BFA theme still fails. But at least we have our cause here now. There is some vital information missing in our userdef_default_theme.c file. Which will likely fixed once we are able to use the python script again to create the default theming.

I have another idea here though. I will look into the log of the userdef_default_theme.c file, and have a look for the latest changes. Maybe we can repair our default theme this way, by applying the missing bits by hand.

**Comment by ReinerBforartists** [comment] 2022-11-05 10:45
Just tried the blender_theme_as_c.py script at Ubuntu, and it fails the same way. It is definitely a problem with the script.

**Comment by ReinerBforartists** [comment] 2022-11-05 11:30
Our latest change at userdef_default_theme.c is newer than the latest changes at this file. Means we most probably have this problem for a bit longer already.

**Comment by ReinerBforartists** [comment] 2022-11-08 08:42
I had yet another look at it, have compiled with the Blender userdef_default_theme.c again, and as a result i can now say it is definitely a bug in our code somewhere. I just have no idea where. We did already a code comparison.

But this means we need to split the two issues. The one is this missing theming bit in the UI. The other that we can't create a theme anymore since the python file fails.

**Comment by ReinerBforartists** [comment] 2022-11-08 09:58
The new stroke animation feature was introduced between version 3.2.0 and 3.2.1. And the theming did never work for us. That's 09-06-2022 to 08-07-2022

Let's have a look if we can find the commit ...

![stroke](https://user-images.githubusercontent.com/13919702/200533694-6889455b-bfb9-468e-8e9c-31a747e4f588.jpg)

**Comment by ReinerBforartists** [comment] 2022-11-08 10:30
Possible commit: 

```
SHA-1: 92d7f9ac56e0ff1e65c364487542dfb7c32a0a67

* Animation: Add GP layers in regular Dopesheet

Grease Pencil animation channels are now also shown in the Dopesheet
mode of the Dopesheet editor and in the Timeline.

Grease pencil related events are now listened not only by container
`SACTCONT_GPENCIL` (Grease Pencil Dopesheet), but also
`SACTCONT_DOPESHEET` (main Dopesheet), and `SACTCONT_TIMELINE`
(timeline).

A new Animation Filter flag was added: `ANIMFILTER_FCURVESONLY`. For now
this only filters out Grease Pencil Layer channels.

**Implemented:**

- Preview range set: now only considers selected Grease Pencil keyframes
  when `onlySel` parameter is true. Not only this allows the operator to
  work with grease pencil keyframes in main dopesheet, but it also fixes
  the operator in the Grease Pencil dopesheet.
- Translation: allocation (and freeing) of specific memory for
  translation of Grease Pencil keyframes.
- Copy/Paste: call to both Fcurve and GPencil operators, to allow for
  mixed selection. Errors are only reported when both the FCurve and
  GPencil functions fail to paste anything.
- Keyframe Type change and Insert Keyframe: removed some code here to
  unify Grease Pencil dopesheet and main dopesheet code.

- Jump, Snap, Mirror, Select all/box/lasso/circle, Select left/right,
  Clickselect: account for Grease Pencil channels within the channels
  loop, no need for `ANIMFILTER_FCURVESONLY` there.

**Not Implemented:**

- Graph-related operators. The filter `ANIMFILTER_FCURVESONLY` is
  naively added to all graph-related operators, meaning more-or-less all
  operators that used `ANIMFILTER_CURVE_VISIBLE`.
- Select linked: is for F-curves channel only
- Select more/less: not yet implemented for grease pencil layers.
- Clean Keys, Sample, Extrapolation, Interpolation, Easing, and Handle
  type change: work on Fcurve-channels only, so the
  `ANIMFILTER_FCURVESONLY` filter is activated

Graying out these operators (when no fcurve keyframe is selected) can be
done with custom poll functions BUT may affect performance. This is NOT
done in this patch.

**Dopesheet Summary Selection:**

The main summary of the dopesheet now also takes into account Grease
Pencil keyframes, using some nasty copy/pasting of code, as explained
[on devtalk](https://devtalk.blender.org/t/gpencil-layers-integration-in-main-dopesheet-selection-issue/24527).
It works, but may be improved, providing some deeper changes.

Reviewed By: mendio, pepeland, sybren

Maniphest Tasks: T97477

Differential Revision: https://developer.blender.org/D15003
```

**Comment by ReinerBforartists** [comment] 2022-11-08 17:27
This was another dead end. The files are identical, besides our modifications to the tooltips. I fear we need a super iyad here !

**Comment by iyadahmed** [comment] 2022-11-09 00:56
No worries hopefully I can solve it, I don't have the solution currently 😅

**Comment by Draise14** [comment] 2023-03-30 00:46
Postponed for 3.6.0

**Comment by Draise14** [comment] 2023-08-22 00:40
![image](https://github.com/Bforartists/Bforartists/assets/35357409/1ab80eb0-fd01-44a2-b89c-510acb2aa870)

I think this is a blender bug, and should be reported. All themes have this issue.

**Comment by ReinerBforartists** [comment] 2023-08-22 05:15
You can try to reproduce it. But Blender doesn't have this issue afaik.

**Comment by Draise14** [comment] 2023-08-22 21:01
![image](https://github.com/Bforartists/Bforartists/assets/35357409/55351703-36c8-4007-b810-3fc0916bcff5)

I have a feeling it's in this document, it's really not quite the same with Blender - and our legacy GP is still there, the old version. Might be causing the issue. 

Document **anim_channels_defines.cc**
`Grease-pencil data-block type define`

**Comment by ReinerBforartists** [comment] 2023-08-23 05:40
I don't see a BFA comment here. So why is it not the same with blender?

**Comment by Draise14** [comment] 2023-08-23 05:42
Never mind. I tried the merge - it's the new go layer groups that is a free days after merge. We have improved tooltips and icons here. But it did not fix it... 

I'm seeing a pattern that BFA needs more comments...

**Comment by ReinerBforartists** [comment] 2023-08-23 05:50
indeed, it can't be enough comments :D

**Comment by ReinerBforartists** [comment] 2024-10-18 15:59
Not longer an issue. Theming is fixed. 

![fixed](https://github.com/user-attachments/assets/609c9153-8f8a-4366-b2cf-4e4c6a0e2265)

**Closed by ReinerBforartists** 2024-10-18 15:59 UTC
Labels: 2 - bug, 5 - Postponed
