### ISSUE TITLE
FBX import problem with 3.5.1

### ISSUE THREAD

**Issue by fasteinke** [Bforartists/Bforartists#3582] opened 2023-06-10 06:19 UTC
**Describe the bug**
A clear and concise description of what the bug is, and how to reproduce it.

**Desktop (please complete the following information):**
The Operating system. Windows 7, 8, 10, Linux, Mac ? What graphics card? 

**Screenshots, Example Files**
If applicable, please add Example material. A screenshot, a blend file, Or even a short video.

**Comment by ReinerBforartists** [comment] 2023-06-10 06:20
Missing content is missing ^^

**Comment by fasteinke** [comment] 2023-06-10 06:25
Sorry 'bout that ... keyboarrd went strange on me, or something ...

Start 3.5.1, immediately try importing Habitat67SampleTutorial_0000000.fbx - this is an export from the Habitat 67 project, in the download available at the RealityCapture website ... BFA crashes.

Using current 3DF Zephyr, same file loads, and object fully displays.

**Comment by ReinerBforartists** [comment] 2023-06-10 06:28
Many thanks for the report. Mh, and if you now could provide the link to the fbx file ... :D

FBX is a difficult matter in general. Blender reverse engineers the format, and does not use the FBX SDK. And since we are always one version ahead you might have a FBX importer that does not work with the "old" FBX version that you use here.

Could you please try the developer version of Blender to recheck if the problem existst there too? It's Blender 4.0.0 Alpha at the end of the list from here: https://builder.blender.org/download/daily/

**Comment by fasteinke** [comment] 2023-06-10 06:36
Here we go ... https://www.capturingreality.com/free-datasets - it's the Habitat 67 **Sample**, not the big fella ...

Will try Blender shortly ...

**Comment by fasteinke** [comment] 2023-06-10 07:28
Right, have Blender 3.1.2.0 on my workstation, from a while back - this doesn't crash on load, but has lost colour, texture, and is missing about 90% of the mesh; chopped off at an angle.

Do you still want the 4.0.0 Alpha to have a go at it?

**Comment by fasteinke** [comment] 2023-06-10 07:30
Went ahead with 4.0.0 Alpha anyway ... close enough to exactly the same result as for 3.1.2.0, above.

**Comment by ReinerBforartists** [comment] 2023-06-10 07:42
So in Blender it works? Hmmm.

**Comment by ReinerBforartists** [comment] 2023-06-24 16:26
Sorry for the delay, finally found a few spare minutes. And it is the usual factor 100 problem. The mesh is bigger than the clipping value. Just scale it down by factor 100 after the import, and you start to see the mesh again. At least by factor 10 as i did here. 

The same happens in Blender. This means there is unfortunately nothing to do for us here. Everything works as intended. So closing the issue.

Hope this helps

![works](https://github.com/Bforartists/Bforartists/assets/13919702/8b05f914-446b-43ea-b9dd-cb964c9fa2d4)

**Closed by ReinerBforartists** 2023-06-24 16:26 UTC
Labels: 0 - task

**Comment by fasteinke** [comment] 2023-06-25 05:20
Unfortunately, not a solution. Tried scaling it, within the import box; but result is always the same. BFA crashes, every time. All other prograsms I try have no trouble opening or importing it.

Tried a downloaded .fbx from SketchFab, with twice as many points; BFA imported and displayed this one, without complaint. So, appears to be something about the combination of my machine and the specific Habitat 67 file.

Thanks for looking into it!

**Comment by ReinerBforartists** [comment] 2023-06-25 05:51
I believe you, but we cannot reproduce the problem. And we can just fix what we can reproduce. Sorry that we don't have a solution here.

**Comment by fasteinke** [comment] 2023-06-25 23:06
Thanks again ... won't get in the way of me being able to use BFA; if I really need something in a .fbx file that upsets the program, I would just use another app to extract what's needed, or convert the format - there are always workarounds!
