### ISSUE TITLE
Node Panel: Error - bforartists_UI_flags not found

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#690] opened 2019-03-13 18:46 UTC
# Issue
bforartists_UI_flags not found - meaning the Node tabs panels won't populate and I get a location error in the console. This addon was removed in task #664, but now something in the interface is looking for it. 

The nodes panel is useless now, won't populate. This is kinda important. 

**Details**
Build from yesterday (3/12/2019)

**Screenshots, Example Files**
![bforartists_2019-03-13_13-42-34](https://user-images.githubusercontent.com/35357409/54305798-043c9180-4596-11e9-9a62-9b14cfcc4dc6.png)

# Solution
Add back the addon?

**Comment by ReinerBforartists** [comment] 2019-03-13 19:01
No, the addon is obsolete, it will remain removed. And i cannot reproduce the issue here. The startup.blend from the master works just fine. Can it be that you work with an old startup. blend again?

**Comment by Draise14** [comment] 2019-03-13 19:20
Startup file and userpref has been erased to test and compiled from the latest merge today - the startup.blend is the latest of the latest. I even tried the original startup from master just to make sure, same issue. It's not the startup nor preferences. Factory reset also does the same issue. 

I "fixed" this issue by copying in the old addon and activating it - from the dev build Bforartists 2 Alpha 0.2.0. But.. without the addon there is a bug somewhere and I'm not sure why. Sure enough the addon makes the panels show up and removes the issue.

**Comment by ReinerBforartists** [comment] 2019-03-13 19:21
You have most probably a old startup.blend somewhere. Could you please remove everything in the appdata directory?

**Comment by Draise14** [comment] 2019-03-13 19:22
Removed, no fix.

**Comment by ReinerBforartists** [comment] 2019-03-13 19:24
Odd. The startup.blend in the master is clean. I have triple checked now. The addon is long removed here. I will check your branch tomorrow.

**Comment by Draise14** [comment] 2019-03-13 20:45
Did a fresh merge from master to the branch and compiled with a new clean %appdata%, and it still doesn't work.

**Comment by ReinerBforartists** [comment] 2019-03-14 07:03
Your branch compiles fine and conflict free here. And without the message. There is also no difference between master and branch at the moment. Merging was successful. And i delete the bforartists folder in the appdata directory regularly. There is none.

And this means the problem most probably resides at your pc. Your compiled result uses an old startup.blend somewhere. Question is where it hides. Appdata content is removed you said. Hmmhmm. Interesting riddle.

One last idea, delete all content from the build folder, run cmake from scratch, and create a new solution file. Maybe the cmake cache is going funky here, and still contains some old settings.

**Comment by Draise14** [comment] 2019-03-14 19:20
Righteo, good point. I'll rebuild/build from and new Cmaek and from zero.

**Comment by ReinerBforartists** [comment] 2019-03-14 19:20
Fingers crossed !!!

**Comment by Draise14** [comment] 2019-03-18 18:53
Ok, just moved the studio for one last time, now can work on this.

**Comment by Draise14** [comment] 2019-03-22 22:00
Ok.. no fix yet. 

- Deleted %Appdata% folder
- Remade barebones Cmake to a new folder
- Built off the latest merge from master with said Cmake


Same issue..... Not sure now what to do. 

Other things to try:
-Uninstall any copies of dev builds that may have registries somewhere?

**Comment by ReinerBforartists** [comment] 2019-03-23 06:27
Ahaha. Here hides the rascal. Bug confirmed! Thanks for checking this one out.

I haven't seen this error since i haven't switched to the node editors for eons. And i had my head elsewhere :)

I still want to get rid of the addon if possible. Let's see what we can do here. At least now i know what the problem is.

![uiflagsmissing](https://user-images.githubusercontent.com/13919702/54862559-0f818100-4d3d-11e9-8c61-ceccf1e74bbf.jpg)

**Comment by ReinerBforartists** [comment] 2019-03-23 06:51
Has somebody ever used the icon mode? Thinking of removing this part, and leaving just the text with icon buttons for now. Else we would really need to readd the addon.

**Comment by Draise14** [comment] 2019-03-23 07:22
Yes. I have. On heavy use. Text to learn. Icon to work. But with the new toolshelf this may be a redundant feature. Icon only buttons should maybe be exclusive in the toolshelf buttons.

**Comment by ReinerBforartists** [comment] 2019-03-23 07:33
Thanks Draise. Hmm, i think i have a solution ....

**Comment by ReinerBforartists** [comment] 2019-03-23 07:38
Fixed in master

I have placed the flag in the toolbar addon code for now. Buttons are back working. Both, text and icon buttons.

![working](https://user-images.githubusercontent.com/13919702/54863272-01d0f900-4d47-11e9-9fb4-3773956fb92d.jpg)

**Closed by ReinerBforartists** 2019-03-23 07:38 UTC
Labels: 2 - bug
