### ISSUE TITLE
User Preferences - SpaceImageEditor - issue with bpy.rna enum

### ISSUE THREAD

**Issue by Blenux** [Bforartists/Bforartists#3759] opened 2023-09-09 08:59 UTC
Notice I get this issue with using previous user preferences in current master, but when using new user preferences the error goes away, saving current preferences doesn't fix the issue.

> WARN (bpy.rna): source/blender/python/intern/bpy_rna.cc:1343 pyrna_enum_to_py: current value '3' matches no enum in 'SpaceImageEditor', '(null)', 'ui_mode'

**With Current User Preferences**

https://github.com/Bforartists/Bforartists/assets/25260650/8a3a2b2e-b5bb-4634-a29b-b00a8dd98856

**With New User Preferences**

https://github.com/Bforartists/Bforartists/assets/25260650/6d74f9ba-c3a7-4204-9777-1df73d0f5fc9

Not sure how to fix apart from using fresh preferences from scratch?

**Comment by ReinerBforartists** [comment] 2023-09-09 09:44
We have recreated the startup.blends before a few days. Most likely a problem with not longer used values. And the solution in this case is indeed to recreate your preferences. That's development, unfortunately. I know of no fix for this.

But thanks for making us aware, we need to put a note somewhere that users might need to redo the prefs when they have this problem. 

@Draise14 , an idea where this is best done?

**Comment by Draise14** [comment] 2023-09-09 12:13
Hmm... This is a workspace layout issue. Specifically with one that uses the image editor. Rebuilding the workspaces and saving in a new startup.blend file will remove this issue. I use a left handed layout so I find this issue often.

**Comment by Draise14** [comment] 2023-09-09 12:23
Ah, and if the factory has the same issue, remove the image editor and add a new one. I will try reproduce here today to see if it is baked into the startup.

**Comment by Draise14** [comment] 2023-11-16 01:19
Cannot reproduce now. Must have been fixed from a previous workspace fix maybe? 

Can you confirm?

**Comment by Draise14** [comment] 2023-11-16 01:19
Postponed for 4.1

**Comment by iyadahmed** [comment] 2024-02-06 07:57
WARN (bpy.rna): source/blender/python/intern/bpy_rna.cc:1339 pyrna_enum_to_py: current value '3' matches no enum in 'SpaceImageEditor', '(null)', 'ui_mode'
WARN (bpy.rna): source/blender/python/intern/bpy_rna.cc:1339 pyrna_enum_to_py: current value '3' matches no enum in 'SpaceImageEditor', '(null)', 'ui_mode'
WARN (bpy.rna): source/blender/python/intern/bpy_rna.cc:1339 pyrna_enum_to_py: current value '3' matches no enum in 'SpaceImageEditor', '(null)', 'ui_mode'
WARN (bpy.rna): source/blender/python/intern/bpy_rna.cc:1339 pyrna_enum_to_py: current value '3' matches no enum in 'SpaceImageEditor', '(null)', 'ui_mode'
WARN (bpy.rna): source/blender/python/intern/bpy_rna.cc:1339 pyrna_enum_to_py: current value '3' matches no enum in 'SpaceImageEditor', '(null)', 'ui_mode'
WARN (bpy.rna): source/blender/python/intern/bpy_rna.cc:1339 pyrna_enum_to_py: current value '3' matches no enum in 'SpaceImageEditor', '(null)', 'ui_mode'

**Comment by ReinerBforartists** [comment] 2024-02-06 11:28
Can you provide a way to reproduce?

**Comment by iyadahmed** [comment] 2024-02-06 18:42
> Can you provide a way to reproduce?

Yes open BFA switch to uv editor layout 😄

**Comment by ReinerBforartists** [comment] 2024-02-06 20:03
Not here, that's why i ask :)

Mh, can it be that you migrated old settings? Or that you have old settings files in the appdata directory?

![ nothere](https://github.com/Bforartists/Bforartists/assets/13919702/7b454073-538e-4171-819a-9cae0607ba87)

**Comment by iyadahmed** [comment] 2024-02-09 05:21
debug build maybe ^^"

**Comment by iyadahmed** [comment] 2024-02-09 22:25
Let's keep it because it does happen 😅 maybe only in Linux... Maybe we need to delete App data Bforartists folder to trigger it

**Comment by ReinerBforartists** [comment] 2024-02-10 06:54
Have you removed all files in the appdata directory?

**Comment by iyadahmed** [comment] 2024-02-10 07:15
Yes ^^ one moment will upload video in few minutes

**Comment by ReinerBforartists** [comment] 2024-02-10 07:39
As told, the fix is to recreate the startup.blend. Or do you think about a more drastical solution that allows us to work with older startup.blend files?

**Comment by iyadahmed** [comment] 2024-02-10 08:34
Ah no but why wasn't it done before ^^"

**Comment by ReinerBforartists** [comment] 2024-02-10 09:01
Because it is not possible ^^

**Comment by ReinerBforartists** [comment] 2024-02-10 09:10
The cause here is how the workspaces are enumerated. And this is stored in the startup.blend files. And when this enumeration changes then you need new blend files since the enumeration does not fit anymore. There is no solution to this that i know of besides to recreate the blend file.

**Comment by iyadahmed** [comment] 2024-02-20 11:58
Let's close this, I am not able to reproduce it anymore

**Closed by iyadahmed** 2024-02-20 11:58 UTC
Labels: Known Issue
