### ISSUE TITLE
The bevel segment slider in header - add tooltip hint how this slider is meant to work

### ISSUE THREAD

**Issue by jinujohnm** [Bforartists/Bforartists#2566] opened 2021-07-29 06:09 UTC
**Describe the bug**
A clear and concise description of what the bug is, and how to reproduce it.

**Desktop (please complete the following information):**
The Operating system. Windows 7, 8, 10, Linux, Mac ? What graphics card? 

**Screenshots, Example Files**
If applicable, please add Example material. A screenshot, a blend file, Or even a short video.

**Comment by ReinerBforartists** [comment] 2021-07-29 06:14
Hi jinujohnm,

Which slider do you mean?

Could you please check if it works in Blender? Chances are that the problems exists in Blender too. And then it is best reported to the Blender developers.
Kind regards
Reiner

**Comment by jinujohnm** [comment] 2021-07-29 06:31
The segment slider for bevel

**Comment by ReinerBforartists** [comment] 2021-07-29 06:37
This slider exists twice in the UI, thus my question. 

As expected, a Blender bug. The slider in the header is indeed dysfunctional.  I will make a bug report.

![blenderbug](https://user-images.githubusercontent.com/13919702/127443622-e90ebb07-bfaf-4f6f-9b27-4cf88472d8dd.jpg)

**Comment by jinujohnm** [comment] 2021-07-29 06:40
The top one seems to be not working. Thank you for checking. And the fast reply.

**Comment by ReinerBforartists** [comment] 2021-07-29 06:40
You're welcome. And thanks for the report :)

**Comment by ReinerBforartists** [comment] 2021-07-29 06:45
Bug reported https://developer.blender.org/T90287

**Comment by ReinerBforartists** [comment] 2021-07-29 15:47
Turns out this is a feature. The slider in the header defines how much segments you will have before you do the bevel operation at all.

Means there is not this much to fix for us at the slider. Everything works as intended.

Maybe we can add a hint to the tooltip how this slider is meant to work. So making it a task

**Comment by ReinerBforartists** [comment] 2021-07-30 09:54
Fixed in master

![bettertooltip](https://user-images.githubusercontent.com/13919702/127636175-289e8988-277e-4dcb-bead-d6675801cecc.jpg)

**Closed by ReinerBforartists** 2021-07-30 09:54 UTC
Labels: 0 - task, Blender Bug
