### ISSUE TITLE
Developer Documentatio - Bforartists Flatpak distrubution pipeline 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3614] opened 2023-06-28 17:09 UTC
Right now we have the option of also providing flatpak for linux, so if it's easy enough it could be automated in the devops step on my end and provided to users. 

This task is to document the steps to setup the environment to do it, and then commit the manifest for it into the repo. 

> works on any distro with flatpak (even if they don't use glibc or use an older version of glibc)

Reasons:
- Could go to the Flathub for discoverability
- Could hit yet another corner of the linux world if appimage doesn't suffice
- Could circumnavigate glibc issues

Another reason to open this, we may have additional help to maintain linux distributions making it viable to at least know how to do it. I'm also working on getting more time into the project since I've found a business model that can carry me out of freelancing soon.

**Comment by StandingPadAnimations** [comment] 2023-06-28 17:30
I've got a Bforartists flatpak working. I still need to publish on GitHub but it works (this is using the current Linux tar archive and is based off of the existing Blender flatpak):
![image-2](https://github.com/Bforartists/Bforartists/assets/75058058/6ae20af6-faaf-4fdc-b4b4-b5c575c9f611)

**Comment by StandingPadAnimations** [comment] 2023-06-28 20:31
I've uploaded the repo with some instructions: https://github.com/StandingPadAnimations/org.bforartists.Bforartists

Right now there is a slight glibc version difference between the flatpak runtime and Arch Linux (the runtime still has its own version of glibc), but this should be somewhat simple to solve

**Comment by StandingPadAnimations** [comment] 2023-06-29 19:56
Alright so for reasons related to Flathub submission, I've swapped out using a local tar archive for a URL (downloading directly from GitHub Releases). This does add overhead with regards to uploading and downloading but it allows for Flathub to be able to build it (at the end of the day Flathub needs to be able to build the Flatpak on their side as well).

Starting with the next release for Bforartists, it might be best to also use Rocky Linux for building the binaries, as that's what the Blender Foundation uses. There's also a lot more documentation on the Blender build environment for Rocky as well (https://wiki.blender.org/wiki/Building_Blender/Other/Rocky8ReleaseEnvironment).

At this point I think it's safe to say the Flatpak works. The process for making it is as follows:
1. Compile a Linux build of Bforartists and upload a tar archive on GitHub
2. Swap out the URL in the Flatpak manifest and replace the sha256 checksum with the checksum for the new release (for verification reasons)
3. Test if Flatpak builds properly and check the [Blender Flatpak repo](https://github.com/flathub/org.blender.Blender) (which is the base of the Bforartists Flatpak) and see if there are any changes
4. Update release on Flathub (once we get Bforartists submitted on Flathub)

There are some currently known issues of the Flatpak version (mostly from the Blender Flatpak), such as:
- No HIP support (Flatpak doesn't yet have a module for this)
- Some issues with Nvidia (CUDA is supported, but Nvidia is known for making their Linux side stuff a nightmare)
- Flatpak has different paths for stuff like configuration (`.var` for instance)
- Some might not like Flatpak in general (but that's where the tar archive comes in)

However here are the benefits of Flatpak:
- `glibc` agnostic (since `glibc` is included in the runtime), adding support for distros with an older `glibc` or distros that use `musl` (like Void-Musl, Alpine, etc)
- Not dependent on System-D like Snap, which allows distros that don't use System-D to run a Flatpak version of Bforartists over a Snap version (like Gentoo, Void, Artix, etc)
- Can be uploaded on the Flathub repo, making updates and discoverability easier (and anyone can have their own Flatpak repo)
- Integrates better with desktops compared to AppImage
- Doesn't require old unmaintained libraries to run (unlike AppImage)
- Builds are reproducible. The only variability is with the Bforartists binaries themselves (but that can be standardized anyway) 

Overall, the benefits outweigh the downsides in this case (not to mention that HIP isn't included in the current Bforartists build anyway), it allows more distros to use Bforartists (since it no longer discriminates by the existence/version of `glibc` and Flatpak doesn't discriminate by the init system someone chooses to have), reproducible builds let anyone build the flatpak themselves with minimal effort, and we can upload on Flathub making it easier for users to discover, install, and update (many desktop environments have GUIs for Flatpak and Flathub is enabled on practically all distros these days). For anyone wondering, even the Blender Foundation has [now considered Flatpak for Linux releases](https://projects.blender.org/blender/blender/issues/102949).

**Comment by StandingPadAnimations** [comment] 2023-06-30 00:24
I've now started the process of uploading the Bforartists Flatpak to Flathub:https://github.com/flathub/flathub/pull/4295

As such, the repo has now been updated (will be part of Flathub if accepted): https://github.com/StandingPadAnimations/flathub/tree/bforartists. The old repo will be deleted once Bforartists is accepted

**Comment by StandingPadAnimations** [comment] 2023-07-01 00:06
Success, first build that works on Flathub's infrastructure (some extra stuff has to be supplied, and I've been traveling all day)
![image](https://github.com/Bforartists/Bforartists/assets/75058058/8e68f878-05fa-4645-bda8-8c5a6d2b54d2)

It's important we get users to test this to see what works and doesn't work. The install command for the test build is:
```sh
flatpak install --user https://dl.flathub.org/build-repo/33110/de.bforartists.Bforartists.flatpakref
```

**Comment by StandingPadAnimations** [comment] 2023-07-01 02:16
New test build, link is now https://dl.flathub.org/build-repo/33114/de.bforartists.Bforartists.flatpakref

Now I'm just waiting for some more change requests from Flathub (or Flathub acceptence)

**Comment by ReinerBforartists** [comment] 2023-07-01 06:36
A few things where i am already unhappy with:

- the user needs to install flatpak, which brings a huge change with several new libs at the system as i experience at the moment.
- the user needs to work at the command line. Which is for me inacceptable.
- i already needed a youtube tutorial, but still then cannot uninstall the formerly installed Bforartists flatpak.

![nouninstall](https://github.com/Bforartists/Bforartists/assets/13919702/aaf1501c-cd04-4906-8573-30ae150a7a27)

But let's see where this all leads to.

As a note, there is a reason why flatpak is the less used solution. A appimage is one file to download, installs nothing anywhere, and requires a single action: a double click at the file. And it simply runs then.

**Comment by StandingPadAnimations** [comment] 2023-07-02 01:50
> the user needs to install flatpak, which brings a huge change with several new libs at the system as i experience at the moment.

Most distros have it preinstalled. Ubuntu doesn't because Flatpak is a competitor to Canonical's Snap, and Canonical is the company behind Ubuntu. There's a reason Ubuntu forks remove Snap and replace it with Flatpak.

> the user needs to work at the command line. Which is for me inacceptable.

KDE and GNOME have software centers to handle flatpaks from Flathub. Bforartists is currently not in Flathub, so installation requires a command. However once installed, it will appear under installed apps in GNOME Software. Once Bforartists is in Flathub, you can search for it in the software center, and install from there.
![image](https://github.com/Bforartists/Bforartists/assets/75058058/ab5a1469-84dc-4bd4-b271-fdf252312b6d)

You can also use the link to get a `flatpakref` file, which double clicking will automatically open the software center to install the flatpak using a GUI (on distros with Flatpak)

> i already needed a youtube tutorial, but still then cannot uninstall the formerly installed Bforartists flatpak.

You're trying to uninstall using the link as the name. The command is `flatpak uninstall de.bforartists.Bforartists`. This is not an issue for the vast majority of users using software centers. In addition, you can just type `flatpak uninstall ` then press Tab to autocomplete.

> As a note, there is a reason why flatpak is the less used solution. A appimage is one file to download, installs nothing anywhere, and requires a single action: a double click at the file. And it simply runs then.

As a **daily Linux user** (and as such can speak from experience), this is **an absolute lie**. I have seen far more Flatpaks then Appimages, why? Because Flatpak is preinstalled on most systems, has the advantage being independent from the system, and doesn't depend on packages that have since been removed from most distros (libfuse2 for instance). Flatpaks are also better integrated with the desktop (this isn't just me, Erin from Erindale.xyz has also expressed his frustration on Appimages being unintegrated with the desktop).

**Comment by StandingPadAnimations** [comment] 2023-07-02 02:16
> A appimage is one file to download, installs nothing anywhere, and requires a single action: a double click at the file. And it simply runs then.

Actually this is also false as reminded by another Linux user
![image](https://github.com/Bforartists/Bforartists/assets/75058058/fe06b136-8aa3-49ce-9b75-490a571770ad)
> No, a user has to go to the file's properties and enable executing as a program before you can do that. It's a security measure for all downloads, but not for installed programs

And guess how you give a program execute permission? A complex menu to properties or `chmod +x ./appimage`. Flatpak meanwhile doesn't require this. There's a reason why Flatpaks are more popular then Appimages

**Comment by ReinerBforartists** [comment] 2023-07-02 08:39
First, i would highly recommend that you think about your tone. This is not how we talk to each other here. Call me once more a liar and you are out of here. I have understanding for being passionated. But i had this kind of passionated discussions with the knife in the hand one time too often. I am not your enemie. And when i would really be against a Bforartists Flatpak, then this thread would be long closed. So stop it.

I raised some valid concerns since i have to care about Bforartists in general. It is my project, i am the boss, i have the last word here. And i will in fact veto everything away that is a problem for Bforartists. You need to convince me, not vice versa. And to make me angry is for sure the wrong strategy.

The issue is still open, since we at Bforartists are open to every idea and since every help is welcome. But we are no wishing well where you as a user put in your ideas and we fulfill it then. It is also no place for propaganda. And as told at another place already, the request must make sense. We must have the man power for it. And it must be easy for the user. Which Flatpak is not. This is the part that still worries me a bit. As told, i was even with Youtube not able to remove the flatpak. Thanks for showing me my mistake. And for that we simply need a solution. We don't have the manpower to give Flatpak support, we are not flatpak central. So this must be explained somewhere.

A solution to this problem could be to add a note to the download page with more detailed instructions of what you need to do to get Flatpak to work, including installing the flatpak files if necessary, and how to uninstall it proper. Which might even still be necessary anymore once the Bforartists flatpak is officially listed. Not every distro supports Flatpak natively.

And my second concern is, we have already a appimage solution, so the question is, shall we really invest into a flatpak solution too? Well, it is a no brainer in case the flatpak package already exists, which you make possible at the moment. But what happens when you loose interest tomorrow? You already show some signs of being highly unhappy here.

The golden rule so far was that i just accept what i can maintain by myself if necessary. Which is a question of experience. Since in the past it always became necessary at one point. I can maintain appimage, but i will in case of cases not maintain the flatpak solution too.

You see, all this must be thought well through. And is nothing personal. But something very rational.

Allow me to react your quote battle once and then never again.

> Most distros have it preinstalled. Ubuntu doesn't because Flatpak is a competitor to Canonical's Snap, and Canonical is the company behind Ubuntu.

And Redhat is the company behind Flatpak. It is imho not less proprietary than Snap. And what you overlook: the most common distros are Ubuntu based. And not all of them comes with Flatpak preinstalled. And for Appimage you don't need to have anything preinstalled at all. A appimage package brings really everything with itself.

>As a daily Linux user (and as such can speak from experience), this is an absolute lie.

Have you even tried it?

When experience is the question, my first Linux was Suse back in 1998. I just don't use Linux regularly and my knowledge is in fact rudimetary here and there. But at Ubuntu you simply double click the Appimage file, and it starts. I test the appimage at a second Ubuntu VM regularly. And i never ever needed to give any permission to start it.

> And guess how you give a program execute permission? 

Yes, when it is required, which should not be the case for an Appimage. But that's general Linux knowledge then. That the command line is required for daily work is a Linux problem that you don't have at Windows.

>There's a reason why Flatpaks are more popular than Appimages.

Please do not ignore or twist facts. I already gave you a link that tells you that Flatpak is the least popular choice, not the most popular one. And this fits with many other sources.

https://phoenixnap.com/kb/flatpak-vs-snap-vs-appimage

But we can measure by ourselves once the flatpak version is online. I am curious about the download values then. Not that it really plays a role. The important bit is to offer a solution to the users. And everything that helps to improve Bforartists is welcome.

One last fact remains: Appimage is really the single file, without the need of any external dependencies. And that's the problem with the other two solutions Snap and Flatpak, they both require external dependencies first. That's why i personally prefer Appimage over the other two solutions.

But this thread is not Appimage versus Flatpak, not you against me, and not Linux against Windows. This all does not belong here.

This thread is how to get Flatpak to work, what is required to do so, what are the caveats and solutions, and if it makes sense to offer a Flatpak version.

Faith war, propaganda, quote battles, personal attacks and strong feelings is not welcome here. And i will in the future close any issue where you try to continue in this manner. The tracker is about problems and solutions regarding Bforartists.

I hope i made my point clear now.

**Comment by barthalion** [comment] 2023-07-02 10:57
> And Redhat is the company behind Flatpak. It is imho not less proprietary than Snap.

Almost all recent work is carried by a diverse set of contributors that have nothing to do with Red Hat. And the proprietary part is about the fact you cannot host your own snap repo or store, as compared to Flatpak. While Flathub is the primary place to get packages from these days, it's also developed as an open source project and is unrelated to Flathub.

> But at Ubuntu you simply double click the Appimage file, and it starts.

For what it's worth, AppImages are the least portable solution. You need to always make sure to use the oldest supported Linux distro to build them, otherwise users of distros older than build environment will encounter problems; it also doesn't actually bundle everything needed to run the binaries. "No external dependencies" is a convenient mischaracterization often repeated by AppImage authors.

The points above aside, Flathub primarily aims to involve upstream developers in the maintenance. I'm happy to merge Bflorartists to Flathub if you are; @StandingPadAnimations's manifest re-uses your binary so the maintenance work should be generally minimal.

**Comment by ReinerBforartists** [comment] 2023-07-02 13:04
I should have known it ^^

Can we please finally stop talking which solution is the best one? This is highly subjective. And no task to solve for our tracker. Thanks.

The task here is to get a Bforartists Flathub version to work.

**Comment by StandingPadAnimations** [comment] 2023-07-02 13:43
Looks like I didn't have to respond this time 

> @StandingPadAnimations's manifest re-uses your binary so the maintenance work should be generally minimal.

That is indeed correct. The goal is to have a truely cross-distro version of Bforartists to allow more flexibility when building Linux binaries, like moving from Ubuntu to Arch or Rocky 8 (what the Blender Foundation officially uses) for building, so stuff like glibc is no longer the main concern. 

> The task here is to get a Bforartists Flathub version to work.

As it stands, it builds and works. Proper testing would be needed, but I've stated what I know for a fact works and doesn't work (based on the Blender Flatpak) in an [earlier comment](https://github.com/Bforartists/Bforartists/issues/3614#issuecomment-1613731053). 

> - No HIP support (Flatpak doesn't yet have a module for this)
> - Some issues with Nvidia (CUDA is supported, but Nvidia is known for making their Linux side stuff a nightmare)
> - Flatpak has different paths for stuff like configuration (.var for instance)
> - Some might not like Flatpak in general (but that's where the tar archive comes in)

Now I'll be working on fine tuning the permission settings cause as it stands, the Bforartists Flatpak has unrestricted access to the file system, and that's not acceptable (to me at least). I believe access to `/home/user` (or whatever `xdg-home` is) is sufficient for most people. If they need access to more directories, they can edit the permissions of the sandbox using something like Flatseal.

**Comment by StandingPadAnimations** [comment] 2023-07-02 16:38
Alright, for maximum readability and maintainability, I have swapped out the JSON manifest for a YAML manifest and added a ton of comments explaining everything (https://github.com/StandingPadAnimations/flathub/blob/bforartists/de.bforartists.Bforartists.yaml)

**Comment by StandingPadAnimations** [comment] 2023-07-02 23:41
Since the Flatpak version of Bforartists is near completion (just waiting for any more suggestions on Flathub's side), I've went ahead and filmed myself installing a Flatpak with GNOME Software and installing an AppImage with AppimageManager. Note that since Bforartists is not on Flathub yet, I've choosen a random Flatpak (which shows the discoverability aspect), but it's the same process for all flatpaks. **This is not to say one is better per say, but rather to show installation differences**.

Flatpak + GNOME Software

https://github.com/Bforartists/Bforartists/assets/75058058/fa41d2e9-7c90-447d-841d-48f58d8c284a

AppImage (not including downloading both the appimage and appimage manager which is needed for desktop integration, something many artists want)


https://github.com/Bforartists/Bforartists/assets/75058058/cf87393e-c8b9-4381-9d2a-229115d444dc

Note that for appimage, if you want to update Bforartists, you have to remove both the AppImage (in `~/Applications`) and the generated desktop file (in `~/.local/share/applications`) and repeat the installation process.

Again _**I'm not arguing that Flatpak is "better" in this case, I'm merely showing the differences in installation**_. As an artist on Linux, I believe many artists would prefer being able to search for Bforartists in their software center, click install, and hop right in). I will admit that GNOME Software does get a bit weird once a Flatpak is installed, but that's a minor inconvenience.

**Comment by ReinerBforartists** [comment] 2023-07-03 05:08
Hey standingpad,

I told you to stop any propaganda. And this includes false informations like Appimage needs a manager. I have therefore removed your comment.

**Comment by ReinerBforartists** [comment] 2023-07-03 05:09
Am i correct that Flatpak would come without HIP and Cuda?

**Comment by StandingPadAnimations** [comment] 2023-07-03 06:44
> Am i correct that Flatpak would come without HIP and Cuda?

Only HIP, CUDA is included

> I told you to stop any propaganda. And this includes false informations like Appimage needs a manager.

Propoganda? I just showed a comparison of installation steps, and I clearly stated that a manager is needed **if** one wants desktop integration (very different from saying Appimage as a whole **requires** a manager), and in that comment I said not 1, but 2 times that it was not to continue the Flatpak vs Appimage debate. How does that constitute as propoganda?

Very well then, please close this issue, I certainly don't feel welcome here. I'll just continue exercising my right under GPL to redistribute (GPL allows redistribution of binaries provided the source is given, and that's very easy for me to do). That seems to be the best and most civil solution for both of us. I apologize it had to end this way, but no harsh feelings.

**Comment by ReinerBforartists** [comment] 2023-07-03 07:08
>Only HIP, CUDA is included

Thanks. Without HIP we can live, but without Cuda it would have made no sense.

>Propoganda?

Yes, propaganda. I was very clear, twice now. And will not discuss this with you. Stick to the rules or leave. This is the Bforartists tracker. We solve issues regarding Bforartists here. We don't start a war which solution is better.

> Very well then, please close this issue, I certainly don't feel welcome here. I'll just continue exercising my right under GPL to redistribute (GPL allows redistribution of binaries provided the source is given, and that's very easy for me to do). That seems to be the best and most civil solution for both of us. I apologize it had to end this way, but no harsh feelings.

Well, i have seen this coming. See what i mean with you may quickly loose interest? Maybe now you understand why i simply have to worry. Somebody starts with something, then is loosing interest, and the rest of the team has to maintain it then.

Your work is still welcome. What is not welcome here is your attitudes. It was you who decided to make yourself not welcome by starting to attack me personally and to continue with spreading propaganda even after being told to stop it. When you want to be part of the crew then stay friendly and kind. And don't misuse the tracker for propaganda. Easy rules. And your decision.

**Comment by StandingPadAnimations** [comment] 2023-07-03 07:57
> Well, i have seen this coming. See what i mean with you may quickly loose interest?

I've it clear I'm continuing a Flatpak, but I have expressed myself not feeling welcome. I've given the benefits, but I've also given the problems that I know exist (but are outweighed by the benefits), is that propaganda? Is claiming every single case, where I've illustrated a benefit, propaganda welcoming? If so, I do not feel welcomed here, but that doesn't mean I'm stopping development the Flatpak (on the contrary, I'll be excercising my right under GPL to continue making one). 

> Maybe now you understand why i simply have to worry. Somebody starts with something, then is loosing interest, and the rest of the team has to maintain it then.

Where did I say I was leaving the Flatpak as your responsibility? On the contrary, I've said I'll continue distributing the Flatpak (although it now qualifies as unofficial), and upstream just returns to what they were doing. Like I said, best and most civil solution given the behavior shown by upstream. 

So please, as I, have requested, close this issue.

**Comment by StandingPadAnimations** [comment] 2023-07-03 20:26
I've made it clear I'm not continuing here, that's final. This will be my last comment. Any further comments you make in response I will interpret as attacking, and neither of us want that do we?

> And i repeat, your work is still welcome.

And part of my work is showing the benefits of a Flatpak Bforartists (after all, you want to be justified, don't you?), which have been interpreted as propaganda.

>  if possible. I would suggest to sleep a night over your decision, and then decide again.

Already done and I still have the same decision, so no, I'm continuing here.

> I will talk with Draise about it, and we will decide then which parts of the discussion will remain.

Since you show interest in deleting discussion comments (against the spirit of FOSS in my opinion, but you do you), I've archived this entire discussion on my personal web archive and the Wayback Machine. 

> You think too short. When we start to offer a Flatpak, and the Flatpak is not maintained anymore, then this throws a bad light at us at Bforartists. So once we start something we have to continue it.

And calling everything propaganda doesn't paint Bforartists in a bad light? I've already changed the metainfo of the Flatpak to mention it's unofficial, and will change the issues link to point to the Flatpak GitHub (which will make it clear that it's unofficial) instead of here if Flathub submission gets through. If someone thinks the Flatpak is official, that's beyond me at that point.

> This is best done under the hood of Bforartists, no matter if you personally like me or not. Since a inofficial version could conflict with an official version.

The manifest is open, anyone can see how its built. If you look in the manifest, you will see 3 things:
- Building codecs (including non-free ones)
- Building ffmpeg
- Downloading the Bforartists tar and adding it to the Flatpak

I've made it clear I do not feel welcome here. I does not matter how much you want my work, if I do not feel welcome here then that's all, nothing else. 

> And you would use our brand without our permission. The product name is not part of GPL.

GPL v3 (the license Bforartists uses) only allows restricting a product name and logo if it's trademarked or the program has been modified. To quote [GPL v3](https://www.gnu.org/licenses/gpl-3.0.en.html):
> Notwithstanding any other provision of this License, for material you add to a covered work, you may (if authorized by the copyright holders of that material) supplement the terms of this License with terms:
> ...
> c) Prohibiting misrepresentation of the origin of that material, or requiring that modified versions of such material be marked in reasonable ways as different from the original version;
> ...
> e) Declining to grant rights under trademark law for use of some trade names, trademarks, or service marks;

No where is it mentioned the name "Bforartists" is trademarked (although "Blender" is trademarked and the Blender Foundation still lets redistributing under their brand), nor am I modifying any aspect of Bforartists, I'm just providing it as a Flatpak (and frankly this isn't the first time someone tried to package Bforartists as a Flatpak, I was made aware of [a previous attempt](https://github.com/flathub/flathub/pull/3357) when I first submitted the Flatpak on Flathub). I am also not misrepresenting the origin of the material (after all, the binaries are from here). The logo can be put under a separate license, but I have not found any license for the logo, so as it stands it can still be redistributed  (and frankly if it gets to that point, I can change the logo in the Flatpak during the build stage anyway, I got an alternative logo prepared just in case). In addition, GPL forbids any additional restrictions:
> All other non-permissive additional terms are considered “further restrictions” within the meaning of section 10. If the Program as you received it, or any part of it, contains a notice stating that it is governed by this License along with a term that is a further restriction, you may remove that term. If a license document contains a further restriction but permits relicensing or conveying under this License, you may add to a covered work material governed by the terms of that license document, provided that the further restriction does not survive such relicensing or conveying.

And Section 10 states:
> You may not impose any further restrictions on the exercise of the rights granted or affirmed under this License. For example, you may not impose a license fee, royalty, or other charge for exercise of rights granted under this License, and you may not initiate litigation (including a cross-claim or counterclaim in a lawsuit) alleging that any patent claim is infringed by making, using, selling, offering for sale, or importing the Program or any portion of it.

Based on all of this, I am fully allowed by GPL to distribute Bforartists as a Flatpak in its original name and logo, as I do not modify the binaries, I do not lie about the origins of those binaries, and I am merely repackaging Bforartists (while making it clear it's now unofficial), all under the spirit of GPL.

**Comment by ReinerBforartists** [comment] 2023-07-04 05:53
Okay, this is it, i showed enough patience now. I will not tolerate any further escalation from your side. This is the Bforartists tracker, not your personal war zone.

You will now be banned from the Bforartists tracker, which will most probably then remove the rest of the discussion. And i will also take care that you are removed from the Discord. When you don't want to listen, then live with the consequences.

People like you are not welcome at Bforartists.

**Closed by ReinerBforartists** 2023-07-04 05:53 UTC
Labels: 0 - task, Documentation, Experimental
