### ISSUE TITLE
Extensions - Refresh Local hits an error and can't find user_default

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4431] opened 2024-07-03 01:11 UTC
![image](https://github.com/Bforartists/Bforartists/assets/35357409/24c0bc42-493c-407c-bae8-fc818f2db91f)

![bforartists_LKOENuUXa5](https://github.com/Bforartists/Bforartists/assets/35357409/cb2b5be9-706e-46ed-9214-8fe268def4a5)

Right now when you refresh local, it hits an error. This doesn't happen with Blender. For some reason a folder is not being created in the USER folder (`USER/extensions/user_default`), or something is off. 

I am not sure if our default addons addon should make this folder to circumnavigate this... or if this a core issue we have with the extensions and the Bforaritsts USER paths of a sort. 

Something is weird, though document apparently shows they are squeaky clean on comparison... 

This is missing. Worth comparing what's up in the `preferences.cc` file
![image](https://github.com/Bforartists/Bforartists/assets/35357409/db5f2428-4626-4fb8-a182-f47a7310d551)

**Comment by Blenux** [comment] 2024-07-15 07:43
This issue seems to be fixed with recent merges.

**Comment by Draise14** [comment] 2024-07-16 02:44
Will verify and close.

**Comment by Draise14** [comment] 2024-07-17 00:05
Happens on Windows still.

**Comment by Blenux** [comment] 2024-07-30 06:59
Yes just notice this still happens on Linux and Blender also.

**Comment by ReinerBforartists** [comment] 2024-09-03 07:05
Just curious, did you report it? Then we could link the issue here and label it as Blender issue.

**Comment by ReinerBforartists** [comment] 2024-09-03 07:07
Can by the way confirm that the problem still exists in Blender

**Comment by ReinerBforartists** [comment] 2024-11-18 10:03
Mh, it is no bug, but a warning. And warnings exists by design. So nothing to fix here really. Not at our end anyways. So i vote to close this issue.

**Closed** 2024-11-18 13:08 UTC
Labels: 6 - wontfix, Blender Bug / Issue
