### ISSUE TITLE
Help Needed - install to Debian

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2205] opened 2021-01-27 19:13 UTC
# Issue
From a user on Discord:
> 
> I'm interested in trying bfartists out, but I can't install it. I used the .deb installation (I'm using Linux) and I keep getting  this error message: Error while installing package: cannot copy extracted data for './opt/bforartists/bforartists' to '/opt/bforartists/bforartists.dpkg-new'.
> 
> I tried using the tar.xz file to install it with the terminal, but it says missing destination file operand after 'Bforartists-270-Linux.tar.xz'
> I'm not sure of what to do or how

# Task
Got some ideas?

It looks like there is an issue extracting the installation.

**Comment by ReinerBforartists** [comment] 2021-01-27 20:07
Hm. The tar.xz is just an archive. No installer. Simply unpack it into the desired directory :)

I will have a look at the deb tomorrow. Maybe i have put the paths wrong.

**Comment by iyadahmed** [comment] 2021-01-28 05:49
It might not be an issue with the deb, the user is new to linux and installing the deb on a chromebook, but let's see

**Comment by ReinerBforartists** [comment] 2021-01-28 06:47
I will create a tar.gz too. It can be that some linux distributions are in trouble with tar.xz. xz compresses much smaller than gz. But is not so common.

**Comment by naetherm** [comment] 2021-01-28 06:52
Or maybe the downloaded *.deb file is broken.
Can the related person verify that the md5 checksum of the deb file is: f690a8db74b78f1457ef42a0ffe645df
If not: Download again and retry, otherwise apt --fix-broken install

**Comment by ReinerBforartists** [comment] 2021-01-28 07:13
I think i know what the problem is. I have build at Ubuntu 20.10. And as usual this means that you need Ubuntu 20.10 now to run it. BFA does not start at my Ubuntu 20.04 here. In Ubuntu 20.10 it works just fine.

I really hate Ubuntu. It's the very worst linux ever. This should not happen with a simple point upgrade.

**Comment by naetherm** [comment] 2021-01-28 07:27
No, that's not the problem here as it has an error during the installation process of the *.deb file.
Problem related to the Ubuntu version are more likely to happen during execution/runtime when specific versions of libraries do not match or there is a GLIB version problem.

**Comment by ReinerBforartists** [comment] 2021-01-28 07:30
Yes, that's what i have here between ubuntu 20.10 and 20.04 :)

x@ubuntu:~/Bforartists-270-Linux$ ./bforartists
./bforartists: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./bforartists)

**Comment by naetherm** [comment] 2021-01-28 07:31
That during runtime, the user tries to install BFA.

**Comment by ReinerBforartists** [comment] 2021-01-28 07:34
Yes. Very nasty. How can we prevent this from happen?

**Comment by ReinerBforartists** [comment] 2021-01-28 07:38
>  (I'm using Linux) 

Before we go on with ranting into the blue, what Linux? There are over 1400 distributions. And every distribution has so and so much versions ...

**Comment by iyadahmed** [comment] 2021-01-28 09:40
He said he is trying to install the deb on a chromebook (probably Chrome OS) as he said 
![image](https://user-images.githubusercontent.com/25552173/106119189-92f03280-615d-11eb-9e6d-83158e67d4ec.jpeg)

**Comment by ReinerBforartists** [comment] 2021-01-28 09:58
Ouch. That's nothing trivial i was told XD

**Comment by iyadahmed** [comment] 2021-01-28 11:10
> Ouch. That's nothing trivial i was told XD

Indeed I just googled it Chrome OS can't unpack tar by default, and it says newer versions doesn't work well with debs

**Comment by ReinerBforartists** [comment] 2021-01-28 11:22
You can't always win. I guess that's one of those cases.

**Comment by iyadahmed** [comment] 2021-01-28 11:37
> You can't always win. I guess that's one of those cases.
> 
> 
> 
> EDIT, maybe he can unpack the archive across the google drive zip extractor. https://zipextractor.app/

Great idea, will tell him that

**Comment by ReinerBforartists** [comment] 2021-01-28 11:53
Let me know how it turns out :)

**Comment by iyadahmed** [comment] 2021-01-28 13:09
> Let me know how it turns out :)

Sure he is offline now apparently

**Comment by ReinerBforartists** [comment] 2021-02-05 20:05
I guess this one is already solved in the one or another way. Can we close it? :)

**Comment by iyadahmed** [comment] 2021-02-05 20:43
The user didn't reply since then
Should we close it? @Draise14

**Comment by iyadahmed** [comment] 2021-02-05 22:32
He replied now, her converted the tar into zip file, now trying to run it

**Comment by iyadahmed** [comment] 2021-02-06 03:42
No success, the weird thing is he got blender working

**Comment by ReinerBforartists** [comment] 2021-02-06 07:05
I have unfortunately no idea what the problem could be :(

We have no chance to reproduce the trouble. I don't have a chromebook. So as sorry as i am, we need to close this issue unfixed.

**Closed by ReinerBforartists** 2021-02-06 07:05 UTC
Labels: help wanted

**Comment by iyadahmed** [comment] 2021-02-06 18:24
I think I now know the problem, it is indeed Debian, that's what chrome os virtualize to run linux apps

the problem is related to outdated libc6

but the weird thing that he got Blender running

**Comment by ReinerBforartists** [comment] 2021-02-06 18:43
Yes this worries me too. We have the same kind of problem with Ubuntu 20.04 versus 20.10. I just have no idea what we could do here.

**Comment by iyadahmed** [comment] 2021-02-06 19:24
I looked it up, it says we could compile with a lower libc6 version

**Comment by iyadahmed** [comment] 2021-02-06 19:24
should we reopen this then?

**Comment by ReinerBforartists** [comment] 2021-02-06 20:03
Hm. Difficult. I use the libs that Blender uses. I worry about the possible trouble when we use a lib that is not the Blender default lib.

I would say leave it alone.

**Comment by ReinerBforartists** [comment] 2021-02-06 20:05
Is this even one of the Blender libs? I can't find libc in the lib folder here.

**Comment by iyadahmed** [comment] 2021-02-06 20:39
Ah ok, I'm not sure too :D 
agree
