### ISSUE TITLE
Outliner - Default to Scene View

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#946] opened 2019-06-07 15:24 UTC
## Issue
Right now the default of BFA and Blender is to start in the collections view. This includes bins for visual settings - acting like layers and instance management. 
This is good because it has element filters, and is built for and around rendering, visibility and scene layout management. 

But this is NOT good for modeling, layout, rigging, and asset creation - and even for quick visibility toggles in a "layer" system. 

![bforartists_2019-06-06_12-19-35](https://user-images.githubusercontent.com/35357409/59111117-0482c980-8906-11e9-8ea1-5c8ceea04ebe.png)

- Right now we have no true scene hierarchy, only ghosting and instanced hierarchies which is not a simple system. 
- With two or more collections, and none-selected, new objects get placed in a "scene collection" without a layer, meaning the use and need for collections is not immediate in early development. 
- If a collection is selected, new objects get placed in it, and if the collection is hidden, the new object would be lost when created. This feel unpredictable and broken. 
- If you create hierarchies and parent/child relationships, and these objects are in different or multiple collections, you'd get a ghosting and multi-instance system that quickly clutters what should be a simple hierarchy overview of a direct child/parent relationship. 
- The collections bin used for visibility control are now cluttered and over-whelmed by their contents UNLESS you collapse them all (making hierarchy selection and scene management nearly useless). 
- instances in multiple collections of the same object show the original everywhere, regardless of hierarchy or where the original instance is located in the scene hierarchy. 
- There is no fusion of scene hierarchy (unless you hide collections all together via filter) and collection visibility overhead control (unless you hide/collapse all collection contents)

All in all, collections proves to be useful for render and lookdev scene setup and management, which is a late process in the 3D authoring pipeline, meaning.. it is deficient for early and general use when you open the software and get your assets modeled, rigged, animated and ready for the latter process. 

![bforartists_2019-06-06_12-14-35](https://user-images.githubusercontent.com/35357409/59111100-faf96180-8905-11e9-9983-107e109e8291.png)

## Solution
**Solution 1**
I'd like to propose the default outliners to be specific to a workspace. 
Eg. If the workspace is more about rigging/modeling/UV/general = Scene Outliner
Eg. If the workspace is about rendering/compositing/shading = Collections Outliner

**Solution 2**
I'd also like to propose that we default all outliners to the Scene Outliner.

Reason: the scene outliner has both collection view toggles and controls AND a true scene hierarchy overview. It is deficient in filters, but it shows everything you have in a scene and how it's setup in a technical and functional way (object and armature relationships within the 3D Space). This also is less of a shock to users coming in from BFA 1 or Blender 2.79 and other software that has traditional hierarchy scene based outliners. 

**Solution 3:**
Do one of the above AND improve the scene view functionality in the Outliner  to have more collection controls for consistency, filter controls for visbility, collection indicators, etc.
Issue: This requires probably heavy C coding and it might be too hard to do. 

## The reason for the Scene View

**Pros**
- The scene view has both true scene hierarchy and a minimized collection management system. 
- It also adds the ability to have a one click scene management for power-users and complex animations. 
- Collections now are organized neatly without distracting contents for easy visibility control. 
- Objects can be assigned to collections through right click or dragging, no problem 
- Hierarchy for rigging, layout and modeling is now clear and uniform and not hidden away with confusing ghosts or multi-collection instances of the same object. 
- It's similar to BFA 1 outliner WITH collection/layer management, so easier on traditional users or users coming from Blender 2.79 or other software

It's simpler, more useful, and the only issue is, unlike the collection outliner, that there are no item filters or indicators where the object resides in the collection. 

![bforartists_2019-06-06_12-21-54](https://user-images.githubusercontent.com/35357409/59115357-baeaac80-890e-11e9-88d2-68df7ab9daaa.png)

**Cons**
- There are not object filters like in the View outliner (yet?)
- There is no indicator which collection an object is located in (yet?)

To justify: for modeling, rigging, sculpting, UV, animation and layout, you don't need to really work with many complex and nested visual layers until you work with complex scene layout and rendering setups.  

## Alternatives
**Solution 4:** 
Default the Collections outliner to filter out collection bins to show only object hierarchies - now we we have a filter system for scene hierarchies in the outliner sacrificing layer/collection management and multi scene management for early modeling/rigging/layout with true simple hierarchy - leaving the user to later toggle this. Thus have the Scene view turned off by default.

**Solution 5:** 
Do what was suggested in Solution 4 only in modeling/rigging/animation layout and others that are about the lookdev and rendering have the filter turned off by default. Thus we can have the scene view turned off and the collections activated where relevant. 

## Addition Notes
I know the scene view is not as functional and customizable as the Collection view, but it is usable and simpler. 
Additional tasks could be created to expose some functionality to the Scene view
eg. create add collections button in header, add object location in a collection indicators, add item filters, etc.

**Comment by ReinerBforartists** [comment] 2019-06-07 15:55
Hm. My current thoughts at it: Rewriting the outliner to do what you want is behind our scopes. To make it workspace dependant is possible but looks super confusing to me. And most probably also to everybody else.

The current entry level makes most sense, it works at scene level. And i don't want to have another default here. You can always switch one hierarchy higher in the dropdown menu in the header. It's one click.

**Comment by Draise14** [comment] 2019-06-07 16:48
> The current entry level makes imho most sense, it works at scene level. And i don't want to have another default here really. You can always switch one hierarchy higher in the dropdown menu in the header. It's one click.

What do you mean? Keeping it as it is in Collections view and collapsing hierarchy for all layers views of the scene? 
Or like.. keeping it all in Scene view to then toggle to collections later for all as a default proposed? 

Collapsing the hierarchy to use collections view is a 3 step process (click, open menu, select collapse, the control the collection views - loose access to scene management/selections) meanwhile in Scene mode you just move the mouse up and click once to hide a collection (without needing to collapse any hierarchy at all)

Hiding collections to get to a true scene hierarchy is also a multi step process (click, open menu, move to filters, hide collections to get scene overview of hierarchy, loose collection visibility control = broken) 

Switch to the scene mode also is not just one click. You click on the dropdown, you select the entry, then it changes. It's not a simple mouseover click. 

There is no scene level in the collections view. New objects don't get created on a scene level (but on selected collection). Hierarchy is not shown in a scene level. All objects are instances in a bin with no regard for hierarchy unless in the same collection bin = complicated. 

With one or more collections you have no scene view, the scene collection is emptied once you move something to another collection. 

> Hm. My current thoughts at it: Rewriting the outliner to do what you want is behind our scopes. To make it workspace dependant is possible but looks super confusing to me. And most probably also to everybody else.

Solution 1 you mean? 

Right now nothing needs to be re-written. The Scene view is **already** functional, it's just changing the startup.blend file to do this, the default of BFA could start with all in Scene view for simplicity and usability sake early use (Solution 2) - with the easy toggle to collections mode for later use (I would argue the collections view is not adequate nor recognizable to everyone first glance -right now for the reasons listed above). 

Re-writing outliner functionality are for additional tasks and not necessarily part of this. 

# Solution 6:
Maybe a button to quick toggle to Scene mode and vice versa in the header would make sense?

**Comment by ReinerBforartists** [comment] 2019-06-07 16:49
I mean that i am not investigating into this issue right now. But my belly tells me that you want to fix something here that aint broken ;)

**Comment by Draise14** [comment] 2019-06-07 16:50
Yes, it's just changing a default of BFA to make more sense, usable.

**Comment by ReinerBforartists** [comment] 2019-06-07 16:57
That's the part that i am not convinced of at the moment, sorry ^^

**Comment by Draise14** [comment] 2019-06-07 17:09
Maybe I'll record the pitfalls and do another project but first in scene view to verify if it's any better. I've used the collection view in 3 projects already, and indeed I have found all the arguments I've listed to why it's not a good default.. but oh well.... You're the boss here.

**Comment by ReinerBforartists** [comment] 2019-06-07 17:17
It's not about a boss attitude. The issue is still open. It's about changing defaults without a deeper check where the pitfalls are. I am currently at icons. And you should know me. I am always just in one issue at a time.

Either way, i will decide about it when i come to this issue. Not while standing in the door and being busy with something else. This kind of issues are too dangerous for a quickshot.

My current observations while standing in the door are: 

I see changes at the defaults that doesn't even make sense to me,  including the danger to confuse newbies even more with having the same thing completely different in different workspaces. And this makes me super careful.

**Comment by ReinerBforartists** [comment] 2019-06-08 06:50
There is currently somebody working at outliner improvements in the Blender crew. It's GSOC, and so chances are big that these changes will never make it into Blender. But it is imho nevertheless worth to wait the two months, and have a look how outliner evolves before we decide this issue here.

**Comment by ReinerBforartists** [comment] 2019-06-28 05:56
The initial issue, to default to scene view, is not gonna happen. 

The rest is a dozen issues at once. And unsolveable in the current way. As told, let's wait what the Blender devs will do here. Then come back to the outliner, and tackle the here named issues at a one by one base when there is still a need for.

Closing this one.

**Closed by ReinerBforartists** 2019-06-28 05:56 UTC
Labels: 5 - Postponed, Feature request
