### ISSUE TITLE
Toolbar - Unify Toggle Menu's into one

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1632] opened 2020-06-19 13:58 UTC
# Issue
![image](https://user-images.githubusercontent.com/35357409/85140171-817b9b00-b20a-11ea-8555-a407d192f10d.png)

> It would be nice, if the individual toolbar menu buttons, could all be combined into the one, 'Type', menu button. In my example, it would eliminate, IMHO, 4 unecessary buttons, and make room for adding 4 other, more useful (to me) icons... vOv

This is a feature request from the discord server. He makes a point, each group could just be a small visual saperator, and to configure each toolbar could be done from the type menu then submenus. 

> Instead of the dropdown displaying just 'Type' when you hover-over, then when you click 'Type', then it shows the list of toolbar catagories... maybe skip that step, and have it just immediately display the list of toolbars, on hover-over?

### Reasons
Well, it would make the toolbar configuring hierarchy exist in one place, and logically be presented by the whole submenu concept. 

# Task
- Investigate if this is a feasible and doable UI
- Then possibly implement.

**Comment by ReinerBforartists** [comment] 2020-06-19 15:43
Hm. This is by design. The menu button acts as a separator. That way you can say what toolbar ends and what toolbar starts.

**Comment by Draise14** [comment] 2020-06-19 16:13
Yeah, I do think a visual separator would be nice between bars, like a line or space. I do have to agree though, having the toggle UX closer and in the same menu does feel like it would be smoother and logical concerning toggle hierarchy.

**Comment by ReinerBforartists** [comment] 2020-06-20 08:05
This would occupy the same space :)

**Comment by Draise14** [comment] 2020-06-20 18:27
Yeah, it would be the same... but the UX to configure the toolbar would be less mouse gymnastics to configure your toolbar to how you want it, less clicks, less movements. I agree a visual separator would be necessary, but the idea of configuring all toolbars from the same menu would make life a little faster-easier. 

We could also maybe think about the idea that the separator is a button to show-collapse the toolbar after unifying the configuration UX to the same menu+submenus.

**Comment by ReinerBforartists** [comment] 2020-06-21 08:58
I am not convinced. Even you agree that we need a separator between the toolbars. And what is better suited as a separator than the menu to adjust it? Take the separators away and you will have a hard time to navigate in the toolbar. This has trapped me in trueSpace before. And that's why i use the menus as separators here. As told, this is by design.

**Comment by Draise14** [comment] 2020-06-22 16:13
Yes. You need separators. I'd prefer them to be a toggle to show-hide the particular tool types. The configuration menu is suggested to be in one place.  

Concerning what is better to adjust a menu, it is the method proposed with this feature request:

1. 1 click on one menu to activate toolbars
2. Move mouse in short distances to activate toolbars, click to toggle
3. Move mouse more short distances to multiple submenus of toolbar to activate groups of icons. _Always in the same place, so easier to visually memorize._ Click to toggle
4. Leave menu - entire toolbar is configured to user preference from the one menu activation. 

The current solution UX to compare:
1. 1 click on one menu to activate toolbars
2. Move mouse in short distances to activate toolbars, so far so good , click to toggle 
3. Then leave that menu. 
4. Move mouse far distances to click another menu used as a separator. 
5. Move mouse in short distances to activate the groups of icons. Click to toggle.
6. Leave that particular menu. 
7. Repeat 4-6 for every toolbar type you want to configure each at individual menus moving and changing locations. _Visual memory of these toolbar menu positions are dynamic and change according to how you have it configured.._  

And as you can see, without putting all the groups and types in the one same menu and sub menu, we have already increased UX time and UI complications by at least 50%. 

I'm not asking about removing the separators, that's a side thought - but unifying the group toggles to be in the same menu as the type toggles so it's all in one place. 

And.. as a compromise, I encourage keeping the separators and instead using them as a visibility collapse toggle instead. I agree, you would need them for visual hierarchy.

**Comment by ReinerBforartists** [comment] 2020-06-22 16:30
I understand the arguments, but i am still not convinced, sorry ^^

Adding a one menu solution would mean that you have to dig in a hierarchy. That you start to search what belongs where. And you waste more space since you want to keep the separators and add one more menu. I have made the separators the menus. Which is for me the superior solution. The menus belongs to the bars, and are asides of it.

The only solution that i could think of is to hide the separators and so the menus completely away. That would free four, maybe five buttons per toolbar editor. And you loose the separators then that visually helps you with navigation. Is that worth it?

**Comment by Draise14** [comment] 2020-06-22 17:03
I'm still finding it hard to counter argue myself with this with you, but I get what you are on about with the separators. Let's try make the proposal clearer. 

**Current solution:**
![PureRef_4hWa5DOELJ](https://user-images.githubusercontent.com/35357409/85313911-5b5e3100-b47e-11ea-8b0c-efd6d78d5a1a.png)
- You have to zigzag to configure things
- Hierarchy of toolbars is a somewhat disjointed. **A** then somewhere else there is **B**. 
- A separator as a visual aid is also is known as a configurable menu 
- by proximity, the header of a particular type would make sense if you want to configure that isolated menu, unless you want to configure everything at once - then you zigzag. 

**Proposed solution:**
![PureRef_ECbeoCmAGe](https://user-images.githubusercontent.com/35357409/85313971-6c0ea700-b47e-11ea-897b-c7f633b2790d.png)
- Configuring all toolbars is the same menu as the types menu (no new menus). 
- A separator as a visual toggle, as a separator is a visual aid (per requested feature in #1502)
- hierarchy of toolbars is now visually and configurable logically - **A** then **B**. 
- No zigzagging needed over the UI to configure all the toolbars. 
- Everything can be configured at once quickly. 
- Downside is that to configure a toolbar, I have to go to that one place and a submenu to toggle subgroups - but upside is I won't have to zigzag a lot to do it to multiple ones. 

Maybe the key issue here is that we have to click then navigate into many submenus anyways to get to the toggles - so making it less effort is ultimately the purpose of this request. Less sub menus in different locations, less zigzagging. Maybe just throwing them up the properties one level might solve this with another compromise.

**Comment by ReinerBforartists** [comment] 2020-06-22 19:04
This is not how it works. A toggle cannot be a menu too. It is an operator. And we loose the connection between the menu and the corresponding toolbar.

**Comment by ReinerBforartists** [comment] 2020-06-23 06:52
The more i think about it the more i see just drawbacks and no benefits from unioning the menus into one.

Just that i have mentioned it. In case of heavy adjustments, you can also activate toolbar items from the addon. Here you have the all in one menu. I could do a cleanup here. This code is from 2.79, not responsible, and not really nice alligned.

Another idea, we could throw out the menus and use panels instead. Panels stays open when you click at a checkbox. Menus not.

![allinone](https://user-images.githubusercontent.com/13919702/85370307-c6ffd700-b52e-11ea-975f-369439527231.jpg)

**Comment by Draise14** [comment] 2020-06-23 13:42
Yeah, those aren't great solution either, going to permanent panels elsewhere or needing to open up user prefs, then find the addon config (assume you know it exists), then configure the addon config.

> This is not how it works. A toggle cannot be a menu too. It is an operator. And we loose the connection between the menu and the corresponding toolbar.

There already is a disconnection, a toolbar type is in one place, the type groups are in another place. It is disconnected. This proposal has been requested by a number of users, and I see the logic proposed because we feel it is disconnected right now. I'm just trying to advocate for them, sorry for being so persistent! 

I guess since you can't nest property menus, you could have a separator with the property to toggle the type, then the group props below in the same menu. 

![image](https://user-images.githubusercontent.com/35357409/85409594-9f5b3f80-b52b-11ea-8b3e-0cc8578e003a.png)

In this case, the hierarchy to configure is still the same, just connected with type and group toggles in the same menu toolbar instead of having it hidden in submenus per separator - where you'd first configure a type, then look for the submenu for the groups then configure the groups. 

But as you suggest, maybe instead of a sub menu, making a click to floating panel like the main toolbar type configuration might work? So atleast the toolbar configuration and group configuration UX is consistent?

**Comment by ReinerBforartists** [comment] 2020-06-23 17:03
No problem. Keep it coming. As long as i keep the thread open everything is fine :)

I just have to decide at one point if it is a user request that makes a few happy and many not, if it is really an improvement, and last but not least if i am clever enough to manage it :)

**Comment by ReinerBforartists** [comment] 2020-11-22 16:59
This one is fixed by the commit to implement the quick toggles in the toolbar editor. Closing.

**Closed by ReinerBforartists** 2020-11-22 16:59 UTC
Labels: Experimental, Feature request
