### ISSUE TITLE
Linux Builds - Scroll Wheel Zoom is Inverted in 4.1.1

### ISSUE THREAD

**Issue by Kagukara** [Bforartists/Bforartists#4291] opened 2024-05-19 16:27 UTC
**Describe the bug:**
When using the scroll wheel in version 4.1.1 of the AppImage scrolling forward zooms out and scrolling backwards zooms in. This does not occur when using 4.1.0.

**System Information:**
- OS: Arch Linux
- AMD Radeon RX 7900 XTX (radeonsi, navi31, LLVM 17.0.6, DRM 3.57, 6.9.1-arch1-1)
- AppImage Version: Bforartists-411.glibc2.35-x86_64.AppImage

**Comment by ReinerBforartists** [comment] 2024-05-20 05:50
I read this the second time now. And it still baffles me. The keymap is the same than the regular deb or tar. It should therefore technically not be possible that the appimage has other controls.

I wish i could check it. But at my VM i can build it, but not longer test it because of graphics driver issues with the VM. It throws an error that OpenGL is too low.

**Comment by Draise14** [comment] 2024-05-21 17:06
I have opened it up in Debian VM, and indeed the zoom is inverted. But it's a toggle in the preferences folder that will rectify. I wouldn't know why it's inverted though, since the keymap is identical from Windows to Linux builds. 

![image](https://github.com/Bforartists/Bforartists/assets/35357409/8fe76432-45a5-4070-8291-6a34d511029a)

**Comment by Draise14** [comment] 2024-05-21 17:07
Window scroll is also inverted.

**Comment by Draise14** [comment] 2024-05-21 17:12
I will do a new build environment to see if I can fix it in the debian build.

**Comment by Kagukara** [comment] 2024-05-21 22:23
> Can confirm. I have opened it up in Debian VM, and indeed the zoom is inverted. But it's a toggle in the preferences folder that will rectify. I wouldn't know why it's inverted though, since the keymap is identical from Windows to Linux builds.
> 
> ![image](https://private-user-images.githubusercontent.com/35357409/332515862-8fe76432-45a5-4070-8291-6a34d511029a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzMzAzNzEsIm5iZiI6MTcxNjMzMDA3MSwicGF0aCI6Ii8zNTM1NzQwOS8zMzI1MTU4NjItOGZlNzY0MzItNDVhNS00MDcwLTgyOTEtNmEzNGQ1MTEwMjlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDIyMjExMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2ZGI3NTg3ZTc4NDhiNjIwMTY0NDM3MDdhOTdkODQ5OWQ2MDI0ZWFlM2UxYTAxZWIyZTYzOWQxOWQ2ZDBhZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MMdzZJLSQq2npHts2GG4iVSdzddUDMWkoHLNrk23_Kc)

This doesn't fix it for me/doesn't do anything when ticked.

Hope the new build fixes the problem.

**Comment by Ams-ARB** [comment] 2024-06-07 04:33
Hi, was this ever fixed? I have been having this issue for a while as well. The 3D view zoom invert can be fixed with the Navigation setting; but the window scroll remains inverted.
I found this related to it: https://projects.blender.org/blender/blender/issues/107676
It seems to be a wayland related issue. 

Saw this was the workaround fix for now: https://projects.blender.org/blender/blender/commit/d6448732521a64809c6827745f8d002f082bbd38

Idk if this is implemented or can in the next build Im not aware of the dev process. Over the month I tried finding any solution nothing works. This isnt an issue in the older build or regular Blender either.

**Comment by ReinerBforartists** [comment] 2024-06-07 05:35
Thanks for the hint, we will look into it.

**Comment by ReinerBforartists** [comment] 2024-06-07 05:39
Mh, from what i understand, the problem is Wayland. The fix in Blender already exists. But when you have an old Wayland installed then it doesn't work. And then there is little that we can do.

**Comment by Ams-ARB** [comment] 2024-06-08 03:25
I have the latest Fedora KDE, but have the issue. Not saying it means latest Wayland, but if this is an issue on latest Fedora it might be widespread (?). Is it possible to add a way to invert scroll software wide as suggested in the workaround? Ill see if I can find a way to upgrade wayland version. 

Still not sure why regular Blender works fine though. Ill try the latest Blender beta release see if that works too. I might need to port settings to regular Blender if it does, or rollback BforArtist version.

**Comment by Draise14** [comment] 2024-06-11 14:54
Did a fresh build on Debian an worked a build of the up and coming Bforartists 4.2.0. Might be fixed in the backend from Blender. There is now no inverted scroll. 

Should I try make another VM with your target Linux Distribution to double make sure that it's fixed?

**Comment by Ams-ARB** [comment] 2024-06-13 01:01
Is there a time frame for when 4.2 will be out? I can wait and test myself. 
If its long you can check, Its Fedora 40 KDE.

As for need more information, I cant find anything. I posted this on fedora forums too and got nothing there. Its a very bizarre issue, hopefully its random and new version fixes it.

**Comment by ReinerBforartists** [comment] 2024-06-13 05:47
Next version of Blender usually appears four weeks after going beta. Which happened last week.

For new versions, Blender offers nightly builds here. And when it is not fixed in the newest Blender alpha, then it is most likely not fixed at our end neither: https://builder.blender.org/download/daily/

**Comment by Ams-ARB** [comment] 2024-06-13 06:25
I just checked both 4.3 build and 4.2 build. Both have fine scroll, so hopefully the issue is fixed upstream.

**Comment by Draise14** [comment] 2024-06-14 16:23
Ah ok, so we should have that fix then. I will close. If you notice it again in the appimage of the future, let us know!

**Closed by Draise14** 2024-06-14 16:23 UTC
Labels: 2 - bug, Needs more information
