### ISSUE TITLE
3D View - Tabbed Tool Shelf - Add Constraint (with Targets) should go to Bones Constraints in Pose Mode

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2666] opened 2021-09-14 21:03 UTC
**Describe the bug**
![image](https://user-images.githubusercontent.com/35357409/133333245-a5292d20-fbcd-4f5c-b310-5995db6b79dc.png)

For some reason, the operator in the Tabbed Toolshelf to Add Constraint (with Targets) adds the modifier, but it's not listing in the constraints tab. It shoes the Last Operator panel, it adds a constraint to a degree, but it's.. just not listing it. 

The same operator in the header works fine. 

Weird.

**Comment by ReinerBforartists** [comment] 2021-09-15 05:51
Indeed O_O

**Comment by ReinerBforartists** [comment] 2021-09-15 06:07
Hm, cannot reproduce. It works just fine here. It's in fact the same operator than from the text menu. No difference.

What are the exact steps to reproduce?

**Comment by Draise14** [comment] 2021-09-15 16:39
Ok, let me try to reproduce in factory, then will log.

**Comment by Draise14** [comment] 2021-09-16 11:59
1. Create Armature
2. in Edit Mode, duplicate the bone.
3. In Pose Mode, select one then the other
4. Go to the Toolshelf Panel, Constraints, then Add Constraint (with Targets) - add any
5. Go to the property shelf - Bone Constraints tab, notice the operator registered into the undo stack, but not in the constraints panel in the property shelf. Nothing actually happened - it only adds a constraint to Object (entire armature). 

Just tested this with a factory reset and the latest dev build. 

![image](https://user-images.githubusercontent.com/35357409/133608143-029616b3-018b-4a1a-bf85-edcb21b1fda2.png)

I found the issue.. it's working fine, but for OBJECTS. Not BONES. 

Desired UX is for bones constraints, since you're in bone pose mode.

**Comment by ReinerBforartists** [comment] 2021-09-16 12:53
Hm, have i added the wrong operator here? I'll check :)

**Comment by ReinerBforartists** [comment] 2021-09-16 12:57
Indeed. I have added the object.constraint operator here. Excellent catch Draise. Thanks. I'll have a look to fix this :)

**Comment by ReinerBforartists** [comment] 2021-09-16 13:01
This is something bigger. We miss the constraints in object mode. I'll have to investigate a bit deeper here.

![constraintsinobjectmode](https://user-images.githubusercontent.com/13919702/133616664-c45c433c-fb4f-47e7-adb7-1faa242faecd.jpg)

**Comment by ReinerBforartists** [comment] 2021-09-16 16:16
Ah, constraints is essential for IK. But for objects you better use the modifier tab. Or the Object menu. It is rarely used. So i will not add the panel to object mode.

**Comment by ReinerBforartists** [comment] 2021-09-16 16:17
Fixed in master

**Closed by ReinerBforartists** 2021-09-16 16:17 UTC
Labels: 2 - bug
