### ISSUE TITLE
Asset Browser - When linking collection to scene, allow toggle to center to world and default it to on. 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3569] opened 2023-06-06 19:18 UTC
![image](https://github.com/Bforartists/Bforartists/assets/35357409/a85f1216-802e-4de4-8c47-3edf2327bd33)

# The Problem:
When linking a collection to scene, you offset the linked data to a new world center. Now when you instance the same collection into the scene at any other time, the instances has an offset world center - breaking the desired UX of all instances (where you have instance at world center at instance origin). 

Showcased here:
https://user-images.githubusercontent.com/25260650/243147112-ad8319a2-803c-4bb9-96de-1d18ab38b290.mp4

**To reproduce:** 
1. Go to the default library
2. Go to the collections section and find the shader ball
3. Drag it in anywhere away from world center and in the Repeat Last operator, turn the Instance toggle off
4. Now drag the same collection in, then in the Repeate Last operator, turn it Instance toggle on
5. Take note that the instance is offset, when it should be at the instance center. 

This will be true in all instances, they will be offset every time you link the collection data to scene to any new location. 

**The reason:**
When you link to scene, the location is offset. This offsets the center of world of all consecutive instances, making the origin center of any instance useless for layout. 
![image](https://github.com/Bforartists/Bforartists/assets/35357409/8568647b-8cd0-4540-acd5-2cf0c2c7ddf6)

## The solution:

If Link Collection with Link to Scene mode (Instance off) then link to scene at world center (0,0,0) instead of mouse cursor. 

Make this overridable as a user preference with a toggle - link to world center, or link to mouse cursor. 

Default linked collections to world center preference to avoid unknown offsets when linking as instance. 

User toggle icon to link to world center could be this one:
![image](https://github.com/Bforartists/Bforartists/assets/35357409/f5be6563-b078-4fc7-9e09-a590428edd70)

### Example
![PureRef_yxCyD5LJs3](https://github.com/Bforartists/Bforartists/assets/35357409/1d234c4d-ae53-437e-bff1-07c5be5ac8d0)

When you have the link as Instances off (#3562), a new button toggle shows, this is to reset linked collection origin to center, or default Blender behaviour (at mouse) which is.. effed. 

But default is on. So when you link collection to scene, it is ALWAYS at world center making any undesired linking as instance work NOT have any offset. Per expected user UX. 

Linked collections need to be overridden to be useful anyway - so making the user revert to the expected overriding UX might be useful and less frustrating. No default broken offsets.

**Comment by ReinerBforartists** [comment] 2023-06-07 05:35
Not against fixing this one, but this is the kind of stuff that should be fixed by the Blender devs in the first place. But yeah, it is UI UX design, and won't be considered as a bug since it works as intended ...

**Comment by Draise14** [comment] 2023-09-09 02:49
I don't see the toggle to turn off and on in the header. Was that commit too? I'll test tomorrow.

**Comment by Draise14** [comment] 2023-09-09 13:14
Yeah, have to re-open due to the fact that now the toggle is broken when trying to append a collection to scene not as instance.

**Comment by Draise14** [comment] 2023-09-09 13:33
Here is the desired UX.


**if** drop_collections_as_instances = **true**
    _add collection as instance at mouse position, per normal_
**if** drop_collections_as_instances = **true** && drop_collections_to_center = **true**:
    _add collection as instance  to world center, as instance
**if** drop_collections_as_instances = **false** && drop_collections_to_center = **true**:
    _Add asset collection to world center, but not as instance_
**else**
    _Add asset collection to original mouse position, per normal_


Meaning a new header prop and.. working the conditionals in the C I guess. Keep at it @iyadahmed ! Through this I'm also learning some of the C++ things going on.

**Comment by Draise14** [comment] 2023-09-11 18:19
https://github.com/Bforartists/Bforartists/assets/35357409/3b6f44fe-9a05-4169-a348-768f2ea2d5a7

Looks like it still needs work: When "As Instance" is disabled, it still adds the collection as instance. Should append/link collection to scene.

**Comment by iyadahmed** [comment] 2023-09-11 19:20
https://github.com/Bforartists/Bforartists/issues/3761

**Closed by iyadahmed** 2023-09-11 19:20 UTC
Labels: 0 - task, Experimental
