### ISSUE TITLE
3D View - Object Header menu - Relations menu misses content

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3198] opened 2022-08-17 00:44 UTC
## Blender:
![blender_ypZLlyJdKX](https://user-images.githubusercontent.com/35357409/185009104-5c85cb56-20be-4505-b6bc-4cb5d025bee9.png)

## Bforartists:
![bforartists_8he7ZiJr9l](https://user-images.githubusercontent.com/35357409/185009114-c0d6c0aa-6855-4936-86b8-a194f5fa8a3b.png)

We probably should double check this. I know these entries are in the toolbar, but indeed they are non-existent in the header. 

**To reproduce;**
- Link a collection or object from another blend
- Select it
- Then observe the difference in the menu (Blender daily vs Bforartists)

**Comment by ReinerBforartists** [comment] 2022-08-17 04:44
The manual shows it like in Blender, so we have a bug here.

**Comment by ReinerBforartists** [comment] 2022-08-20 15:59
This is a regression in version 3.2.2. 3.2.1 has still the full menu

![regression322](https://user-images.githubusercontent.com/13919702/185755802-ab0bfa81-3caf-4ec7-92be-e7b27b0052c6.jpg)

**Comment by ReinerBforartists** [comment] 2022-08-20 16:01
The cause. Always look in the console when such things appears ...

![cause](https://user-images.githubusercontent.com/13919702/185755879-074e1755-27bf-4f46-a5e5-a190a978d021.jpg)

**Comment by ReinerBforartists** [comment] 2022-08-20 16:09
No idea where this extra operator came from. We had it never documented. Fixed. The manual still fits.

![fixed](https://user-images.githubusercontent.com/13919702/185756173-1011df75-4b6c-4fa1-83db-5a1ed04d8cbc.jpg)

**Comment by ReinerBforartists** [comment] 2022-08-20 16:11
Let's have a quick look at the operator itself, and what options it offers before we close this one here.

**Comment by ReinerBforartists** [comment] 2022-08-20 16:14
Nope, this do_fully_editable option definitely doesn't exist anymore.

**Closed by ReinerBforartists** 2022-08-20 16:14 UTC
Labels: 0 - task, 1- Fixed
