### ISSUE TITLE
3D View - Missing operators in header - Add them back and rename to "Quick" operators

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1721] opened 2020-08-05 17:42 UTC
# Issue
Right now, in the discord server, a number of active users, even a couple of long term ones have pointed out an inconsistency and design choice we made that is now causing issues... and this is making things not great for the BFA users ultimately. 

Our choice was to remove redundant operators and unify them into the one toolshelf one - and move the hotkeys to the toolshelf tools where possible. Then we removed the repeated legacy operators that were redundant in essence. 

But now here is the issue they have kindly elaborated: 
![image](https://cdn.discordapp.com/attachments/662282900691222528/739145739887837268/bfa_feedback_menu.jpg)

![image](https://user-images.githubusercontent.com/35357409/89443284-b2118880-d715-11ea-8aa3-0489e79ecdba.png)

![image](https://user-images.githubusercontent.com/35357409/89445598-036f4700-d719-11ea-924d-98b7a60ea5de.png)

Another example:
**The Loop Cut and Slide** 
- Exists in the toolshelf but work in a different way,
- This is Documented in the manual
- Documentation is set to the legacy method, not the new method. 
- The legacy method is no-where in the UI now
- A user following a blender tutorial now doesn't have access to this tool
- This tool is accesible in the API and "Specials" double right click menu only, hidden there. 
![image](https://cdn.discordapp.com/attachments/662282900691222528/739170096295051304/unknown.png)

# Feature request
So... to solve this and come to a compromise... the policy we have here is: 
1. No hidden operators or keyboard exclusive operators. 

Second... 
2. No redundency. 

So.. we probably should expose and add these legacy operators to the header again (don't add hotkeys) and rename them to not be redundant - something like "Quick Tools" to avoid new user confusion. 

Eg. 
(Legacy) Extrude = **Quick** Extrude (Tooltip saying this is a quick act once extrude way, legacy, etc)
(Legacy) Loop Cut and Slide = **Quick** Loop Cut and Slide (Tooltip saying this is a quick act once loop cut and slide, legacy, etc)

In fact, to keep things minimal, we can have a whole new Quick Tools header entry for the redundant operators instead of the extra large and confusing repopulated menus. 

### Benefits
They have pointed out a number of key features 
- Compatibility with Blender tutorials and features
- No more hidden operators or workflows
- More options for frequent users and artists to be able to assign hotkeys themselves or use quick operators instead of the slower widget and mode based toolshelf operators by user choice. 

Relevant tasks that tried to tackle this redundant operator issue #620 and #737. 

So... I think to avoid redundancy, we should rename the legacy tools to "quick" tools and to avoid hidden operators, we should expose them for the user, but keep the hotkey maps to the toolshelf for UX consistency, preserving our changes there - yet still expose what a power user and/or a blender compatible user would expect. 

##### Notes
_I know this feels like a big regression.. but in a span of a week, I've got some users really put in time saying they love BFA, but they find this issue their biggest complaint when it comes to learning Bforartists and using it routinely. It also feels like it is a somewhat half baked solution, what we did to reduce the redundency, like CTRL+R pulls the legacy tool, not the toolshelf tool, etc... and there is no strong justification or consistency there. I hope this idea is ok to pitch... just voicing some of our frequent users_

**Comment by ReinerBforartists** [comment] 2020-08-05 19:11
Hm. This issue makes me think if the fork is still needed. I don't want to have Blender with just a few different icons. That's not what Bforartists stands for. But that would be the result when we revert our changes. 

The decision to get rid of the old operators was a design decision. When we still have hotkeys that pulls the old tools then we should have a closer look at the keymap.

**Comment by Draise14** [comment] 2020-08-05 19:23
The fork is still needed, mainly due to the visual system of working in 3D, the UX improvements everywhere, minimization, cleanup, and better tooltips, and a bunch more reasons - and the amazing toolbar. No doubt there. Just... some of these operators that we hid on purpose maybe wasn't a good idea... nothing wrong with the fork. 

I do think a quick tools header entry for these "redundant" operators might help. They are already in the specials menu. They are only a handful to add back.

**Comment by ReinerBforartists** [comment] 2020-08-06 06:17
Yeah, i completely understand where you are coming from. But again, this is not what Bforartists stands for. It is no Blender clone with a few neat icons. We are much more, we are different. And our evolution leads usually away from the Blender UI, not closer to it.

If we would miss functionality then we need to add the entries back. That's a no brainer then. But the functionality is all there. It's just in the new toolset now, available in the sidebar. And so i don't see a reason to add those operators back. They are still available in the right click menu because i haven't arrived there yet with my work. I may remove them from there at one point too.

The more interesting question is how can we make the new operators more attractive so that people don't miss the old operators anymore. And as told, we may need to clean up the keymap again. That's all part of the evolution.

The old toolset is also available across the search by the way. That's the curse with this hack called tool shelf. It is not proper implemented, not proper though through. I think i told you before, the Blender devs are still not aware what they did there.

When it really bothers you this much then you could simply create an addon that contains these entries, active in Edit mode, and append it to the header. But i don't see the need to do this in the Master.

**Comment by Draise14** [comment] 2020-08-06 12:33
Yeah, guess an addon could work. Could this be included with BFA by default? 

_Rant on. Just to personally say ... I think Bforartists stands for everything about "being for the artist"... not just to be different to Blender. If our artists ask for something, and from multiple users... what's the procedure? (even if it feels similar to Blender)

Also.. It's a little sad to hear that users have to make addons to add and fix their solutions - which is what the Blender developers do: they put a gate to user requests and ideas, and since they won't do it, it has to be done as an addon - and more so through a non-centralized addon distribution system. Now there are addons everywhere and also nowhere, but the core development is restricted from the requests of the general artists (and at a loss for doing so - so many great ideas and code out there that could be and should be in a master).

I like being different to Blender (and with reason), don't get me wrong.. just.... I am now just wondering about the priority of Bforartists: Be for Artists - not just be different. Rant over._  

But yes, I wish the legacy operators were combined in functionality with the toolshelf addon - better one good method than multiple half baked ones. I like the widgets, but I also sometimes prefer how the legacy ones works sometimes - loopcut and slide with the mouse wheel to add loops from the legacy is still superior to the toolshelf one. How do you think those fixes are possible? How can you add the modal system AND the widget system into one? Just updating the keymap doesn't fix anything... this sounds like actually fixing those operators at their base functionality and how they work in the core architecture.. not just a UI issue, but more a UX one. 

Concerning the operators he mentioned, or the conflicting hotkeys that go to legacy, or the suggested removal of all evidence of these legacy operators (even from the specials menu) - should I post them individually as tasks? After cleaning up that consistency issue (which is the opposites of the feature request, haha!) To make an addon official for BFA, what is that procedure? That one I can code.

**Comment by ReinerBforartists** [comment] 2020-08-06 15:52
It is not broken. It is just different. As told, when you find missing functionality feel free to make a bug report. Then we have something to fix.

Not sure if we should include such an addon. It's a step back. It's like all those dozen UI addons for Blender that fixes at the symptoms instead of the cause.

>loopcut and slide with the mouse wheel to add loops from the legacy method is still superior to the toolshelf one

This would be a first point to tackle. To see if we can manage something here. But that's fixing at the tools. Which i want to avoid when ever possible. Already nowadays the merges are killing me from time to time. So this is best reported to the Blender developers.

And i am honestly not sure how to proceed with the legacy stuff at this point at all. I can see why people are unhappy. But i haven't found a satisfying solution yet. We would really need to go through these operators at a one by one case. So yes, make an issue for every single case. Then we can tackle it one by one.

But note that i am still at completing the manual. This has highest priority for me. Everything else comes after the manual is completed.

**Comment by Draise14** [comment] 2020-08-07 17:58
No problem on the wait. 

Yeah, the whole legacy and mode based toolshelf system by Blender™ is really off.. 

I'll make a task for each tool by tool rwith the edundency-merge-optimization for better UX, meanwhile in holidays end of this month I'll work on the addon for the user on Discord.

**Comment by ReinerBforartists** [comment] 2020-10-31 12:39
Manual is long finished. Means we can tackle this one now. Maybe you can ask Iyad if he can implement the old toolshelf functionality back so that we can add some panels here again. I failed at it so far. 

Issue is still open. https://github.com/Bforartists/Bforartists/issues/1402

And the toolshelf branch is also still available. But the general problem was to get the panels back into this location.

**Comment by ReinerBforartists** [comment] 2020-12-05 13:56
The original task is fixed in task 

Add back the old operators into the edit menus #2028

So closing this task.

**Closed by ReinerBforartists** 2020-12-05 13:56 UTC
Labels: Feature request
