### ISSUE TITLE
3D View - Quick Toggles for Grid, Wireframe and decorations 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1652] opened 2020-07-02 20:27 UTC
# Feature Request

In the 3D View> view controls has a quick toggle for grid, wireframe and decorations (without turning off overlays). I think this is Genius and useful. 

![bforartists_Ve1lbfMdCg](https://user-images.githubusercontent.com/35357409/85156133-3e77f280-b21f-11ea-8a90-c450ec323c21.png)
![bforartists_GwJYjAQWZc](https://user-images.githubusercontent.com/35357409/85156139-3f108900-b21f-11ea-8084-2884f16a502d.png)
![bforartists_gtiiRYkyif](https://user-images.githubusercontent.com/35357409/85156140-3fa91f80-b21f-11ea-90ce-e59b3ea64cc6.png)

### Reason
The wireframe toggle is often pressed, but it's burried in a submenu. Xray is in a submenu, but also in the header for that reason. Grid can also be toggled with the same consistency.  

Also a quick toggle for the objects and things but not overlays would be nice (hide lights, empties, etc) so you can keep wireframes on geometry and other overlays but reduce visual viewport clutter in one click. 

Right now, to do the later, you have to go into a sub menu and drag on a number of entries to do it, click and drag, and also ready what is what that you want to hide - not very fast. A one click solution would nice. 

# Task
- Check how to implement this, 
- Maybe make icons for them, 
- Add them to the 3Dview header. 

#### Note
This is a feature request seen in the Bforartists XT fork #1633

**Comment by ReinerBforartists** [comment] 2020-12-11 07:56
Hm. I have a problem here with the double entries then. And we cannot remove Wireframe from the panel since it has settings. And the header is already pretty crowded up right.

Question is, do you really click these buttons permanently so that it makes sense to put them at the top hierarchy? Like every two seconds? Why not also put the statistics at top level? Or the 3d cursor? Or the origins? Yes, it is one more click. But it is better organized to have these settings in its own panel. And power users could add a shortcut to the wireframe for example.

The only thing i see here where it could make sense is the ground grid as a whole. Including its settings. But that's two more buttons then.

**Comment by Draise14** [comment] 2020-12-11 14:35
I change them often enough to have to dig through a panel with more than a few dozen entries multiple times a day, specially when rigging, weight painting, modeling, sculpting then back to modeling, etc. They should be a lot more accessible, there is no doubt. It can be slow and frustrating, and having them in an icon-less quick menu (workaround) doesn't work when you already have it populated with 7 or more entries. Not to mention.. with or without the quick menu, these panels don't have icons so digging for them is even harder when there are more than a few dozen entries.  

# **New Mockup**

![image](https://user-images.githubusercontent.com/35357409/101914707-a0902f80-3b92-11eb-8f50-0a6aa6d4a943.png)

You are right, we could be crowding the header with 4-2+ icons, but we could also only add 1 icon space to the overlay group so there are two "dropdowns", easier digging. 

Here is another mockup, instead of in the header, have it as another dropdown in the overlay group. 
![image](https://user-images.githubusercontent.com/35357409/101915206-4cd21600-3b93-11eb-8f0b-200c5659031c.png)

Pro's:
1. Priority panel, for Wireframe Grid toggles and settings
2. Secondary panel, for everything else
3. Still keep the settings in panels
4. No crowding the header
5. No need to dig through and filter between common and uncommon overlays
6. This overlay workflow could be applied to all the modes, like Sculpting is REALLY huge, splitting it into two would help a lot. 
7. No double entries. 

# Alternative
Expose the on/off of the grid and wireframe to the header, but keep the settings in the dropdown panel. +2 icons. The panel won't show the on/off, and raises their settings to the top of the panel.

**Comment by ReinerBforartists** [comment] 2020-12-11 16:55
Yes. Not so easy. Let's think about this a bit more.

**Comment by Draise14** [comment] 2020-12-13 22:24
**Mockup 2**

A friend of mine made an addon with Serpens to change the object wireframe, axis, and name toggle, along with bounding box, based on selection toggling. It's not very performant right now, but the idea is nice. 

In Bforaritst 1, we had a quick wireframe toggle and system for object selections, which was very useful. i think this is what I miss the most. Maybe instead of exposing the global toggle, we expose controls for per object wireframe toggling? 

Beats digging into the object properties then sub panel. 

![bforartists_CwQGJgQgak](https://user-images.githubusercontent.com/35357409/102025713-e2260380-3d67-11eb-9635-b5fb46a63163.png)
![bforartists_p8K9VMmqos](https://user-images.githubusercontent.com/35357409/102025716-e4885d80-3d67-11eb-9f1a-e1dc91a82d53.png)

**Comment by ReinerBforartists** [comment] 2020-12-14 07:04
Mh. Addon means we don't need to do it anymore? :)

**Comment by Draise14** [comment] 2020-12-14 07:19
It's not performant and not pre-included with BFA. But the idea is kinda what this task is going for.

**Comment by ReinerBforartists** [comment] 2020-12-14 07:21
I doubt that our solution will be any more performant. And when an addon exists, why should we reinvent it then? Including this addon is also no option, we don't maintain third party addons. And last but not least, i simply doubt that a normal user will use this toggle more than once in a month. 

As told, this one needs much more thinking.

**Comment by Draise14** [comment] 2020-12-14 07:34
I started using the wireframe toggle within 10 seconds that it existed, and toggled it numerous times before I noticed the performance hit. Right now the poll to swap the icons for on/off is slowing it down, as it passes an if else statement over and over again. It could just be an act once toggle which would be much more performant. 

I really do toggle this a lot if I can. It's like toggling the overlays to just see without decoration, then jump back, or jumping in and out of a camera, or to get wireframe into sculpting, weight painting, etc. Most software has atleast the wireframe toggle pretty exposed. We've seen it first in a fork of this fork, in Softimage, in trueSpace, in Maya (number row hotkeys), in an addon.. it's a UX that's needed by users. 

I wouldn't consider it a power user feature, just.. a viewport baseline feature. We had this in Bforartists 1, a leg up over Blender default, would be great to also have something similar in Bforartists 2.

**Comment by ReinerBforartists** [comment] 2020-12-14 07:36
It is there, just in a panel. And this gives me the headache of double menu entries then too.

**Comment by Draise14** [comment] 2020-12-14 07:42
Yeah. I guess the task needs to change. 

Global Wireframe doesn't have to be double, just more accessible, or more organized so the UX to use it more often isn't so painful. 

Local Wireframe exposed to 3D View panel or something like in Bforartists 1 could be another task.

**Comment by ReinerBforartists** [comment] 2020-12-14 11:47
Yes, that's the design part of this task, to make the functionality more accessible. And i am still unsure how to solve it. I want to avoid doubles.

In BFA 1 there was no toggle in the 3d view panel. I think you mean the wiretools addon. But it was also not at top hierarchy. But in a panel in the sidebar. Hmmhmm.

![wiretools](https://user-images.githubusercontent.com/13919702/102077977-6d57d580-3e0a-11eb-8cc6-24e8dfd3e235.jpg)

**Comment by Draise14** [comment] 2020-12-14 16:33
> 
> 
> Yes, that's the design part of this task, to make the functionality more accessible. And i am still unsure how to solve it. I want to avoid doubles.
> 
> In BFA 1 there was no toggle in the 3d view panel. I think you mean the wiretools addon. But it was also not at top hierarchy. But in a panel in the sidebar. Hmmhmm.
> 
> ![wiretools](https://user-images.githubusercontent.com/13919702/102077977-6d57d580-3e0a-11eb-8cc6-24e8dfd3e235.jpg)

Aye, that addon. Wish it got ported. The good thing with panels is that they can be surface level optionally, or hidden away.

**Comment by ReinerBforartists** [comment] 2020-12-14 16:44
Indeed. It's still in the BFA1 repo. You could try the port :)

**Comment by ReinerBforartists** [comment] 2020-12-19 08:58
What if we put your requested functionality into the Align View addon? That way you can turn it on, it is in the header then. And this addon is meant to contain doubles by design. To allow the user to customize his UI to his needs.

![alignviewaddon](https://user-images.githubusercontent.com/13919702/102685408-a2846f00-41e0-11eb-8302-aa263411117d.jpg)

**Comment by Draise14** [comment] 2020-12-21 16:28
> 
> 
> What if we put your requested functionality into the Align View addon? That way you can turn it on, it is in the header then. And this addon is meant to contain doubles by design. To allow the user to customize his UI to his needs.
> 
> ![alignviewaddon](https://user-images.githubusercontent.com/13919702/102685408-a2846f00-41e0-11eb-8302-aa263411117d.jpg)

Actually... a good idea here. I like it. I haven't had a chance to look at the addon, but from what i know, the coloured wireframe functionality is broken in 2.8+ versions.. as you can't colour wireframes directly.

**Comment by ReinerBforartists** [comment] 2020-12-21 16:44
This functionality is replaced by a random color. I just can't remember where it is ^^

**Comment by ReinerBforartists** [comment] 2021-02-13 10:55
Let's see if we can add your needed functionality into our addon.

**Comment by ReinerBforartists** [comment] 2021-02-13 10:59
Ah, i first need to fix that grid turns off the grid in perspectivic view too.

Draise, a chance to have a look at your addon that you mentioned here?

![gridforall](https://user-images.githubusercontent.com/13919702/107848345-faabac00-6df2-11eb-861d-5aaa6e7ffe97.jpg)

**Comment by Draise14** [comment] 2021-02-13 15:53
Oh, looking forward to this. I toggle the wireframe quite often and my quick menu is too full now. 

This is where I got the buttons idea from, Softimage and a some Bforartists mods from a fork of this fork. 
Download an older version here: 
[https://www.si-community.com/community/viewtopic.php?f=27&t=7180&sid=7ef729e709ad9ac6ae148204407e18d6](https://www.si-community.com/community/viewtopic.php?f=27&t=7180&sid=7ef729e709ad9ac6ae148204407e18d6)

**Comment by ReinerBforartists** [comment] 2021-02-13 16:49
Thanks. Then i will have a look there :)

**Comment by ReinerBforartists** [comment] 2021-02-16 09:37
I could swear we had a task for the grid thingie already. But i cannot find it at the moment.

Let's create it new. And hope that i will find the original issue at one point ^^

**Comment by ReinerBforartists** [comment] 2021-02-23 11:56
Groundgrid button is added.

@Draise, what is the state of the wireframe problem? Are you green with the addon solution? What exactly are you still missing?

Ah that's the reason why i don't like all in one issues. You always end in asking and discussions. If possible please just one issue for one change. 

![groundgrid](https://user-images.githubusercontent.com/13919702/108840075-23435b00-75d6-11eb-9b45-b5513c49bb2f.jpg)

**Comment by ReinerBforartists** [comment] 2021-02-24 09:00
Calling this task done. Added the most used elements into the align view buttons addon now for quick top ui access. We have a little UI annoyance here though. A bigger gap when there is no content of the middle group activated. Let's have a look if i can eliminate this one ...

![overlay](https://user-images.githubusercontent.com/13919702/108975765-1fbbdc80-7687-11eb-9c20-b8b64c9300ae.jpg)

**Comment by ReinerBforartists** [comment] 2021-02-24 09:17
Fixed in master

![better](https://user-images.githubusercontent.com/13919702/108978067-82ae7300-7689-11eb-8043-b00d60d7edcc.jpg)

**Closed by ReinerBforartists** 2021-02-24 09:17 UTC
Labels: 0 - task

**Comment by Draise14** [comment] 2021-02-24 16:45
SO EXCITING. Thanks for adding these here. I couldn't get the coloured wireframes addon working from 2.79, which is more of a Blender feature, so I couldn't get it to work.

**Comment by ReinerBforartists** [comment] 2021-02-24 16:52
Just that i have mentioned it again, the one was just a wireframe addon, and had nothing to do with the colors. The wireframe color was a patch, written in C.

Colored wireframe would have been nice, yeah. But Eevee is another viewport engine. And so the old patch did not work anymore. I had to remove it.

**Comment by Draise14** [comment] 2021-02-24 16:54
Yeah, makes sense.

**Comment by Draise14** [comment] 2021-03-11 20:01
Just have to say, thanks for adding this to the customizable addon for the view header, I have used them immediately and have loved them.

**Comment by ReinerBforartists** [comment] 2021-03-12 07:17
You're welcome :)
