### ISSUE TITLE
Geometry Nodes - Mix Color node is added back to the Color category - add to Add Shelf

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3251] opened 2022-09-27 20:53 UTC
![bforartists_Qpu8hOus0d](https://user-images.githubusercontent.com/35357409/192632905-d2a9791a-3258-4142-9fe3-ca67104325f5.png)

They added the same Mix Color node with a different default to the Color Category in Geometry Nodes. So we should update the Add Shelf. The Utility Mix node defaults to Float. Mix Color defaults do Color.

**Comment by Draise14** [comment] 2022-09-28 12:27
Yeah.. they merged the nodes, then they split it again... jeesus christ.

**Comment by ReinerBforartists** [comment] 2022-10-08 05:51
No icon creation involved, let's tackle it

**Comment by ReinerBforartists** [comment] 2022-10-08 06:24
This task is mission impossible. What the heck. From the add menu it works. From the sidebar it is forbidden ...

Either way, postponing for after 3.3.1.

![impossible](https://user-images.githubusercontent.com/13919702/194692713-17cc865e-4b7d-455c-9ada-d8da599cc53e.jpg)
![shadernodetree](https://user-images.githubusercontent.com/13919702/194692720-913f7083-c54f-436d-936c-1171813f656a.jpg)

**Comment by ReinerBforartists** [comment] 2022-11-07 11:54
I think the cause here is that this particular node has settings. 

Normal operator: bpy.ops.node.add_node(type="ShaderNodeMixRGB", use_transform=True)

This particular operator: bpy.ops.node.add_node(type="ShaderNodeMix", use_transform=True, settings=[{"name":"data_type", "value":"'RGBA'"}])

I am having a hard time though to pass these settings to the python operator . It refuses to work. I tried everything i can think of now. Obviously i missed the working method ...

```
            props = col.operator("node.add_node", text=" Combine Color      ", icon = "COMBINE_COLOR")
            props.use_transform = True
            props.type = "FunctionNodeCombineColor"
            props.settings = "[{"name":"data_type", "value":"'RGBA'"}])"
```

@iyadahmed , do you have an idea how to write the props settings here so that python doesn't fail at it?

**Comment by ReinerBforartists** [comment] 2022-11-07 17:38
I simply can't see what i do wrong here.

I have now at least added (surprise, don't ask me why it initially failed) the prop. It starts with the wrong mode though. The Float mode. Since i cannot tell it to set it to RGBA  mode.

As told, any help is highly appreciated.

![fails](https://user-images.githubusercontent.com/13919702/200377439-88d2da3b-3a82-4de4-86a5-689f9e597a69.jpg)

**Comment by iyadahmed** [comment] 2023-03-01 18:15
Seems to be fixed in master, clicking the button though creates Mix Float instead of Mix Color,
also same issue with Mix Vector button

![image](https://user-images.githubusercontent.com/25552173/222226533-d3dde10f-317d-4f35-bfb4-de41a9d29d8b.png)

**Closed by iyadahmed** 2023-03-01 18:15 UTC
Labels: 0 - task
