### ISSUE TITLE
Cannot activate OpenGl render from VSE viewer

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#71] opened 2018-03-15 15:40 UTC
I have tried adding a shortcut to the OpenGL viewport capture feature  with mouseover, and tried to activate that viewport (the VSE image viewer, the third of the 3 VSE sub viewers) to draw the GP and also render out my animatic notes for collaborative working preproducion - buuuut I can't get the OpenGL viewport to render that particular viewport - as those OpenGl render icons were removed from the view system and now only exist in the toolbar or in the Info Header bar. The default active viewport that BFA detects to render is the 3D View, not the VSE view. 

I need to find someone who is willing to update the VSE.... 

Maybe adding the OpenGL render buttons the view panel in the VSE exclusively (the 3D View areas don't have an issue with shortcut and mouseover assignment). The panel still needs a lot of work, moving parameters out, adding icons, etc... but we need someone else to do it... _I need to work less and work more here and learn how to code more, lol_

![bforartists_2018-03-15_10-38-03](https://user-images.githubusercontent.com/35357409/37473808-f6b3c0be-283c-11e8-83b3-62507c9f6860.png)

**Comment by ReinerBforartists** [comment] 2018-03-15 16:56
Hm, i don't really understand the problem here. We haven't modified the VSE in any way. So what is the problem?

**Comment by Draise14** [comment] 2018-03-15 17:01
![blender_2018-03-15_11-56-50](https://user-images.githubusercontent.com/35357409/37478361-082eefd4-2848-11e8-9c55-079a50486a16.png)

Here is the comparison with Blender: the icons for OpenGl rendering is included in the header. In BFA, these were removed for being a double entry. But now it's impossible to render out a VSE preview render from the viewer, and the solution in other areas through the Info header>OpenGL render and Toolbar OpenGL render icons do not work (defaults to rendering out the 3D View) or with a hotkey with mouseover (doesn't work also). 

_Yeah, it's starting to feel noticed that there hasn't been much work, and it also is starting to feel inconsistent with the rest of BFA.. the VSE needs work. Not a huge priority though, all good. Just need to render out the GP from the VSE for animatic teamwork edits._

**Comment by ReinerBforartists** [comment] 2018-03-15 17:02
Cross posting. 

To repeat my question, shall i readd the buttons in the header or in the menu? :)

**Comment by Draise14** [comment] 2018-03-15 17:03
In the View menu of the view would be more compatible with BFA consistency, I suppose.

**Comment by ReinerBforartists** [comment] 2018-03-15 17:04
Okay, will do.

**Comment by ReinerBforartists** [comment] 2018-03-15 17:19
Fixed in master

https://github.com/Bforartists/Bforartists/commit/5d2c8259158d52506767865a5c3c3a2230143857

![vsefix](https://user-images.githubusercontent.com/13919702/37479432-f06a410c-287c-11e8-9892-7889646e3c74.jpg)

Draise, you can grab the fixed file from the repo, and replace it in your installation. The fie is located in 2.79\scripts\startup\bl_ui\

The space_sequencer.py

**Comment by Draise14** [comment] 2018-03-15 19:14
![bforartists_2018-03-15_13-50-15](https://user-images.githubusercontent.com/35357409/37484881-de152d16-2857-11e8-885b-0b634e2c57cc.png)

I had a bit of trouble, seems when replacing the file, or even just the little bit of code on the View menu entry within the header - it screws up the UI. I must be doing a step wrong. 

So.. I dug a bit and found out what might have been confusing it, and edited the document - please don't be mad! Just I got a bad bug and I actually found a way to fix it! I think I am slowly getting the hang of this. I put in the fixes with comments to revise and tagged them in the file on github.

**Comment by ReinerBforartists** [comment] 2018-03-15 19:18
Huh, here it works. odd. But yeah, Bforartists definitely dislikes a change here. 

Either way, it's time you learn how to use Git and Github it seems. Usually you make a commit with a fix. 

Currently i cannot see what files you have added. I cannot see your edits. And so i cannot commit any fix.

Reopening the issue ...

**Comment by Draise14** [comment] 2018-03-15 19:22
![image](https://user-images.githubusercontent.com/35357409/37486279-0b5dce96-285c-11e8-9fd6-bc3189d5ab54.png)

https://github.com/Bforartists/Bforartists/blob/master/release/scripts/startup/bl_ui/space_sequencer.py

It logged the edit in the file. But yes, I probably should reread the instructions for Github.

**Comment by ReinerBforartists** [comment] 2018-03-15 19:40
Ah, you commited into the master. But your *fix* has removed the buttons in Sequencer view now :/

I still wonder what the problem was. I can still not reproduce it. And i guess you have no way to repeat the trouble, and give me the console output ...

**Comment by ReinerBforartists** [comment] 2018-03-15 19:47
As a sidenote, you did nothing wrong. And it's great to see that you get the hang. But you yhouldn't have been  able to commit files at this point. It should be on ice until i give green light. To prevent such trouble commits. Seems that something went wrong with the commit rights. I'll talk with MoxFulder tomorrow ^^

**Comment by ReinerBforartists** [comment] 2018-03-15 19:50
And last but not least, one of the problems with a python error is that the whole UI vanishes. I have usually hotkeyed the console with F2. That way you can access the Python error. Or you start Bforartists directly from a Windows console. That way you can also follow crashes.

**Comment by ReinerBforartists** [comment] 2018-03-15 19:53
> So.. I dug a bit and found out what might have been confusing it, and edited the document 

It would be great to tell what the problem was ...

**Comment by Draise14** [comment] 2018-03-15 19:55
Yeah, might be good to look at the permissions thing, I found it.. a little too easy to modify the master, sorry about that. 

I will run the F2, problem is easy to reproduce. One moment.

**Comment by Draise14** [comment] 2018-03-15 20:04
Ok, I reedited back the fix away from the conditional, and.. there is no issue anymore. Weird.

OpenGL render buttons are everywhere where they should be, as you intended. 

Till I get really really get a hang for Github and all, then I'll commit in a better way, but meanwhile here is the zip file with your fix, the one I did commented out. For some reason this one doesn't reproduce the issue. Maybe there was some bad syntax somewhere. 

# Download
[space_sequencer - Tiles Fix, working.zip](https://github.com/Bforartists/Bforartists/files/1816923/space_sequencer.-.Tiles.Fix.working.zip)

**Comment by Draise14** [comment] 2018-03-15 20:11
**Previous file:** had the issue with missing UI probably from a python error
**Edited file:** fixed, but caused the inconsistencies with the IF statement (out of ignorance made change to master document)
**Manually edited file reverting changes to previous file:** fixed the issue (uploaded to this thread)

**Comment by ReinerBforartists** [comment] 2018-03-15 20:12
It can unfortunately be everything. Nevertheless, it sounds like we can revert the commit that you did. I'll have a look tomorrow.

Don't worry. It was nevertheless a great first commit. And we both learned something here :)

How did you do the changes? Was it directly at the github page? Or have you downloaded the repository, and commited it by Git? That would be the preferred way. Never, NEVER edit files directly at Github! ^^

I had meanwhile a look at the rights. And it seems that it is a everything or nothing thing. So i think it's good to remind at the golden rule to work in branches. That's something i can decline when it's not so optimal, or merge when it works then. As told, i am in a special situation. I would merge my bugfixes anyways ...

**Comment by Draise14** [comment] 2018-03-15 22:06
I went into the file on the Github file browwer in the web browser. There is an icon button to the top right that says "Edit" where you can submit the edit. 

Ok, so branches and the desktop Git pusher. Gothca. Great to be more a part of the team.

**Comment by ReinerBforartists** [comment] 2018-03-16 07:48
Sorry for the failed communication. I did not expect you to enter the arena this fast. You have PM ;)

I have reverted your "commit" now. And will turn the status of this issue to fixed and closed again. Since i cannot reproduce any problem with my solution, and you said it is now working.

**Closed by ReinerBforartists** 2018-03-16 07:48 UTC
Labels: task
