### ISSUE TITLE
BFA 2.7 Cycles render crash

### ISSUE THREAD

**Issue by Blenderblunder** [Bforartists/Bforartists#2210] opened 2021-01-31 05:16 UTC
Animated ocean modifier with floating object. Send to render (Cycles). Begins to build the screen, program quits and disappears. 
 Windows 10, GPUs Nvidia 1060 and K621. W3690 6 cores. 
This occurs with GPU render only selected or with combination CPU and CPU.
Denoising is set to Optix.

Using the same file, issue does not occur with version 2.6

**Comment by ReinerBforartists** [comment] 2021-01-31 07:59
Thanks for the report.

Could you please have a look if this also happens with Blender?

**Comment by Blenderblunder** [comment] 2021-01-31 08:23
Hi Reiner, 

No worries, I will give it a go - but I have just started a render that will probably take a day or so. It is installed on my other machine (Windows), so once that is done I can try it.

By the way, was looking to find a way to message you just to thank you for your efforts in making Blender actually useable!

I have used a 3D program called Carrara for many years (now owned by DAZ Studios) and they have basically stopped supporting it, so i need to move on. Carrara is not as fully featured as Blender but it has the most useable, graphic interface of any 3D program I have used - very intuitive, little clutter, logically designed - you move between ‘rooms’ to do particular activities (modelling etc) and the tools you need are all there - not spread all over the place, repeated, hidden, badly designed - all that Blender stuff. 

Anyway, Blender does my head in. The logic of the layout and the tools placement (and the multiple versions of doing the same thing) are impossible. Along with the keyboard commands. (And jumping out of camera view when you move something!! I mean.. what in the hell?) Anyway, I am an artist, not a programmer so memorising keyboard commands is not my thing. So - thank you very much for sorting it out into a version which is very useable. And although, obviously constrained by the original program, you have an produced a viable alternative to Carrara so I am very grateful.  Thank you.

I will try the bug in Blender as soon as I can (if I can figure out how to actually render in the stupid thing) and let you know. 

Cheers
Stephen

**Comment by ReinerBforartists** [comment] 2021-01-31 08:58
You're welcome. And thanks for looking into the problem. Take your time, there is no hurry :)

The culprit here is, we don't develop core features. We change the UI. We merge the Blender master code into our code once a week, And it can happen that something goes wrong then. But it is more likely that this bug comes from the newest Blender version.

**Comment by Blenderblunder** [comment] 2021-02-01 11:13
Hi Reiner,

Just to report back. Tried the file with the latest version of Blender 2.91.2, it worked fine, so it seems to be just in Bforartists.

I do remember a previous version (one or two back) of Blender where I had the same problem and found a forum note saying it had something to do with Embree and older video cards but was fixed in a later version. I updated then and it worked. 

Perhaps the build of the current Bforartists is based on that early Blender build?

At any rate, I hope this of some use. For the time being I can still render in Bforartists 2.6

Best
Stephen

**Comment by ReinerBforartists** [comment] 2021-02-01 11:36
Many thanks for having a look at it and reporting back.

Embree is a lib. And the libs are the same with Blender. So that should not be the cause.

I will dive into the source code again. Maybe i will find the trouble maker. I have unfortunately not this much knowledge in this area. So chances are very low that i can track this one down.

Could you please help me again here, and provide me a little example that crashes in Bforartists and not in Blender? Then i could follow back with a debug build where the problem really is.

And when you start Bforartists from the console, then you might get a crash report in the console when BFA crashes, pointing at the problem. Access violation caused by ... . This is usually not really informative, but could also help us a bit.

**Comment by Blenderblunder** [comment] 2021-02-01 23:42
HI Rainer,

Happy to help and thanks for getting back so quickly.

When you say provide you with an example, would you like me to upload the file to you? Can do - just let me know how (sorry I can’t find the information on the website.)

Also you mention Console which I know from my Mac but I also use a Windows machine to run Blender and 3D things (Cuda etc). I don’t really know my way around Windows 10 (compared to the Mac, it has pretty much the same UI problems that Blender does compared to Bforartist.) Where are the crash reports stored on Windows?

Cheers
Stephen

**Comment by ReinerBforartists** [comment] 2021-02-02 07:28
Hi Blenderblunder. 

Yes, Windows is a special thing to some. For me this special thing is Linux and Mac :)

When it's not above 2 mb then you could zip this example and simply attach it here. If not, phew, we have no upload location for such files, sorry. Maybe google drive could be a place to share bigger files.

The crash file usually gets written to the temp folder. That's at Windows 10  C:\Users\YOURUSERNAME\AppData\Local\Temp . Or simply type %temp% into the run dialog. Or cd %temp% at the console, which will also point you towards the temp folder.

In this temp folder have a look for blender_crash.txt, and upload it here.

Thanks for your efforts :)

**Comment by Blenderblunder** [comment] 2021-02-02 10:10
Hi 

The original file is only about 2.5mb so I can send you that. I had a quick look for the crash file but can’t find anything obviously labelled in that way, so I will need to recreate the crash.

At the moment though, the file is rendering in 2.6 and still has almost a day to go. Once it is done, I will send it all on.

Cheers
Stephen

**Comment by ReinerBforartists** [comment] 2021-02-02 11:15
Many thanks :)

In case Github still moans about the file size, simply send it to reiner.prokein@posteo.de

**Comment by ReinerBforartists** [comment] 2021-02-04 06:53
A thousand thanks for the scene file. I was able to reproduce the problem once so far, right at starting the rendering process the first time. But then it started rendering just fine. Proof see below.

I will keep this under observation, and do a test rendering from time to time. But i remember that Blender is that way from time to time. Sometimes it quits and you will never find the cause.

Kind regards
Reiner

![renderingisworking](https://user-images.githubusercontent.com/13919702/106855922-ffb77f80-66bd-11eb-9560-b1f81050e1af.jpg)

**Comment by ReinerBforartists** [comment] 2021-02-10 17:30
I can't even debug at the moment. Something has changed. So let's close this issue. We are simply not able to resolve it, unfortunately. Sorry.

**Closed by ReinerBforartists** 2021-02-10 17:30 UTC
Labels: 2 - bug, Blender Bug

**Comment by Blenderblunder** [comment] 2021-02-10 21:08
Sure thing. Thanks for the efforts though. 
Cheers 
Stephen
