### ISSUE TITLE
Default Theme - regression with highlighting selected menu item

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3740] opened 2023-09-06 08:57 UTC
Noticed this while working with the nodes menus. Our blue highlight color is gone. 

BFA 3.6.2
![themingregression](https://github.com/Bforartists/Bforartists/assets/13919702/e95ea6db-0b7d-46c3-b5c3-b89c044e30c3)

Now

![topo](https://github.com/Bforartists/Bforartists/assets/13919702/076f2a32-27f7-49e6-9627-5207767ae1ef)

**Comment by ReinerBforartists** [comment] 2023-09-06 09:12
Hm. Unfunny. Something has changed under the hood. Using the userdef_default_theme file from BFA 3.6.2 throws errors.

Let's compare the theming ...

**Comment by ReinerBforartists** [comment] 2023-09-06 09:17
It's getting unfunnier with every moment. They changed the order of the panels here too ^^

![order](https://github.com/Bforartists/Bforartists/assets/13919702/b73e9115-db3f-42d7-a46f-368b0b4901b5)

**Comment by ReinerBforartists** [comment] 2023-09-06 09:26
Ah this undefined color field where you never know what they are good for. What the heck is inner? To fix this i need to change a value that formerly worked completely different.

![menu](https://github.com/Bforartists/Bforartists/assets/13919702/2a21b1e6-874a-46ed-aad6-37a85ad4bcce)

**Comment by ReinerBforartists** [comment] 2023-09-06 09:37
U kidding me?

This userdef_default_theme was written by Bforartists. So why is something missing what is explicitely written by bfa? O_O

![error](https://github.com/Bforartists/Bforartists/assets/13919702/7461ffe1-9db4-4846-82c4-241cbe1f5530)

**Comment by ReinerBforartists** [comment] 2023-09-06 09:53
Blender, killing user configurations since 1784 ...

![defaults](https://github.com/Bforartists/Bforartists/assets/13919702/45c116b0-7715-488b-94ac-80657a901b15)

**Comment by ReinerBforartists** [comment] 2023-09-06 10:03
Woah, finally. Fingers crossed :D

Friends, please take care, any change at the userdef_default_theme.c also means a change at our theming in general. DON'T JUST BLINDLY COPY OVER THE CHANGES FROM BLENDER ! A change at the userdef_default_theme.c file always needs a very close look, and a change at the theming files then. And most probably a fix then too.

I've updated our theming files too. And hope that we haven't overlooked too much here. I haven't followed the changes.

![theming](https://github.com/Bforartists/Bforartists/assets/13919702/dcccb6bb-616e-424f-8c24-7fca8c85d43c)

**Comment by Draise14** [comment] 2023-09-06 12:23
This was related to the enums highlight feature they made this week. So we did have it ok, they broke things internally, so it is not really a regression but a breaking theme change due to internal behaviour of how enums are now pre-highlighted.

**Comment by ReinerBforartists** [comment] 2023-09-06 12:52
It was more than just this issue here. The themes were quite a few changes behind.

**Comment by Draise14** [comment] 2023-09-06 16:59
Another note for the merges.

**Comment by ReinerBforartists** [comment] 2023-09-06 19:00
Indeed. The more you care of this detail at a merge the fewer trouble we have afterwards. Thus my note here :)

**Comment by ReinerBforartists** [comment] 2023-09-07 16:06
The change strikes back. Reopened.

![greyedoutcol](https://github.com/Bforartists/Bforartists/assets/13919702/ffa01d76-c738-41e6-b04b-26a7d99f134e)

**Comment by Draise14** [comment] 2023-09-08 00:30
Yeah, I see it. Where is the report to track?

**Comment by ReinerBforartists** [comment] 2023-09-08 06:13
At its way, Github and real life came in the way ^^

Will do now ...

**Comment by ReinerBforartists** [comment] 2023-09-08 06:59
Here it is 

https://projects.blender.org/blender/blender/issues/112122

**Comment by ReinerBforartists** [comment] 2023-09-12 06:47
I fear we end in a "works as designed" state, since they already start to close reports about the issue. We should find the commit and fix it by ourselves by reverting the problem.

**Comment by Draise14** [comment] 2023-09-18 23:13
A commit to fix has been done, waiting for review.

**Comment by ReinerBforartists** [comment] 2023-09-20 10:21
Yeah, this means we need to fix our theme then too ^^

**Comment by Draise14** [comment] 2023-10-12 21:43
Fixed by Blender, no-longer an issue, hurrah! 

<details>
<summary>Details</summary>

SHA-1: b5ebf31fb114d3d43c11227eca9b1f3ded9f06f1

* Fix #113022: Disabled menu item's text uses inner color

This fails to differentiate between active buttons and disabled buttons
for some custom themes (and also in blender light theme)

Instead use text color with 0.5 alpha value for disabled item's text.
(Don't blend between text and inner color)

Pull Request: https://projects.blender.org/blender/blender/pulls/113082


</details>

**Closed by Draise14** 2023-10-12 21:43 UTC
Labels: 0 - task, 4 - needs work

**Comment by ReinerBforartists** [comment] 2023-10-13 06:19
Uh nice, and we don't even need to change our theme again it seems.
