### ISSUE TITLE
Toolbar Editor - Unnecessary Click to access toolbar types - UX issue

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1501] opened 2020-04-28 14:33 UTC
# Issue
![image](https://user-images.githubusercontent.com/35357409/80498922-ebc23e80-8931-11ea-9444-379e6b6f7711.png)

The first toolbar menu to set the toolbar Editor has a hidden floating submenu that only shows after you click on "Type". Ideally, like in BFA1, you should be able to just mouse over and see the toolbar options. 

Desired funcionality:
![bforartists_2020-04-28_09-30-40](https://user-images.githubusercontent.com/35357409/80499830-119c1300-8933-11ea-855a-bbf65e888e64.png)

It's a little inconsistent and awkward needing to click. I remember Bforartists 1 didn't have this issue. 

Version: Bforartists 2.0.0

# Task
Make the first toolbar category checkbox list show on mouseover like the other toolbar lists.

**Comment by ReinerBforartists** [comment] 2020-04-28 15:43
This is by design. It was not to achieve in another way when i made the toolbar. I was happy to have a menu here at all. I would have loved to display a menu here too. But i did not manage it. 

But let's keep the task open. Maybe i find a better way nowadays.

**Comment by ReinerBforartists** [comment] 2020-11-06 11:58
Bforartists was exactly the same implementation.

Mh, i am not sure if we talk about the same thing here. To save space the menus in the toolbar are collapsed. And then you need to click at the menu name first. 

![expandcollapse](https://user-images.githubusercontent.com/13919702/98363768-cd9b7080-202f-11eb-8b4e-c1182e057cc1.jpg)

**Comment by ReinerBforartists** [comment] 2020-11-07 09:04
Now i remember why i have implemented a C popup menu here instead of a proper menu or panel ...

![missingsrna](https://user-images.githubusercontent.com/13919702/98437191-96d16300-20e0-11eb-889d-2cfbce72309d.png)

**Comment by ReinerBforartists** [comment] 2020-11-12 17:45
Man, i was so fixed at the idea to call the C menu as a whole that i totally overlooked that you can call the single operators of the menu too -.-

We just need to make our own python menu here. I'll make a own panel now for the toolbar types. And am experimenting to implement quick expand collapse buttons in front of every toolbar. Draise here comes your solution from the request of the other closed issue ;)

I will make it optional though. It adds noise to those who doesn't want to expand collapse the toolbars regularly.

I also think to remove the collapsible menus, and just display an arrow button to call a panel with the available menus. Saves one more click.

![experimental](https://user-images.githubusercontent.com/13919702/98976017-1d3dd880-2517-11eb-87ae-ac0ee16bf4c3.jpg)

**Comment by Draise14** [comment] 2020-11-12 18:02
Optional sounds awesome!! The second thinnist (0.7) one feels like a handle, which works for what it would do. And since it's the least invasive when it comes to reptition, it fits nicer. 

How exciting.

**Comment by seanr** [comment] 2020-11-12 18:14
Can that "Toolbars" in the text in each of those in the last screenshot be eliminated/filtered out? It's just totally redundant. And I like the 0.7 option as well.

**Comment by ReinerBforartists** [comment] 2020-11-12 18:38
It's not redundant, it's the expanded menus for the single toolbars. The initial design idea was to setup the toolbars with expanded menus, then hide it away when done. But sure. I plan to make it a dropdown panel with an arrow down button at it.

**Comment by ReinerBforartists** [comment] 2020-11-13 07:52
Houston we have a problem ^^

> Layout.prop() supports bpy.props and ID properties only.

I told you there was a reason why i made it a C menu then. The props in question are bpy.ops.screen. I can show them as buttons, like i did in the toolbar already. But to show them with checkboxes is not supported. I get errors. And these buttons doesn't even hilight when they are on -.-

Searching for workarounds ...

![toolbartypes](https://user-images.githubusercontent.com/13919702/99042747-937d2200-258d-11eb-9120-c102cca0ea96.jpg)

**Comment by ReinerBforartists** [comment] 2020-11-13 08:51
Found a workaround. On it goes ...

![workaround](https://user-images.githubusercontent.com/13919702/99048378-c4f9eb80-2595-11eb-9e08-3b59506c8694.jpg)

**Comment by ReinerBforartists** [comment] 2020-11-13 10:13
Menus turns into panels to have the triangle button at the top. It's a bit wider than a regular menu though. Benefit: colored checkboxes. In the text menu they are grey.

![menustopanel](https://user-images.githubusercontent.com/13919702/99060994-2a9fa500-25a1-11eb-85d7-6330e2fe838f.jpg)

![old](https://user-images.githubusercontent.com/13919702/99061002-2d9a9580-25a1-11eb-9dd9-01a19298dea1.jpg)

**Comment by ReinerBforartists** [comment] 2020-11-13 16:45
Fixed in master

![fixed](https://user-images.githubusercontent.com/13919702/99097462-f5627980-25d7-11eb-8756-2c9ee2e1456f.jpg)

**Closed by ReinerBforartists** 2020-11-13 16:45 UTC
Labels: 0 - task

**Comment by Draise14** [comment] 2020-11-13 17:11
You are a legend. I have shared this to the socials! I knew a few users who will be happy with this, including myself. Thanks for listening, and really putting in the effort to do this. You really make my day/s.

**Comment by ReinerBforartists** [comment] 2020-11-13 17:20
It was me a pleasure :)
