### ISSUE TITLE
Compilation warnings

### ISSUE THREAD

**Issue by iyadahmed** [Bforartists/Bforartists#2281] opened 2021-03-09 05:19 UTC
```
C:\dev\bforartists-git\Bforartists\source\blender\editors\space_view3d\view3d_iterators.c(462): warning C4047: 'function': 'float *' differs in levels of indirection from 'float (*)[2]'
C:\dev\bforartists-git\Bforartists\source\blender\editors\space_view3d\view3d_iterators.c(462): warning C4024: 'ED_view3d_project_float_object': different types for formal and actual parameter 3
C:\dev\bforartists-git\Bforartists\source\blender\editors\space_view3d\view3d_iterators.c(531): warning C4090: 'function': different 'const' qualifiers
C:\dev\bforartists-git\Bforartists\source\blender\editors\mask\mask_select.c(266): warning C4113: 'unsigned char *(__cdecl *)(bContext *,wmOperatorType *,PointerRNA *,int)' differs in parameter lists from 'unsigned char *(__cdecl *)(bContext *,wmOperatorType *,PointerRNA *)'
```

**Comment by ReinerBforartists** [comment] 2021-03-09 07:09
Hm, seems that my port of the tooltip to the C code strikes back here. Makes me think if it is really a good idea to port the single tooltips to C.

**Comment by ReinerBforartists** [comment] 2021-03-09 07:09
Related Separated tooltips - Implement the different tooltips in the original operator #2052

**Comment by ReinerBforartists** [comment] 2021-03-09 07:26
The problem is, i don't even see this warnings with VS. Now go fix them :/

**Comment by iyadahmed** [comment] 2021-03-09 08:07
> Hm, seems that my port of the tooltip to the C code strikes back here. Makes me think if it is really a good idea to port the single tooltips to C.

It seems like a good idea if it does what it is meant to do,
the warnings can be fixed easily I think it seems there are only two issues.

**Comment by iyadahmed** [comment] 2021-03-09 09:43
Hmmm, not sure, afaik C doesn't have straightforward function overloading,
We could just define two different functions

**Comment by iyadahmed** [comment] 2021-03-09 09:59
I think we just leave it as long as it is working, until a better way is found, warnings can be fixed later

**Comment by ReinerBforartists** [comment] 2021-03-09 10:01
Hmm. The problem is, the more i fix the tooltips, the more warnings i will add :)

**Comment by iyadahmed** [comment] 2021-03-09 10:45
Ah I see, I meant when we find a way to fix warnings without breaking the new feature, removing the last argument should fix some warnings,
But it is being used, so that would cause problems

**Comment by iyadahmed** [comment] 2021-03-09 11:06
one warning fixed, 3 to go, but isn't the int action used?
![image](https://user-images.githubusercontent.com/25552173/110461482-28c19a80-80d8-11eb-8b14-9a60921757d9.png)

**Comment by ReinerBforartists** [comment] 2021-03-09 11:20
The problem resided as usual in front of the pc. I could swear that i needed to include the variable into the overload. But now it works without.

Varialbe removed, no crash, function is still given. Problem fixed it seems :)

**Comment by ReinerBforartists** [comment] 2021-03-09 11:21
Ah, damn, more warnings XD

Thanks for confiriming that at least one error is gone :)

**Comment by iyadahmed** [comment] 2021-03-09 11:23
> Ah, damn, more warnings XD

XD yep at least there's progress,

**Comment by ReinerBforartists** [comment] 2021-03-09 11:34
The second warning is the select through patch. I fear i am lost here. But let's investigate a bit more. Never give up too fast.

**Comment by ReinerBforartists** [comment] 2021-03-09 12:01
I have not the slightest idea what the problem even is :/

**Comment by iyadahmed** [comment] 2021-03-09 12:06
oh :/

**Comment by iyadahmed** [comment] 2021-03-09 12:08
Aha, I see now, it should be `temp_screen_co` instead of `&temp_screen_co`, it is already an array, which is a pointer, so no need to get pointer to it

**Comment by ReinerBforartists** [comment] 2021-03-09 13:14
Thanks  @iyadahmed .Will test it :)

**Comment by iyadahmed** [comment] 2021-03-09 13:26
Great!

**Comment by iyadahmed** [comment] 2021-03-09 13:31
![image](https://user-images.githubusercontent.com/25552173/110478030-8c55c300-80ec-11eb-8980-c9ce09024cf9.png)

**Comment by iyadahmed** [comment] 2021-03-09 18:17
There was a comment here hmm, I didn't have the chance to read

**Comment by ReinerBforartists** [comment] 2021-03-09 20:02
Not from me. And i did not get a mail. I have just assigned you here too since i am stuck. And you fixed half of it anyways already :)

**Comment by iyadahmed** [comment] 2021-03-10 04:00
Ah ok

**Comment by ReinerBforartists** [comment] 2021-03-20 08:27
I am really close to uninstall this patch again. But in the end it's just warnings. The function is given.

![selectthroughwarnings](https://user-images.githubusercontent.com/13919702/111863898-6aff9d00-895e-11eb-8d13-9b3150097b53.jpg)

**Comment by iyadahmed** [comment] 2021-03-20 15:45
> I am really close to uninstall this patch again. But in the end it's just warnings. The function is given.
> 
> 
> 
> ![selectthroughwarnings](https://user-images.githubusercontent.com/13919702/111863898-6aff9d00-895e-11eb-8d13-9b3150097b53.jpg)
> 
> 
> 
> 
> 
> 

Oh , if it is just warnings I think no need to remove the patch

**Comment by iyadahmed** [comment] 2021-03-20 15:46
> I am really close to uninstall this patch again. But in the end it's just warnings. The function is given.
> 
> 
> 
> ![selectthroughwarnings](https://user-images.githubusercontent.com/13919702/111863898-6aff9d00-895e-11eb-8d13-9b3150097b53.jpg)
> 
> 
> 
> 
> 
> 

Oh what are all these warnings 😵

**Comment by ReinerBforartists** [comment] 2021-03-20 16:42
Fun! Pure fun ! :D

**Comment by ReinerBforartists** [comment] 2021-03-20 16:44
Just the four last ones comes while compiling. The rest above appears when i open the view3d_select.c file ...

**Comment by iyadahmed** [comment] 2021-03-20 17:43
> Just the four last ones comes while compiling. The rest above appears when i open the view3d_select.c file ...

Oh right so they are static analysis warnings

**Comment by ReinerBforartists** [comment] 2021-03-20 20:07
Yes. That's VS code analysis. Not sure if you can even show them under Linux :)

I have no idea how to fix the problem in the view3d_iterators.c file. The other three ones are unreferenced variables. Also nothing harmful. When you find a solution for it, everything is welcome. But if not i would say we simply move on. The select through patch was no finished patch. But in development, and then abandoned. So it misses the polishing. But the warnings doesn't harm. The important part is that select through works.

**Comment by iyadahmed** [comment] 2021-03-20 23:29
> Yes. That's VS code analysis. Not sure if you can even show them under Linux :)
> 
> 
> 
> I have no idea how to fix the problem in the view3d_iterators.c file. The other three ones are unreferenced variables. Also nothing harmful. When you find a solution for it, everything is welcome. But if not i would say we simply move on. The select through patch was no finished patch. But in development, and then abandoned. So it misses the polishing. But the warnings doesn't harm. The important part is that select through works.

Awesome, indeed we move on until a solution is found

**Comment by ReinerBforartists** [comment] 2021-03-31 16:16
Functionality is still given it seems. Fingers crossed. Remains the different const qualifier warning. I have no idea what is meant here ...

**Comment by iyadahmed** [comment] 2021-03-31 16:21
Hmm I don't think that commit was necessary, It could be fixed while keeping them uncommented I believe

**Comment by ReinerBforartists** [comment] 2021-04-12 09:33
Compilation warnings are gone after removing the select through patch. Closing.

**Closed by ReinerBforartists** 2021-04-12 09:33 UTC
Labels: 0 - task
