### ISSUE TITLE
3D View - Armature Edit Mode - Clear and Make parent doesn't show assigned hotkeys

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1454] opened 2020-04-13 15:03 UTC
# Issue
![bforartists_2020-04-11_12-24-04](https://user-images.githubusercontent.com/35357409/79130915-58074480-7d6d-11ea-9b71-a9e5494f3bbe.png)
Right now, the Make Parent and Clear Parent don't show hotkeys when assigned. The Change Bone Layers and Change Armature layers also. This is in Edit mode of an armature. 

# Task
Check and see how shortcuts are shown to enumerated operators, and show them when assigned. 

**Version: Bforartists 2 - 1.0.0 RC**

**Comment by ReinerBforartists** [comment] 2020-04-13 15:46
This is most probably caused by the same bug than in this reports here: 
Pose Mode - Flip quats menu item doesn't show hotkey #867
Object menu - Delete operator - wrong label, no hotkey #597

It is reported to Blender, and happily forgotten. It wears the almighty known issue label ...
https://developer.blender.org/T60887

**Comment by Draise14** [comment] 2020-04-13 16:46
Ah.. shame. Oh well.

**Comment by ReinerBforartists** [comment] 2020-04-17 10:32
Just a short check ...

**Comment by ReinerBforartists** [comment] 2020-04-17 10:34
Hmmmm .....

**Comment by ReinerBforartists** [comment] 2020-04-17 10:37
We don't have these hotkeys, so no wonder they don't show :D

**Comment by ReinerBforartists** [comment] 2020-04-17 10:46
Now it's getting interesting. Adding them does not help. Same keymap code. Same UI code.

No idea. Postponing ...

**Comment by ReinerBforartists** [comment] 2020-12-12 11:57
Fixed in master

**Comment by ReinerBforartists** [comment] 2020-12-12 12:03
Ah, change armature layers is also affected.

**Comment by ReinerBforartists** [comment] 2020-12-12 12:09
And fixed.

**Closed by ReinerBforartists** 2020-12-12 12:09 UTC
Labels: 2 - bug, 5 - Postponed, Blender Bug
