### ISSUE TITLE
Properties Editors - Collections Tab - Exporters Panel - Double Presets system

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4220] opened 2024-04-23 01:46 UTC
![bforartists_o6QCk6bnMk](https://github.com/Bforartists/Bforartists/assets/35357409/fa3d0315-8e04-4831-a23c-0533854d0156)
![bforartists_ED1nDTb0cj](https://github.com/Bforartists/Bforartists/assets/35357409/de0e824a-fd59-43fb-b14c-b1ae79455530)

For some reason we have two of the same thing.... And one operator is not showing in the other. 

Remove and consolidate that one operator (Set Operator Defaults) and remove the other.

**Comment by ReinerBforartists** [comment] 2024-04-30 09:33
May i repeat my request to make bigger screenshots that shows the whole? I cannot reproduce, and am once more lost to find what you are pointing at.

I've checked all exporters now, and no double entry is to find. What i have found though is some missing icons. Making it a task.

![nottoreproduce](https://github.com/Bforartists/Bforartists/assets/13919702/9bdfd774-8cb9-4565-8439-dc00840f0278)

![missingicons](https://github.com/Bforartists/Bforartists/assets/13919702/8236b178-8364-4f33-be15-26d02651e631)

**Comment by Draise14** [comment] 2024-05-02 17:16
Ah, will update, these presets are inside the exporter, not in the panel.

**Comment by ReinerBforartists** [comment] 2024-10-07 07:59
Not longer an issue it seems. None of the exporters shows an operator preset prop anymore. Closing.

**Closed by ReinerBforartists** 2024-10-07 07:59 UTC
Labels: 0 - task
