### ISSUE TITLE
FBX export bug

### ISSUE THREAD

**Issue by emilsvfx** [Bforartists/Bforartists#63] opened 2018-03-12 06:42 UTC
giving me fbx export error 
https://i.imgur.com/Ax3SCeo.png

[](https://i.imgur.com/Ax3SCeo.png)

**Comment by ReinerBforartists** [comment] 2018-03-12 07:28
Thanks for the report. We will look into this.

**Comment by ReinerBforartists** [comment] 2018-03-12 07:52
Hi emilsvfx,

I cannot reproduce the error here. I smell a bug at the script, which would be a job for Blender developers then. Or maybe the geometry is shot down.

Do you have an example scene for me? And could you tell me with what settings you export?

**Comment by emilsvfx** [comment] 2018-03-12 08:30
i just add some vertex color to the model.

FBX Settings defult
https://i.imgur.com/YttnGQA.png
scene file https://failiem.lv/u/a93m8uz2

**Comment by ReinerBforartists** [comment] 2018-03-12 09:07
Thanks. I will have a look at it.

**Comment by ReinerBforartists** [comment] 2018-03-12 09:09
Okay, confirmed. Blender works, Bforartists fails. I will dive into the fbx export script now ...

**Comment by ReinerBforartists** [comment] 2018-03-12 09:28
Fixed in master

https://github.com/Bforartists/Bforartists/commit/5daf9e3f04e069aa51e6b5562ac7d23590ebbc98

The cause was an outdated FBX plugin version. We have 3.8.4, Blender already has 3.9.0.

Emil, it can take a while until the fixed version is available. Next devbuild comes next sunday. In case you want to fix it immediately, i have attached the updated fbx addon here . Replace the one in \2.79\scripts\addons in your installation folder by the one here attached.

[io_scene_fbx.zip](https://github.com/Bforartists/Bforartists/files/1802145/io_scene_fbx.zip)

**Closed by ReinerBforartists** 2018-03-12 09:28 UTC
Labels: bug

**Comment by Draise14** [comment] 2018-03-15 01:48
Thanks for the fix, I really needed this for work.

**Comment by ReinerBforartists** [comment] 2018-03-15 08:02
Shall we update the installer for that? I don't want to make a new version for it really, but it's a showstopper ...
