### ISSUE TITLE
Geometry nodes sidebar - Group Tab - Interface panel - Move up, move down is missing

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3889] opened 2023-10-14 16:03 UTC
The new icons are super confusing. But this is not why i make this task, sorry.

The move item up and move down buttons are now missing.

Possibly related issue: https://github.com/Bforartists/Bforartists/issues/3733

**Comment by Draise14** [comment] 2023-10-14 16:06
The up and down is removed from the API for the new drag and drop system. They built a new recent API to do the re-ordering, but it's not exposed to button anymore. I'm trying to confirm the API to do this. 

I may suggest making an "add" label and a column visual representation of what the add group does. 
![bforartists_tYi5wnz6wU](https://github.com/Bforartists/Bforartists/assets/35357409/9fbb846e-7c2e-48c1-9e26-0b2aa4d07c1b)

And if the API allows it, the re-order buttons should definately be added back if the API allows for it (two weeks ago it was impossible)

**Comment by ReinerBforartists** [comment] 2023-10-14 16:10
Yeah, i found out, i was then too slow with editing the issue, sorry for the confusion ^^

The up and down buttons are now missing, which is this issue now.

![interface](https://github.com/Bforartists/Bforartists/assets/13919702/50da036d-eff1-431d-a165-70e0b002420b)


![move](https://github.com/Bforartists/Bforartists/assets/13919702/d7c2d38d-031c-4dc3-9aac-f71babd5b754)

**Comment by ReinerBforartists** [comment] 2023-10-14 16:10
Ah, you also pointed at it already :D

**Comment by ReinerBforartists** [comment] 2023-10-14 16:12
Mh, it becomes a bit crowded when putting this one asides. Above would have more space. But looses the connection to the remove button then. A dropdown menu might be better suited. But is also one more click ...

This one definitely needs a bit more thinking.

**Comment by Draise14** [comment] 2023-10-14 16:14
The remove could be in the same row above in the same "add" box. I used a box to group them together. I really don't want to dig to add things, specially with the toolbar workflow for adding geo/objects that we have. 

But yeah, if we get the API for up/down buttons to work, then that will be super important for the future since all lists will get drag and drop, but Blender seems to not show interest to add those buttons back - in GP 3, in the bone collections, light linking collections, and more.

**Comment by ReinerBforartists** [comment] 2023-10-14 16:17
Ah  now i see, this is removed by design since it is now drag and drop. We could make a sub menu for it. Or we do as blender and remove it. But then the user has no choice to discover that the list can be sorted at all.

**Comment by Draise14** [comment] 2023-10-14 16:21
Exactly, drag and drop is not discoverable, the buttons could allow for the tooltip to hint and allow users to use a button to move up or down intentionally too. 

I've seen users talk about missing this already in Erindales discord server, the place for node gurus.

**Comment by ReinerBforartists** [comment] 2023-10-14 16:22
Then i vote for a sub menu. This is just one button place then. 

What bothers me a bit, and this is why i made initially the task is that the tooltips all shows the same name. I thought it is doubles in the first moment. But i'll make it an extra task.

![split](https://github.com/Bforartists/Bforartists/assets/13919702/4bbebf02-d533-4ea1-8778-33addd59fde5)

**Comment by Draise14** [comment] 2023-10-14 16:25
I'm against the sub menu to add things to this list, no-where do we have add sub menus for lists.... it's inconsistent and inconvenient.

**Comment by ReinerBforartists** [comment] 2023-10-14 16:28
Okay, then let's do like Blender and close the issue?

**Comment by Draise14** [comment] 2023-10-14 16:31
Ah, back to topic.

**Up/Done arrows:** I vote to find a way and expose the buttons like before. 

**Reason:**
- Discoverability
- Ability to add a tooltip to show that dragging is possible
- Not rock the boat with traditional list organization for former users

Keep this task open.

**Comment by ReinerBforartists** [comment] 2023-10-14 16:41
Just to don't forget about it, Blender has it in sub menus. But yeah, has the disadvantage that you can just add one at a time.

![blender](https://github.com/Bforartists/Bforartists/assets/13919702/ff52b4a3-95ce-4e18-a49e-a44797b6cb84)

**Comment by ReinerBforartists** [comment] 2023-10-14 16:42
Ah cool, just wanted to test that my assumption is true, Blender is bugged here.

Bug report tomorrow ...

![blenderisbugged](https://github.com/Bforartists/Bforartists/assets/13919702/334eba20-b034-45c1-9104-fc53811cf28c)

**Comment by Draise14** [comment] 2023-10-14 16:44
Already fixed in this week coming merge. https://github.com/Bforartists/Bforartists/commit/a80bc41df9f293c56f2b0fc141c305dc632044c3

**Comment by ReinerBforartists** [comment] 2023-10-14 16:53
Good to know, saves me the report, thanks :)

**Comment by Draise14** [comment] 2023-11-07 17:01
Yeah, they are consistently removing them for the new UI List tree views that will be implemented in all editors. 

We need the API to move things up or down, to also add a tooltip to show that you can drag and drop too, or use pens with the lists easily.

**Comment by ReinerBforartists** [comment] 2023-11-07 17:26
I would postpone this one for after 4.0 release.

**Comment by Draise14** [comment] 2023-11-07 17:32
Postponed for 4.1

**Comment by Draise14** [comment] 2023-12-15 02:34
There is some API to define the index up or down. And you could make an addon or internal operator that stores the GUI active index, though the API doesn't exist for it. It's a theory, but will require some tests, and a full on addon I think. But for those who use pen tablet, and for the tooltip, I think this is important.

**Comment by Draise14** [comment] 2024-01-15 14:47
A friend (and winner of a splashscreen) quackers managed to crack the code. He's trying to submit it to upstream, but it may be denied "by design". 

So.. we have working code for it here: 
https://projects.blender.org/blender/blender/pulls/117130#issuecomment-1102220

**Comment by Draise14** [comment] 2024-01-15 15:54
![image](https://github.com/Bforartists/Bforartists/assets/35357409/10867219-b13b-4571-a6c0-c444b7e0712a)

![image](https://github.com/Bforartists/Bforartists/assets/35357409/73733a79-8142-46fa-82ca-27e7c2b37bf2)

Good enough for now. The default box is small and you can't drag and drop to resize like the traditional UI Lists, but that can be figured out later I guess.

**Comment by Draise14** [comment] 2024-01-15 15:55
Documenting.

**Closed** 2024-01-15 16:05 UTC
Labels: 0 - task, 1- Fixed
