### ISSUE TITLE
Crash with clicking at the shading tab

### ISSUE THREAD

**Issue by Jackle4Foxy** [Bforartists/Bforartists#3454] opened 2023-03-20 15:24 UTC
**The bug**
With Bforartists v 3.4.1 both when attempting to open the shading tab 
& when attempting to create a shader in the materials tab Bforartists crashes/closes.
Happens with any object.

**Laptop:**
The Operating system. Windows 10, 
22H2 Feature Experience Pack 120.2212.4190.0
Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
16,0 GB RAM, Intel HD Graphics 520 - 8Gig

Shader v 5.1, OpenGL 4.5, OpenCL 2.1, DirectX 12, Vulkan 1.1.82

![B4A](https://user-images.githubusercontent.com/75924956/226387138-6fb87cc7-ce6d-4d36-b15d-825788bc30e6.jpg)

**Comment by Jackle4Foxy** [comment] 2023-03-21 11:00
# Blender 3.5.0, Commit date: 2023-01-10 03:04, Hash f3ec965414a5

# backtrace
Exception Record:

ExceptionCode         : EXCEPTION_ACCESS_VIOLATION
Exception Address     : 0x00007FF6A118EE60
Exception Module      : bforartists.exe
Exception Flags       : 0x00000000
Exception Parameters  : 0x2
	Parameters[0] : 0x0000000000000000
	Parameters[1] : 0x0000000000000008


Stack trace:
bforartists.exe     :0x00007FF6A0DF0F40  PyInit_manta_main
bforartists.exe     :0x00007FF69BD4D227  Symbols not available


Loaded Modules :
0x00007FF69B5E0000 3.4.1.0              bforartists.exe  
0x00007FFFA2ED0000 10.0.19041.2130      ntdll.dll  
0x00007FFFA2410000 10.0.19041.2546      KERNEL32.DLL  
0x00007FFFA08C0000 10.0.19041.2728      KERNELBASE.dll  
0x00007FFFA2630000 10.0.19041.2486      USER32.dll  
0x00007FFFA0DF0000 10.0.19041.2728      win32u.dll  
0x00007FFFA27E0000 10.0.19041.2130      GDI32.dll  
0x00007FFFA0600000 10.0.19041.2604      gdi32full.dll  
0x00007FFFA0BA0000 10.0.19041.789       msvcp_win.dll  
0x00007FFFA0CF0000 10.0.19041.789       ucrtbase.dll  
0x00007FFFA1200000 10.0.19041.2546      SHELL32.dll  
0x00007FFFA0710000 10.0.19041.1620      CFGMGR32.dll  
0x00007FFFA2170000 10.0.19041.546       WS2_32.dll  
0x00007FFFA2D60000 10.0.19041.2728      RPCRT4.dll  
0x00007FFFA2330000 10.0.19041.2130      ADVAPI32.dll  
0x00007FFFA1B20000 7.0.19041.546        msvcrt.dll  
0x00007FFFA0FB0000 10.0.19041.1865      sechost.dll  
0x00007FFFA1FE0000 10.0.19041.1202      ole32.dll  
0x00007FFFA1C70000 10.0.19041.2311      combase.dll  
0x00007FFFA2110000 10.0.19041.2075      SHLWAPI.dll  
0x00007FFFA1BC0000 10.0.19041.1865      shcore.dll  
0x00007FFFA23E0000 10.0.19041.2673      IMM32.dll  
0x00007FFF98610000                      tbbmalloc.dll  
0x00007FFF89450000                      tbb.dll  
0x00007FFF2A9E0000                      cycles_kernel_oneapi_jit.dll  
0x00007FFF4AFC0000                      OpenColorIO_2_2.dll  
0x00007FFF47510000                      OpenImageIO.dll  
0x00007FFF52770000                      OpenImageIO_Util.dll  
0x00007FFF48F00000 6.1.0.0              sycl6.dll  
0x00007FFF89250000                      boost_python310-vc142-mt-x64-1_80.dll  
0x00007FFF6B670000                      Iex.dll  
0x00007FFF525C0000                      epoxy-0.dll  
0x00007FFF29230000 10.0.0.0             openvdb.dll  
0x00007FFF6B370000                      Imath.dll  
0x00007FFF48C30000                      OpenEXR.dll  
0x00007FFF26D40000 59.37.100.0          avcodec-59.dll  
0x00007FFF6B600000 59.7.100.0           avdevice-59.dll  
0x00007FFF471B0000 59.27.100.0          avformat-59.dll  
0x00007FFFA2810000 10.0.19041.985       OLEAUT32.dll  
0x00007FFF467A0000 57.28.100.0          avutil-57.dll  
0x00007FFFA05D0000 10.0.19041.2486      bcrypt.dll  
0x0000000067380000 1.1.0.0              libsndfile-1.dll  
0x00007FFF56720000 6.7.100.0            swscale-6.dll  
0x00007FFF4B430000 1.21.1.0             OpenAL32.dll  
0x000000006ACC0000                      libgmp-10.dll  
0x00007FFF9C060000                      libgmpxx.dll  
0x00007FFF48AD0000 2.0.20.0             SDL2.dll  
0x00007FFFA28E0000 10.0.19041.2193      SETUPAPI.dll  
0x00007FFF99940000                      boost_thread-vc142-mt-x64-1_80.dll  
0x00007FFF55DE0000                      boost_locale-vc142-mt-x64-1_80.dll  
0x00007FFF53FE0000 14.29.30139.0        MSVCP140.dll  
0x00007FFF99850000 14.29.30139.0        VCRUNTIME140.dll  
0x00007FFF9B290000 14.29.30139.0        VCRUNTIME140_1.dll  
0x00007FFF5B9A0000 10.0.19041.1         AVIFIL32.dll  
0x00007FFF88F90000 6.10.19041.1110      COMCTL32.dll  
0x00007FFF97BD0000 10.0.19041.546       VERSION.dll  
0x00007FFF905C0000 10.0.19041.867       dbghelp.dll  
0x00007FFF9E1A0000 10.0.19041.746       dwmapi.dll  
0x00007FFF44830000 3.10.9150.1013       python310.dll  
0x00007FFF99CC0000                      tbbmalloc_proxy.dll  
0x00007FFF99BB0000 14.29.30139.0        MSVCP140_CODECVT_IDS.dll  
0x00007FFF441A0000 10.0.19041.1503      dbgeng.dll  
0x0000000070680000                      libfftw3-3.dll  
0x00007FFF253F0000                      usd_ms.dll  
0x00007FFF81A10000 10.0.19041.546       Secur32.dll  
0x00007FFF98980000 10.0.19041.1         AVICAP32.dll  
0x00007FFF8CE20000 10.0.19041.546       WINMM.dll  
0x00007FFF566F0000 10.0.19041.1         MSVFW32.dll  
0x00007FFF9B8E0000 10.0.19041.1         MSACM32.dll  
0x00007FFF52530000                      OpenEXRCore.dll  
0x00007FFF9C0E0000 10.0.19041.546       XmlLite.dll  
0x00007FFF4ADE0000 10.0.19041.1503      dbgmodel.dll  
0x00007FFF882F0000 10.0.19041.2193      OPENGL32.dll  
0x00007FFF7E530000 10.0.19041.1         winmmbase.dll  
0x00007FFF882C0000 10.0.19041.2193      GLU32.dll  
0x00007FFFA0490000 10.0.19041.2130      SSPICLI.DLL  
0x00007FFF99B60000                      IlmThread.dll  
0x00007FFF552B0000 4.7.100.0            swresample-4.dll  
0x00007FFF9E490000 10.0.19041.546       kernel.appcore.dll  
0x00007FFF9E690000 10.0.19041.2673      windows.storage.dll  
0x00007FFF9FF50000 10.0.19041.2673      Wldp.dll  
0x00007FFF9DFC0000 10.0.19041.2193      uxtheme.dll  
0x00007FFFA0E90000 10.0.19041.2486      bcryptPrimitives.dll  
0x00007FFFA0510000 10.0.19041.844       profapi.dll  
0x00007FFFA1A70000 2001.12.10941.16384  clbcatq.dll  
0x00007FFF93750000 10.0.19041.1503      MMDevApi.dll  
0x00007FFFA02A0000 10.0.19041.1620      DEVOBJ.dll  
0x00007FFF92F70000 10.0.19041.2364      AUDIOSES.DLL  
0x00007FFFA0440000 10.0.19041.546       powrprof.dll  
0x00007FFFA0420000                      UMPDC.dll  
0x00007FFFA1950000 10.0.19041.2673      MSCTF.dll  
0x00007FFF992B0000 10.0.19041.2673      AppXDeploymentClient.dll  
0x00007FFF24500000 24.20.100.6286       ig9icd64.dll  
0x00007FFF9EE90000 10.0.19041.2311      dxgi.dll  
0x00007FFF97BE0000 10.0.19041.546       dxcore.dll  
0x00007FFF938D0000 24.20.100.6286       igc64.dll  
0x00007FFF81170000 10.0.19041.1387      dataexchange.dll  
0x00007FFF9CAE0000 10.0.19041.2075      d3d11.dll  
0x00007FFF9D330000 10.0.19041.2546      dcomp.dll  
0x00007FFF9AA10000 10.0.19041.1865      twinapi.appcore.dll  
0x00007FFF8A7C0000 10.0.19041.2546      textinputframework.dll  
0x00007FFF9D8A0000 10.0.19041.546       CoreUIComponents.dll  
0x00007FFF9F710000 10.0.19041.546       ntmarta.dll  
0x00007FFF9DC00000 10.0.19041.2193      CoreMessaging.dll  
0x00007FFF9C3D0000 10.0.19041.2311      wintypes.dll  
0x00007FFF80F50000 10.0.19041.1949      explorerframe.dll  
0x00007FFF82E90000 10.0.19041.1566      directmanipulation.dll  
0x00007FFF9FEB0000 10.0.19041.546       CRYPTSP.dll  
0x00007FFF9F5D0000 10.0.19041.1052      rsaenh.dll  
0x00007FFF9FEA0000 10.0.19041.546       CRYPTBASE.dll  
0x000001420ABF0000 3.10.9150.1013       python3.DLL  
0x00007FFF895D0000 3.10.9150.1013       _bz2.pyd  
0x00007FFF54BA0000 3.10.9150.1013       _lzma.pyd  
0x00007FFF86FF0000 3.10.9150.1013       _socket.pyd  
0x00007FFF9F9A0000 10.0.19041.1865      IPHLPAPI.DLL  
0x00007FFF99480000 3.10.9150.1013       select.pyd  
0x00007FFF54B70000 3.10.9150.1013       _ssl.pyd  
0x00007FFFA0760000 10.0.19041.2486      CRYPT32.dll  
0x00007FFF4A610000 1.1.1.17             libssl-1_1.dll  
0x00007FFF458A0000 1.1.1.17             libcrypto-1_1.dll  
0x00007FFF9FCB0000 10.0.19041.546       mswsock.dll  
0x00007FFF98A10000 3.10.9150.1013       _hashlib.pyd  
0x00007FFF980D0000 3.10.9150.1013       _queue.pyd  
0x00007FFF453A0000 3.10.9150.1013       unicodedata.pyd  
0x00007FFF89440000 3.10.9150.1013       _uuid.pyd  
0x00007FFF7F520000 3.10.9150.1013       _asyncio.pyd  
0x00007FFF87BE0000 3.10.9150.1013       _overlapped.pyd  
0x00007FFF547C0000 3.10.9150.1013       _ctypes.pyd  
0x00007FFF878F0000                      libffi-7.dll  
0x00007FFF87540000                      _multidict.cp310-win_amd64.pyd  
0x00007FFF79F80000                      _quoting_c.cp310-win_amd64.pyd  
0x00007FFF85C90000                      _helpers.cp310-win_amd64.pyd  
0x00007FFF6DB20000                      _http_writer.cp310-win_amd64.pyd  
0x00007FFF54780000                      _http_parser.cp310-win_amd64.pyd  
0x00007FFF6DC50000                      _websocket.cp310-win_amd64.pyd  
0x00007FFF6BD40000                      _frozenlist.cp310-win_amd64.pyd  

# Python backtrace

**Comment by ReinerBforartists** [comment] 2023-03-21 11:23
Many thanks :)

Hmmmm. the macro, i am not sure if it is from us. What extensions do you use? Could you please reset Bforartists to the factory defaults and try again?
![factorysettings](https://user-images.githubusercontent.com/13919702/226592127-de717991-96df-4d4c-ac99-edbbd5e44d49.jpg)

**Comment by Jackle4Foxy** [comment] 2023-03-21 11:46
Factory settings:

-----

# Blender 3.5.0, Commit date: 2023-01-10 03:04, Hash f3ec965414a5

# backtrace
Exception Record:

ExceptionCode         : EXCEPTION_ACCESS_VIOLATION
Exception Address     : 0x00007FF6A118EE60
Exception Module      : bforartists.exe
Exception Flags       : 0x00000000
Exception Parameters  : 0x2
	Parameters[0] : 0x0000000000000000
	Parameters[1] : 0x0000000000000008


Stack trace:
bforartists.exe     :0x00007FF6A0DF0F40  PyInit_manta_main
bforartists.exe     :0x00007FF69BD4D227  Symbols not available


Loaded Modules :
0x00007FF69B5E0000 3.4.1.0              bforartists.exe  
0x00007FFFA2ED0000 10.0.19041.2130      ntdll.dll  
0x00007FFFA2410000 10.0.19041.2546      KERNEL32.DLL  
0x00007FFFA08C0000 10.0.19041.2728      KERNELBASE.dll  
0x00007FFFA2630000 10.0.19041.2486      USER32.dll  
0x00007FFFA0DF0000 10.0.19041.2728      win32u.dll  
0x00007FFF99AA0000                      tbb.dll  
0x00007FFFA27E0000 10.0.19041.2130      GDI32.dll  
0x00007FFFA0600000 10.0.19041.2604      gdi32full.dll  
0x00007FFF2AED0000                      usd_ms.dll  
0x00007FFFA0BA0000 10.0.19041.789       msvcp_win.dll  
0x00007FFF99A60000                      tbbmalloc.dll  
0x00007FFFA0CF0000 10.0.19041.789       ucrtbase.dll  
0x00007FFFA1200000 10.0.19041.2546      SHELL32.dll  
0x00007FFFA2170000 10.0.19041.546       WS2_32.dll  
0x00007FFFA0710000 10.0.19041.1620      CFGMGR32.dll  
0x00007FFFA2D60000 10.0.19041.2728      RPCRT4.dll  
0x00007FFFA2110000 10.0.19041.2075      SHLWAPI.dll  
0x00007FFFA2330000 10.0.19041.2130      ADVAPI32.dll  
0x00007FFFA1B20000 7.0.19041.546        msvcrt.dll  
0x00007FFFA0FB0000 10.0.19041.1865      sechost.dll  
0x00007FFFA1FE0000 10.0.19041.1202      ole32.dll  
0x00007FFFA1C70000 10.0.19041.2311      combase.dll  
0x00007FFFA1BC0000 10.0.19041.1865      shcore.dll  
0x00007FFFA23E0000 10.0.19041.2673      IMM32.dll  
0x00007FFF29090000                      cycles_kernel_oneapi_jit.dll  
0x00007FFF535E0000                      OpenColorIO_2_2.dll  
0x00007FFF47510000                      OpenImageIO.dll  
0x00007FFF56150000                      OpenImageIO_Util.dll  
0x00007FFF99480000                      boost_python310-vc142-mt-x64-1_80.dll  
0x00007FFF55FA0000                      epoxy-0.dll  
0x00007FFF98A10000                      Iex.dll  
0x00007FFF278E0000 10.0.0.0             openvdb.dll  
0x00007FFF525A0000                      OpenEXR.dll  
0x00007FFF85D30000                      Imath.dll  
0x00007FFF4B000000 6.1.0.0              sycl6.dll  
0x00007FFF253F0000 59.37.100.0          avcodec-59.dll  
0x00007FFF99A30000 59.7.100.0           avdevice-59.dll  
0x00007FFF48F60000 59.27.100.0          avformat-59.dll  
0x00007FFFA2810000 10.0.19041.985       OLEAUT32.dll  
0x00007FFF6B9E0000 6.7.100.0            swscale-6.dll  
0x0000000067380000 1.1.0.0              libsndfile-1.dll  
0x00007FFF54BB0000 1.21.1.0             OpenAL32.dll  
0x000000006ACC0000                      libgmp-10.dll  
0x00007FFF54770000 2.0.20.0             SDL2.dll  
0x00007FFF9DE30000                      libgmpxx.dll  
0x00007FFFA28E0000 10.0.19041.2193      SETUPAPI.dll  
0x00007FFF9B410000                      boost_thread-vc142-mt-x64-1_80.dll  
0x00007FFFA05D0000 10.0.19041.2486      bcrypt.dll  
0x00007FFF6BE40000                      boost_locale-vc142-mt-x64-1_80.dll  
0x00007FFF9C0A0000                      tbbmalloc_proxy.dll  
0x00007FFF47040000 3.10.9150.1013       python310.dll  
0x00007FFF56740000 14.29.30139.0        MSVCP140.dll  
0x00007FFF99940000 14.29.30139.0        VCRUNTIME140.dll  
0x00007FFF9C060000 14.29.30139.0        VCRUNTIME140_1.dll  
0x00007FFF98660000 10.0.19041.1         AVIFIL32.dll  
0x00007FFF905C0000 10.0.19041.867       dbghelp.dll  
0x00007FFF88F90000 6.10.19041.1110      COMCTL32.dll  
0x00007FFF97BD0000 10.0.19041.546       VERSION.dll  
0x00007FFF882F0000 10.0.19041.2193      OPENGL32.dll  
0x0000000070680000                      libfftw3-3.dll  
0x00007FFF9E1A0000 10.0.19041.746       dwmapi.dll  
0x00007FFF53FD0000 57.28.100.0          avutil-57.dll  
0x00007FFF53550000                      OpenEXRCore.dll  
0x00007FFF9B2B0000 14.29.30139.0        MSVCP140_CODECVT_IDS.dll  
0x00007FFF44670000 10.0.19041.1503      dbgeng.dll  
0x00007FFF9B290000                      IlmThread.dll  
0x00007FFF98620000 4.7.100.0            swresample-4.dll  
0x00007FFF81A10000 10.0.19041.546       Secur32.dll  
0x00007FFF99850000 10.0.19041.1         AVICAP32.dll  
0x00007FFF8CE20000 10.0.19041.546       WINMM.dll  
0x00007FFF9B8E0000 10.0.19041.1         MSACM32.dll  
0x00007FFF89450000 10.0.19041.1         MSVFW32.dll  
0x00007FFF882C0000 10.0.19041.2193      GLU32.dll  
0x00007FFF9C0E0000 10.0.19041.546       XmlLite.dll  
0x00007FFF53490000 10.0.19041.1503      dbgmodel.dll  
0x00007FFF7E530000 10.0.19041.1         winmmbase.dll  
0x00007FFFA0490000 10.0.19041.2130      SSPICLI.DLL  
0x00007FFF9E690000 10.0.19041.2673      windows.storage.dll  
0x00007FFF9FF50000 10.0.19041.2673      Wldp.dll  
0x00007FFF9E490000 10.0.19041.546       kernel.appcore.dll  
0x00007FFF9DFC0000 10.0.19041.2193      uxtheme.dll  
0x00007FFFA0E90000 10.0.19041.2486      bcryptPrimitives.dll  
0x00007FFFA0510000 10.0.19041.844       profapi.dll  
0x00007FFFA1A70000 2001.12.10941.16384  clbcatq.dll  
0x00007FFF93750000 10.0.19041.1503      MMDevApi.dll  
0x00007FFFA02A0000 10.0.19041.1620      DEVOBJ.dll  
0x00007FFF92F70000 10.0.19041.2364      AUDIOSES.DLL  
0x00007FFFA0440000 10.0.19041.546       powrprof.dll  
0x00007FFFA0420000                      UMPDC.dll  
0x00007FFFA1950000 10.0.19041.2673      MSCTF.dll  
0x00007FFF992B0000 10.0.19041.2673      AppXDeploymentClient.dll  
0x00007FFF24500000 24.20.100.6286       ig9icd64.dll  
0x00007FFF9EE90000 10.0.19041.2311      dxgi.dll  
0x00007FFF97BE0000 10.0.19041.546       dxcore.dll  
0x00007FFF938D0000 24.20.100.6286       igc64.dll  
0x00007FFF81170000 10.0.19041.1387      dataexchange.dll  
0x00007FFF9CAE0000 10.0.19041.2075      d3d11.dll  
0x00007FFF9D330000 10.0.19041.2546      dcomp.dll  
0x00007FFF9AA10000 10.0.19041.1865      twinapi.appcore.dll  
0x00007FFF8A7C0000 10.0.19041.2546      textinputframework.dll  
0x00007FFF9DC00000 10.0.19041.2193      CoreMessaging.dll  
0x00007FFF9D8A0000 10.0.19041.546       CoreUIComponents.dll  
0x00007FFF9F710000 10.0.19041.546       ntmarta.dll  
0x00007FFF9C3D0000 10.0.19041.2311      wintypes.dll  
0x00007FFF80F50000 10.0.19041.1949      explorerframe.dll  
0x00007FFF82E90000 10.0.19041.1566      directmanipulation.dll  
0x00007FFF9FEB0000 10.0.19041.546       CRYPTSP.dll  
0x00007FFF9F5D0000 10.0.19041.1052      rsaenh.dll  
0x00007FFF9FEA0000 10.0.19041.546       CRYPTBASE.dll  
0x000001334C4A0000 3.10.9150.1013       python3.DLL  
0x00007FFF98980000 3.10.9150.1013       _bz2.pyd  
0x00007FFF89260000 3.10.9150.1013       _lzma.pyd  
0x00007FFF895D0000 3.10.9150.1013       _socket.pyd  
0x00007FFF9F9A0000 10.0.19041.1865      IPHLPAPI.DLL  
0x00007FFF99CC0000 3.10.9150.1013       select.pyd  
0x00007FFF85D00000 3.10.9150.1013       _ssl.pyd  
0x00007FFFA0760000 10.0.19041.2486      CRYPT32.dll  
0x00007FFF524C0000 1.1.1.17             libssl-1_1.dll  
0x00007FFF458A0000 1.1.1.17             libcrypto-1_1.dll  
0x00007FFF9FCB0000 10.0.19041.546       mswsock.dll  
0x00007FFF99B60000 3.10.9150.1013       _hashlib.pyd  
0x00007FFF98610000 3.10.9150.1013       _queue.pyd  
0x00007FFF4B450000 3.10.9150.1013       unicodedata.pyd  
0x00007FFF980D0000 3.10.9150.1013       _uuid.pyd  
0x00007FFF86FF0000 3.10.9150.1013       _asyncio.pyd  
0x00007FFF89440000 3.10.9150.1013       _overlapped.pyd  
0x00007FFF6B9B0000 3.10.9150.1013       _ctypes.pyd  
0x00007FFF89250000                      libffi-7.dll  
0x00007FFF87BE0000                      _multidict.cp310-win_amd64.pyd  
0x00007FFF7F520000                      _quoting_c.cp310-win_amd64.pyd  
0x00007FFF878F0000                      _helpers.cp310-win_amd64.pyd  
0x00007FFF79F80000                      _http_writer.cp310-win_amd64.pyd  
0x00007FFF6B5F0000                      _http_parser.cp310-win_amd64.pyd  
0x00007FFF87540000                      _websocket.cp310-win_amd64.pyd  
0x00007FFF6DB20000                      _frozenlist.cp310-win_amd64.pyd  

# Python backtrace

**Comment by Jackle4Foxy** [comment] 2023-03-21 11:46
see attached 
![1a](https://user-images.githubusercontent.com/75924956/226596999-377de35d-2c79-4fd9-9a22-72de17b19fc9.jpg)

**Comment by ReinerBforartists** [comment] 2023-03-21 11:50
Many thanks. Makes me scratch my head. As told before, we cannot reproduce it :/

**Comment by ReinerBforartists** [comment] 2023-03-21 11:53
One last try, have you tried our latest developer build? https://www.bforartists.de/download/

**Comment by Jackle4Foxy** [comment] 2023-03-21 12:00
https://www.bforartists.de/data/binaries/Install_Bforartists3_341.exe
I was running this one

**Comment by Jackle4Foxy** [comment] 2023-03-21 12:01
https://www.bforartists.de/data/binaries/Install_Bforartists3_341.exe
I was running this one

**Comment by Jackle4Foxy** [comment] 2023-03-21 14:47
Same problem with Dev-build

**Comment by Jackle4Foxy** [comment] 2023-03-21 15:07
Still downloading Blender 3.6 and latest 3.5
A older build of Blender 3.5 gave no problems

Bforartists 2.9.3 works ok, no problems there

**Comment by ReinerBforartists** [comment] 2023-03-21 17:26
Many thanks for your help. I feared it. We pull our code from the master, and this code is always one developer cycle ahead already. Blender separates the release branch roughly one month before the actual release. And then the new things goes already into the Blender master. Including new problems. It seems that we have such a problem here. 

In best case it is a bug in the code somewhere. In worst case your hardware is deprecated with the newest Blender version. Could you nevertheless be so kind to report it to the Blender developers? They are thankful for every report :)

**Comment by ReinerBforartists** [comment] 2023-03-22 18:03
I will close this one now since we have no influence at this bug anyways. Fingers crossed that it gets fixed at the Blender side!

**Closed by ReinerBforartists** 2023-03-22 18:03 UTC
Labels: 2 - bug, Blender Bug
