### ISSUE TITLE
Cmake Release - OneApi problems at Linux

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3541] opened 2023-05-19 18:46 UTC
Right now we have a small market share and I think few use OneAPI graphics. Cycles OneAPI has proven to be complex, the depedencies are not opensource, you gotta compile them yourself for the binaries and for Windows (which is a headache in itself) and it bites often. If we disable this, we get faster compile times, less compile errors, and.. live simpler, ei, faster builds for our userbase and more free time for actual development and better maintenance. Cut our losses, and be for the artist that don't use OneAPI. 

At the moment we don't know who uses OneAPI if at all...  

**Here are the methods to get it going:**
https://projects.blender.org/blender/blender/issues/96840

Here is additional things to get it going on Ubuntu, ei, the answer to the most recent issue on Discord. 
```./lib/linux_x86_64_glibc_228/dpcpp/bin/clang++ -std=c++14 -pedantic -Wall test.cpp -o test -v on a test.cpp file that includes <iostream>. It tells which GCC installation clang is using, and it'll be the one for which libstdc++-N-dev is missing and needs to be installed.```

**Current Issue:**
![vmplayer_WUtd1nNtpM](https://github.com/Bforartists/Bforartists/assets/35357409/bf61233c-c98b-44ed-ab1d-0763ca6efca8)

As you can see, even looking at the surface (and in practicality)... it's a pain in the butt specially for Ubuntu, and things aren't even really available in the SDK for GPL anyway. This isn't FOSS. 

From the Blender Documentation:
> OneAPI support is available on Windows & Linux, for Intel Arc GPUs. Building must be done using precompiled libraries, which includes the compiler for OneAPI (there is currently no Intel provided SDK that works with Blender).  
https://wiki.blender.org/wiki/Building_Blender/GPU_Binaries

To turn it off is a simple Cmake in the Release file, toggle on to off. Peace. 

Shall we?

**Comment by ReinerBforartists** [comment] 2023-05-19 19:05
Well, we promised to deliver the same features than blender ...

Let's turn it off in the case it makes trouble and does not work, like now. I am pretty sure that it will get back to work at one point.

**Comment by Draise14** [comment] 2023-05-22 00:31
Great. Yeah, you are right, sticking close to Blender source on core arquitecture is a must - but if we simply can't compile, skipping this to not burn time for the devbuild can do.

**Comment by iyadahmed** [comment] 2023-05-22 01:31
but the solution is a simple 
`sudo apt install libstdc++-12-dev`

not sure about the 12 though someone needs to test ^^ it would be either 10, 11 or 13
but let's 12 first ^^

**Comment by iyadahmed** [comment] 2023-05-22 02:27
yep it was 12
https://devtalk.blender.org/t/make-release-fails-at-oneapi-at-ubuntu-after-upgrade-from-20-04-to-22-04/26895/7?u=iyadahmed

**Comment by ReinerBforartists** [comment] 2023-05-22 06:04
Ah, this one slipped my mind so fast ...

**Comment by ReinerBforartists** [comment] 2023-05-26 15:49
Hmm. 12 does not work. Compilation still fails. Let's try 13

**Comment by ReinerBforartists** [comment] 2023-05-26 15:50
No such thing than libstdc++-13-dev

**Comment by ReinerBforartists** [comment] 2023-05-30 05:30
My whole vm has went wonky. I cannot paste the Optix path anymore into Cmake. Ubuntu immediately crashes then.

Reverting to a earlier copy of Ubuntu. This means though that we will not compile with Cuda 12, but with Cuda 11

![crash](https://github.com/Bforartists/Bforartists/assets/13919702/bf0776e3-d465-47c6-a875-ee12581a420c)

**Comment by ReinerBforartists** [comment] 2023-05-30 09:55
We are stuck in a loophole here. I have reverted to a earlier version of the VM with Cuda 11. No crashes, but it does not finish the compilation. 

I then have upgraded to Cuda 12. Now the compilation finished. But now i am back at the crashes with pasting text. And have no clue how to report this to Ubuntu since it completely crashes.

**Comment by ReinerBforartists** [comment] 2023-05-30 16:18
Here you can see how to reproduce the trouble 

https://cloud.bforartists.de/index.php/s/LpBNeCXwzFj6gdX

I have tried the procedure now twice, always starting from a backup of the VM. With Cuda 11 i have no problem. But BFA does not compile. Adding Cuda 12 will allow me to compile, but will cause this problems now that i cannot longer edit Cmake. I can just guess that the graphics drivers for the desktop goes fubar here.

@Draise14 , before i start to report this around, i need to make sure it is not my system or the VM. So could you please check if you can reproduce this behaviour? Could you please copy your VM, make sure Cuda 12 and libstdc++-12-dev is installed? Then you should be able to compile at Ubuntu again. And then try to simply right click at one of the variables in Cmake to test if you can reproduce the crash?

sudo apt install libstdc++-12-dev

And the advice to install Cuda 12 is at the Nvidia page.

**Comment by Draise14** [comment] 2023-05-30 16:20
I'll try give this a go after work - right now I haven't installed CUDA 12 correctly, as I didn't uninstall CUDA 11 first before trying to install it. That might be one of the steps I didn't do right.

**Comment by ReinerBforartists** [comment] 2023-05-30 16:22
Me neither. Just install Cuda 12 over it. It will work.

**Comment by ReinerBforartists** [comment] 2023-05-30 16:32
Hmm, but maybe you are at something here. Old driver battling with new driver. I would nevertheless be happy with somebody to confirm my trouble.

The good news is, as long as i don't touch cmake it compiles ^^

**Comment by ReinerBforartists** [comment] 2023-06-04 06:39
Meow?

**Comment by Draise14** [comment] 2023-06-04 11:50
No luck my end yet. Might have to roll back my Ubuntu distro.

**Comment by ReinerBforartists** [comment] 2023-06-04 12:44
Can you at least reproduce my problem?

**Comment by Draise14** [comment] 2023-06-04 12:47
I couldn't. I had trouble implementing the header fix Iyad mentioned. No oneapi compile.

**Comment by ReinerBforartists** [comment] 2023-06-04 12:52
To check if my problem arrises does not require to have oneapi to compile. Just open cmake, and right click at one of the string fields, as shown in the video above.

**Comment by ReinerBforartists** [comment] 2023-06-06 07:27
Now it's getting unfunny. I haven't changed anything, even waited with the updates. The build from last week succeeded. This time i run into the errors again.

![unfunny](https://github.com/Bforartists/Bforartists/assets/13919702/5d9ebce5-800b-425b-8353-eb6919724c51)

**Comment by ReinerBforartists** [comment] 2023-06-06 07:30
And i cannot update Ubuntu anymore from the graphical UI, clicking at the Update button leads me to black screen. -.-

**Comment by ReinerBforartists** [comment] 2023-06-06 08:00
Okay, the second attempt is at compiling the oneapi stuff again. Fingers crossed ...

**Comment by ReinerBforartists** [comment] 2023-06-06 08:23
And now it compiled successfully. It remains curious.

**Comment by ReinerBforartists** [comment] 2023-06-07 15:49
Just an observation, and maybe i am wrong. It seems that OneAPI requires to compile the release version twice. And with the second attempt it finds the files that are missing.

So @Draise14 , have you tried to run the make release twice?

**Comment by ReinerBforartists** [comment] 2023-06-07 16:26
For the other problem, i have just installed a new Ubuntu VM from scratch, installed Cuda 12.1 as described at the webpage, opened Libre Office, saved a document, copied some text, and the current state of this new VM is now:

![blackscreen](https://github.com/Bforartists/Bforartists/assets/13919702/6d2a2615-57de-4ca0-b9a8-8a9ad94b7828)

Either we report this to Ubuntu, which i still have no idea how to since they insist to do a bug report via console. And there is no console anymore. Or we switch platform. Away from this crap OS. Or both ...

**Comment by Draise14** [comment] 2023-06-08 16:07
Yeah, maybe another OS might be better. I haven't had luck here, nor a lot of time. We need something that.. just works.

**Comment by ReinerBforartists** [comment] 2023-06-08 16:32
I upgraded my VMWare player to version 17, it was at 16 still. But same result. So it is really Ubuntu 22.04 lts in conflict with Cuda 12.1. What is curious is that i cannot find any problems like i have here in the web. And i am still at searching where to report this.

**Comment by iyadahmed** [comment] 2023-06-08 17:52
I have Rocky8 setup in a vm but haven't setup cuda or optix yet

**Comment by ReinerBforartists** [comment] 2023-06-26 16:10
Finally reported the bug to Ubuntu https://bugs.launchpad.net/ubuntu/+bug/2025080

**Comment by iyadahmed** [comment] 2023-06-30 12:51
> Now it's getting unfunny. I haven't changed anything, even waited with the updates. The build from last week succeeded. This time i run into the errors again.
> 
> ![unfunny](https://user-images.githubusercontent.com/13919702/243593830-5d9ebce5-800b-425b-8353-eb6919724c51.jpg)


could be low ram 
![image](https://github.com/Bforartists/Bforartists/assets/25552173/0aabe1d1-1e35-48a2-b1f1-de0f1d693699)

**Comment by ReinerBforartists** [comment] 2023-06-30 15:45
Run it again. Is at least worth a try. And here it compiled just fine.

As told i made the experience that sometimes the second run succeeds then. Which may have to do that most is already compiled, and not so much ram is needed with the second run then.

**Comment by iyadahmed** [comment] 2023-06-30 17:39
Should we close this issue now or?

**Comment by ReinerBforartists** [comment] 2023-06-30 19:04
Yes. We might need another issue for the migration to rocky linux though. The bug report is ignored hard ^^

**Closed** 2023-06-30 19:04 UTC
Labels: 2 - bug
