### ISSUE TITLE
UV Editor - New "Select Similar" operator

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3088] opened 2022-06-28 16:33 UTC
![image](https://user-images.githubusercontent.com/35357409/176232973-8d3db62b-e46c-4557-ac27-cec8758229da.png)

New Operator, new documentation and iconography

UV Editor - Select - Select Similar

**File:**
`release/scripts/startup/bl_ui/space_image.py`
![image](https://user-images.githubusercontent.com/35357409/176246979-f62df069-3165-43a4-b201-2433d444cc11.png)

**Comment by ReinerBforartists** [comment] 2022-07-04 09:01
Fixed in master

**Comment by ReinerBforartists** [comment] 2022-07-04 09:14
Wow, what is this can of worms? The content changes, dependant of what mode and what selection is active O_O

And vs code made its fun to me too it seems ... So reopen it.


![mode](https://user-images.githubusercontent.com/13919702/177123424-895abaa5-5075-4462-ae06-ae327dde4ced.jpg)

**Comment by ReinerBforartists** [comment] 2022-07-04 09:47
SHA-1: 1154b45526797d6f5999d1be18f92124baf8107f

* UV: Add "Select Similar" operator in UV editor

Resolves T47437.

Differential Revision: https://developer.blender.org/D15164

But no exlanation how this all is meant to work. Investigating ...

**Comment by ReinerBforartists** [comment] 2022-07-04 09:55
For me this operator is undocumentable, sorry. It is not clear what similar elements are even compared, and what result is to expect.

The code that brings the menus is a long list of cases that we simply cannot reproduce as menus.  As a consequence i will revert my changes, add an icon instead, write it in the manual exactly as i have written here: "this operator is undocumentable", and call this task a day.

**Comment by ReinerBforartists** [comment] 2022-07-04 11:11
This fixes at least the missing icon at the main operator. The sub menus still needs icons too.

![iconized](https://user-images.githubusercontent.com/13919702/177143173-3e4b516f-f086-4a25-adb5-5f0ad7977ac7.jpg)

**Comment by ReinerBforartists** [comment] 2022-07-04 16:10
Ah, now the picture becomes clearer. The sub menus are dependant of if you are in vertex, edge or face select mode. In both sub modes, Sync selection on and off.

There are three sub menus. I couldn't get pinned to work proper so far. But similar edge length selects what it should select. At least somehow. Edge select should just calculate edges. But it calculates vertices too. And so we get a much bigger selection than what it should select. But i guess to fix this is a job for the Blender devs.

![vertsedgesfaces](https://user-images.githubusercontent.com/13919702/177190195-789bc55a-1281-4c60-aabf-16cbf8630fd6.jpg)

![selectedges](https://user-images.githubusercontent.com/13919702/177190204-0743328a-4d6a-47d7-8b3a-27f01a5d9b3e.jpg)

**Comment by ReinerBforartists** [comment] 2022-07-04 16:11
Mh, to add proper tool tips could be another task here.

**Comment by ReinerBforartists** [comment] 2022-07-04 16:13
Initial issue with the missing icons fixed in master. 

The rest is postponed for now. New Blender version is at the corners. And so we better empty the tracker first before continuing to add improvements.

Adding the manual chapter here now ...

**Comment by ReinerBforartists** [comment] 2022-07-04 16:51
Too late ^^

**Comment by Draise14** [comment] 2022-07-27 17:32
Question @ReinerBforartists what is left with this task? What needs to be done now?

**Comment by Draise14** [comment] 2022-08-03 21:21
I guess what I did with the dynamic selection menu in the VSE for changing could have the idea for this one. It was dependent on selection.

**Comment by ReinerBforartists** [comment] 2022-08-15 09:45
Let's have a look if i can get this one to work

**Comment by ReinerBforartists** [comment] 2022-08-15 10:31
>3

Does not work with mesh mode, does not work with UV mode. No error, but no functionality. I fear this is mission impossible. 

![similarfails](https://user-images.githubusercontent.com/13919702/184620177-7bd33e11-8c90-4972-ad08-1591396bfda4.jpg)

**Comment by ReinerBforartists** [comment] 2022-08-15 10:57
Giving up, this is not to solve.

**Closed by ReinerBforartists** 2022-08-15 10:57 UTC
Labels: 0 - task, 4 - needs work
