### ISSUE TITLE
Iconography - General - Desaturate all icons just a little tiny bit

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2654] opened 2021-09-08 20:20 UTC
# Feature Request
I have been enjoying the iconography, but lately I have noticed a lot of users quick on about the bright colours. The design overhaul from 2.8+ days was great, nice iconography, but we also saturated the colours, even added a tiny bit more luminance to all of them.

Here is a comparison:
**Bforartists 1**
![bforartists_CbXmo7FJki](https://user-images.githubusercontent.com/35357409/132578851-726eda43-6bc9-40e8-9442-bbd71f18c522.png)
Notice that the menu has colour, the property shelf too, but it's not hitting you hard. 

**Bforartists Dev Build (today)**
![bforartists_ra5dVtF4IB](https://user-images.githubusercontent.com/35357409/132578879-4315fa78-1fe9-45b2-bdcc-30f7cac64f9a.png)
Here, most icons and menus hit you quite obviously, which is great for legibility - but maybe a little too much contrast. 

Notice that straight off the bat, the colours hit you strong currently - which is great, but it is a little jarring. Iconography is incredible, useful, and handy - but over long use it can be a little.. too colourful? And this often scares new users - immediate feedback is.. "woah, so many icons, too much colour". 

# Task
Add a filter to all icons in the Inkscape file to desaturate a tiny bit.. if that's posssible. If not.. desaturating all of them will be time consuming. If too time consuming, don't worry bout it. This is a low priority, but might be welcome to a few.

**Comment by ReinerBforartists** [comment] 2021-09-09 06:17
Okay. let's use the monochrome icons from Blender :)

**Comment by Draise14** [comment] 2021-09-09 10:08
Lol that's not what I meant. I mean a drop in like 5% to 15% saturation. 

Monochrome would kill me. 

It's really a very minor request on what is already good.

**Comment by ReinerBforartists** [comment] 2021-09-09 10:36
But that's the logical consequence of your request :)

We have been in the situation already where the user was not thrown to death with all the icons in the UI. But then a not closer defined member of our team asked if this button could be in the header, or that button could be in the header. Which was nothing wrong at all, but simply a question of workflow. But this has a price. More UI elements produces more visual noise.

And we have been already in the situation when the Blender code did desaturate our colored icons. It just didn't help. Colored icons have simply the side effect that they show color. And that the icons are really colorful is by design. I want them to be as colorful as possible. So that they are as good to distinguish as possible. They are tiny. We need best separation.

What happens when the icons are too equal in one area can be seen here: https://github.com/Bforartists/Bforartists/issues/2656

And this is what happens in general when you take the color away. Then the icons looks all equal and nothing is disturbing anymore. But also not to distinguish anymore. You can have either the one or the other.

What you ask for is in real a completely new icon set that fits better together. And that's nothing that i am able to provide, sorry.

The icon set can of course be improved. It has historically grown. And there are still some ugly ones around. You can report them if you want. But not all at once please. This task is not to fulfill.

That said, i will close this issue now. Thanks for the idea.

**Closed by ReinerBforartists** 2021-09-09 10:36 UTC
Labels: Feature request

**Comment by Draise14** [comment] 2021-09-09 10:38
No problem! Yeah, case by case is always better.
