### ISSUE TITLE
Scroll Bar in Outliner does not show

### ISSUE THREAD

**Issue by jinujohnm** [Bforartists/Bforartists#2575] opened 2021-08-01 12:49 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ReinerBforartists** [comment] 2021-08-01 15:42
And your question is? :)

**Comment by jinujohnm** [comment] 2021-08-01 16:33
Why there is no scroll bar in the outliner. Had to use the mouse wheel to scroll down a long list. Or did I missed it (the scroll bar). Please let me know. Thank you.

**Comment by ReinerBforartists** [comment] 2021-08-01 18:44
Congratulations, you found a bug. Thanks for the report :)

Unfunny :/

Must be something with the workspace layouts. Making the editor new solves the problem. I will have a closer look at it tomorrow. As a workaround, you can switch the properties editor to the outliner. And here you have the scrollbar available. Switching to Outliner from the Properties editor might even solve your space problem. That's why we have added the switch here.

![noscrollbar](https://user-images.githubusercontent.com/13919702/127781936-e14c3309-a57c-4722-a6eb-22e15c8c7db6.jpg)

**Comment by ReinerBforartists** [comment] 2021-08-01 18:45
The problem exists in all workspaces. Seems that we have to redo the layouts again.

**Comment by ReinerBforartists** [comment] 2021-08-01 18:48
Great, the properties editor is also affected. And this one is not to convince :/

**Comment by ReinerBforartists** [comment] 2021-08-01 18:52
Ah, getting closer. I was able to reproduce this behaviour in Blender. Seems that we need to make a bug report for it.

**Comment by ReinerBforartists** [comment] 2021-08-02 06:31
It works when i redo the layouts, and save the startup file. But the scrollbar vanishes when i compile with this startup.blend then.

**Comment by ReinerBforartists** [comment] 2021-08-02 07:12
Created a blender bug report. Maybe they know what is going on here.

**Comment by ReinerBforartists** [comment] 2021-08-04 10:33
Let's have a look if we can find the commit in question.

2.6.0 worked fine, and was released on 26 Nov 2020

2.7.0 is broken, and was released on 25 Jan 2021

**Comment by jinujohnm** [comment] 2021-08-04 10:42
In the last Blender Today live session, some one mentioned about the outliner scroll bar, and it looks like it is right there in blender.
Here is the link to the video, please fast forward to 48th minute of the video.
https://www.youtube.com/watch?v=h-pKbazp4Ak

**Comment by ReinerBforartists** [comment] 2021-08-04 10:50
Ah nice, they want to show it all the time now. Thanks for the link.

And yes, it shows in Blender. I am currently at investigating at which point we have introduced the bug to Bforartists. It should definitely not be possbile to transfer the visibility state by a blend file. That's why i made the bug report to the Blender bug tracker.

Build from 23.02.2020 already shows the problem. Picking the next test version two weeks earlier ...

**Comment by ReinerBforartists** [comment] 2021-08-04 16:04
13.12.2020 - problem persists. One more week back ...

**Comment by ReinerBforartists** [comment] 2021-08-04 16:17
06.12. - problem persists. Not sure if i had a merge between 06.12 and the release of 2.60. Checking ...

**Comment by ReinerBforartists** [comment] 2021-08-04 16:30
Yes i had. 29.11 still has the problem. Bforartists 2.6.0 released at 27.11 not. So the problem got introduced with this merge from 29.11. Going through the commits of this week.

**Comment by ReinerBforartists** [comment] 2021-08-06 10:37
Catched the cause i think. 

SHA-1: 046ea1c55df71a3de4a584271df99dc84ab11541

* Timeline/Dope sheet/NLA editors - slider covers button to call sidebar

@iyadahmed, this is your implementation. I am lost with what the code is purposed to do in the versioning_defaults.c file.  

I think i will for now remove this code piece. We can live with the slider covering the sidebar button. But not so well with no sliders. But i am not sure what to do with the other files. This task made also changes to space_action. Shall we revert this too?

SHA-1: c6575cb6bcac411ef3954281f4a8ba335aee7b1d

* Dope sheet editor - slider covers button to call sidebar

**Comment by ReinerBforartists** [comment] 2021-08-06 10:54
Original issue was this one i think: https://github.com/Bforartists/Bforartists/issues/1867

**Comment by iyadahmed** [comment] 2021-08-06 11:30
> Catched the cause i think. Replacing the versioning_defaults.c file with the file before the commit makes the sliders reappear. You need to compile from scratch though. There seems to be some cmake files involved.
> 
> SHA-1: [046ea1c](https://github.com/Bforartists/Bforartists/commit/046ea1c55df71a3de4a584271df99dc84ab11541)
> 
> * Timeline/Dope sheet/NLA editors - slider covers button to call sidebar
> 
> @iyadahmed, this is your implementation. Do you want to have a look at it? I am lost with what the code is purposed to do in the versioning_defaults.c file. There is as usual the issue number missing. So i don't even know what the original issue is.
> 
> We can live with the slider covering the sidebar button. But not so well with no sliders. But i am not sure what to do with the other files. This task made also changes to space_action. Shall we revert this too?
> 
> SHA-1: [c6575cb](https://github.com/Bforartists/Bforartists/commit/c6575cb6bcac411ef3954281f4a8ba335aee7b1d)
> 
> * Dope sheet editor - slider covers button to call sidebar

yes it is related to the issue
we can restore versioning_defaults.c no issue, this just makes Bforartists fix slider cover when opening a file

**Comment by iyadahmed** [comment] 2021-08-06 12:01
hmm just commented those lines, deleted default files, and still scroll bar doesn't show

**Comment by ReinerBforartists** [comment] 2021-08-06 13:04
As told, you need to empty everything, and compile completely from scratch.

Here it worked. I haven't tested it at the actual version though. Just between the working version 2.6.0 and the one that did not work afterwards.

**Comment by iyadahmed** [comment] 2021-08-06 13:08
> As told, you need to empty everything, and compile completely from scratch.
> 
> 
> 
> Here it worked. I haven't tested it at the actual version though. Just between the working version 2.6.0 and the one that did not work afterwards.
> 
> 
> 
> 

Hmmm

**Comment by ReinerBforartists** [comment] 2021-08-06 15:41
I'll check.

**Comment by ReinerBforartists** [comment] 2021-08-06 16:21
We are doomed :/

Reverting this commit did definitely fix the issue in the branch. But not in the master.

**Comment by ReinerBforartists** [comment] 2021-08-06 16:29
Ah, wait, the problem was transferable by a blend file to Blender. And we have written new blend files meanwhile. Good possible that we have the error in our startup.blends now. No matter if the code was removed or not.

I will tomorrow catch the old blend files from before this commit.

**Comment by ReinerBforartists** [comment] 2021-08-07 06:36
As expected. it was the blend files. Scrollbar is back.

Unfortunately the umber of rows in the tool shelf is now broken. And we need to check the commits for other changes that we have lost now.

![scrollbar](https://user-images.githubusercontent.com/13919702/128590989-0f819530-951d-445f-9c87-ba7d3c50c1d7.jpg)


![oldtoolbarstate](https://user-images.githubusercontent.com/13919702/128590985-6a367ac3-76a5-4a6d-b991-52b1004b3aac.jpg)

**Comment by ReinerBforartists** [comment] 2021-08-07 08:19
(Hopefully) fixed in master.

This one was a real challenge. Recreated the nodes layout, hunted through all 3d view tool shelves to make them wider again, and readded the toolbar in the layouts where they were missing. I hope i have catched all the changes that we did at the blend files after this point. But i haven't found antything obvious anymore. And the scrollbar is back, yay \o/

Please have an open eye when testing the next developer build.

**Closed by ReinerBforartists** 2021-08-07 08:19 UTC
Labels: 2 - bug

**Comment by iyadahmed** [comment] 2021-08-07 10:14
> As expected. it was the blend files. Scrollbar is back.
> 
> 
> 
> Unfortunately the umber of rows in the tool shelf is now broken. And we need to check the commits for other changes that we have lost now.
> 
> 
> 
> ![scrollbar](https://user-images.githubusercontent.com/13919702/128590989-0f819530-951d-445f-9c87-ba7d3c50c1d7.jpg)
> 
> 
> 
> 
> 
> ![oldtoolbarstate](https://user-images.githubusercontent.com/13919702/128590985-6a367ac3-76a5-4a6d-b991-52b1004b3aac.jpg)
> 
> 
> 
> 
> 
> 
> 
> 

Yes for the tool bar I manually created startup files

**Comment by ReinerBforartists** [comment] 2021-08-07 10:24
And i reverted it then ^^

It was more than one task that modified the blend files this spring. As told, we had a editortype menu showing, missing toolbars, and implementing the tabs back into the tool shelf made also some modifications necessary.

**Comment by iyadahmed** [comment] 2021-08-07 10:30
> And i reverted it then ^^
> 
> 
> 
> It was more than one task that modified the blend files this spring. As told, we had a editortype menu showing, missing toolbars, new editors, and implementing the tabs back into the tool shelf made also some modifications necessary.

Oh ^^, ok will try to find a way to make it shaped well, already have some ideas,

- Edit versioning_*.c files
- Make toolshelf snap on drawing and mot on dragging

**Comment by ReinerBforartists** [comment] 2021-08-07 10:31
Or poke the Blender developers that they finally fix this issue. It's a Blender bug ;)

**Comment by iyadahmed** [comment] 2021-08-07 10:33
> Or poke the Blender developers that they finally fix this issue. It's a Blender bug ;)
> 
> 
> 
> EDIT, wait you mean the tool shelf. I meant the scroll bar issue ^^
> 
> 
> 
> Please make a task before you start to do any modifications!

Oh right ^^
