### ISSUE TITLE
General - Blender version and Bforartsits version number disconnect in Info

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1901] opened 2020-10-23 23:06 UTC
# Issue
![image](https://user-images.githubusercontent.com/35357409/97060841-53142080-155a-11eb-821d-013bef841fdf.png)

Right now Bforartists shows a version number which is based on Blender. 

It's good to show users what I'm using and what feature set I'm using when it comes to Blender.. but it doesn't show the Bforartists version, or to what number that is relative to. It's disconnected. 

# Solution
Change it to "[BFA version ###] ([Blender version ###])

**Comment by ReinerBforartists** [comment] 2020-10-24 06:49
This task is a duplicate of https://github.com/Bforartists/Bforartists/issues/1703

I want to remove it completely if possible since it is visual noise.

Closing.

**Closed by ReinerBforartists** 2020-10-24 06:49 UTC
Labels: Feature request
