### ISSUE TITLE
Showstopper - File - New is broken

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3604] opened 2023-06-20 08:58 UTC
We have a showstopper bug here. I cannot create a new scene anymore. BFA locks up.

![filenew](https://github.com/Bforartists/Bforartists/assets/13919702/a98f9a83-0a69-4161-ade8-0b8fafdaf16b)

**Comment by ReinerBforartists** [comment] 2023-06-20 09:03
Exists since a while. BFA 3.5.1 did not have it. But the latest devbuild already has the problem.

**Comment by Draise14** [comment] 2023-06-20 17:58
That's strange, I use this operator often, from the toolbar. Let me test to double confirm.

**Comment by Draise14** [comment] 2023-06-20 18:09
![image](https://github.com/Bforartists/Bforartists/assets/35357409/8a251b29-2d91-4491-a40d-29c716cf6ca3)

Can reproduce:
1. When you are on factory and there is no config data saved, then it hangs. 
2. When you have the default startup saved to the config (user preferences) then it won't crash.

**Comment by Draise14** [comment] 2023-06-20 18:41
It must be looking in the config folder initially, unlike old times that would look in the SYSTEM folder first if USER didn't exist.

**Comment by ReinerBforartists** [comment] 2023-06-20 19:04
Thanks for confirming.

**Comment by Draise14** [comment] 2023-06-20 19:09
![image](https://github.com/Bforartists/Bforartists/assets/35357409/5e6fe0cf-ddd5-49b2-b8e9-8eae7b93100a)
Digging deeper, maybe it's this operator that's having trouble.

**Comment by ReinerBforartists** [comment] 2023-06-21 06:08
How does Blender handle this?

**Comment by Draise14** [comment] 2023-06-21 16:16
Blender doesn't, this is a BFA operator it seems? Since you can only make a new scene from template..... Maybe we could re-write this operator to load from SYSTEM or USER instead of the template code.

**Comment by ReinerBforartists** [comment] 2023-06-21 17:50
I think to remember that this is a old Blender operator. But yeah, Blender doesn't use it anymore.

**Comment by Draise14** [comment] 2023-06-22 21:28
Put the big guns onto this one. (ei, Iyad!)

**Comment by iyadahmed** [comment] 2023-06-27 09:31
this is related to dimensions of an area, I think this was recently edited by us
![image](https://github.com/Bforartists/Bforartists/assets/25552173/4516b090-2efd-40fe-9113-3bfba2213a04)

**Comment by iyadahmed** [comment] 2023-06-27 14:23
> When it was edited by us then it should contain a bfa comment somewhere.

honestly I was just guessing that it was our edit, could be a merge problem, still looking for it

**Comment by ReinerBforartists** [comment] 2023-06-27 16:05
Hmm, i am wrong, it is not unused. It is used in Blender too, with the corresponding app_template value.

![homefile](https://github.com/Bforartists/Bforartists/assets/13919702/7a2456d7-de88-4c9b-bd90-d05f2cdeebfe)

**Comment by ReinerBforartists** [comment] 2023-06-27 16:16
Did a quick test in Blender, and added the new button to a panel in the sidebar. And in Blender this button works flawless. 

Means our code differs somewhere from the Blender code. Which would be the first thing to check.

![quicktest](https://github.com/Bforartists/Bforartists/assets/13919702/50d61ee1-2c18-4764-be75-c8234c798bb9)

**Comment by ReinerBforartists** [comment] 2023-06-27 16:23
The file that you investigated, wm_window.c, is equal to Blender. So most probably not the cause. But i spotted a few differences in wm_files.cc already. Something always slips through ...

I suggest to check the whole content of source\blender\windowmanager\intern for unwanted differences.

![differences](https://github.com/Bforartists/Bforartists/assets/13919702/e42eab49-5f47-46de-8304-823d718e05c1)

**Comment by iyadahmed** [comment] 2023-06-27 20:46
Blender BUG ^^
https://projects.blender.org/blender/blender/issues/109422

**Comment by Draise14** [comment] 2023-06-28 02:36
Damn, a Blender bug. I couldn't reproduce in Windows, as the person commented, but if this is the cause for our issue on windows.. let's hope they fix it ASAP, or that you can!!! 

I'm doing another file comparison walk through one by one too, with meld.

**Comment by ReinerBforartists** [comment] 2023-06-29 15:51
So expect a fix in two or three years \o/

**Comment by Draise14** [comment] 2023-06-29 19:37
A fix has been found, rudimentarily. Let's see if they commit to master soon.

**Comment by iyadahmed** [comment] 2023-06-30 10:36
Fixed by https://github.com/Bforartists/Bforartists/commit/f3c131adfe6970985638698187f251b8d73fca05

**Closed by iyadahmed** 2023-06-30 10:36 UTC
Labels: 2 - bug, Blender Bug
