### ISSUE TITLE
Python error with View Alignment in adjust last operator panel 

### ISSUE THREAD

**Issue by vidu3k333** [Bforartists/Bforartists#2906] opened 2022-02-22 02:22 UTC
**Describe the bug**
When I add a Torus model, the error box with "object has no attribute 'region_3d'" appeared (screenshotted below). Whenever I adjust the object parameters the error box will also appears but my adjustments are still registered.

**Desktop (please complete the following information):**
Windows 11 Pro 21H2, with NVIDIA GTX 1050 Ti 

**Screenshots, Example Files**
![image](https://user-images.githubusercontent.com/69661650/155050723-0d85378b-82bf-4552-bfeb-f3b80970326f.png)

**Comment by ReinerBforartists** [comment] 2022-02-22 07:54
HI vidu3k33,

I can unfortunately not reproduce the error. Could you please download the latest development build, and have a look if the problem persists? It might be already fixed ...

https://www.bforartists.de/download/

**Comment by vidu3k333** [comment] 2022-02-24 21:23
Sorry for the slow follow-up.

The latest dev build also have the same problem:
![image](https://user-images.githubusercontent.com/69661650/155609462-417664d5-0b57-45d8-b6be-96a90e584978.png)

Doing the same thing in Blender has no errors.
![image](https://user-images.githubusercontent.com/69661650/155609880-6c915e73-a1f9-43ad-acad-3f955c551982.png)

This happens to the Torus model only, any other objects does not have any problems.

**Comment by ReinerBforartists** [comment] 2022-02-25 07:04
Thank you for your screenshots. And many thanks for checking.

My dilemma is still that i simply cannot reproduce the error at Windows 10 nor at Linux Ubuntu. And the code is identical for the files in the error message. I simply wonder where this error should come from. It should not happen at all.

From where do you create the torus primitive? From the toolbar? From the Add menu? Or is this from an addon? What happens if you reset to factory settings?

Another thing that you can try is to delete or to rename the Bforartists folder in 

C:\Users\YOURUSERNAME\AppData\Roaming

**Comment by ReinerBforartists** [comment] 2022-02-25 07:27
Ah, i got it reproduced. Your description did mislead me. I thought the error pops already up when you create the primitive. But it appears when you adjust the Align from the Adjust Last Operator panel.

Workaround: press F6 in the viewport. Here the switch to View works without error.

Now for the bug. I fear we run into a Blender code limit here. And i am not sure if we can fix it. Blender has the bad habit to limit tools and their settings to the editor in which they are used. Our Toolbar is not the 3D View. And so it moans that there is no 3D view to perform the settings available, which ends in the none_type error then.

That the toolbar does not work for all tools is the result of this limit. But i did not expect to run into it with the primitives. The curious part is that it works for all other primitives. But the torus object is unfortunately a bit special. It has its own very special code ...

Here how to reproduce: 
- Create torus
- Call the Adjust Last operator from the Toolbar
- Now, in the Adjust Last panel switch the Align method to View
- Error message appears. And the torus does of course not align to the view as expected.

Investigating ...

![alignview](https://user-images.githubusercontent.com/13919702/155673111-07fc89bb-f598-4f01-adf1-b7dbae987dca.jpg)

![error](https://user-images.githubusercontent.com/13919702/155673129-459eff0f-67de-4e89-a570-9236c15c9ff2.jpg)

**Comment by ReinerBforartists** [comment] 2022-02-25 07:33
Align to view does also not work with the other primitives. Here it just doesn't throw an error. Because for these primitives the code is written in C.

**Comment by ReinerBforartists** [comment] 2022-02-25 08:13
release\scripts\startup\bl_operators\add_mesh_torus.py

We could simply hide away the align dropdown box by checking if the operator was called from the 3D view. But that's unelegant. And doesn't fix the align for the other primitives.

![checkforeditor](https://user-images.githubusercontent.com/13919702/155679367-3d461c4e-4076-435c-8612-92827c4325c1.jpg)

**Comment by iyadahmed** [comment] 2022-02-25 11:42
> Align to view does also not work with the other primitives. Here it just doesn't throw an error. Because for these primitives the code is written in C. Ah. Blender. Everything is written in its own way ...
> 
> 
> 
> @iyadahmed , do you want to have a look at the dilemma? I don't even know where to start here ...

Will look at it asap

**Comment by iyadahmed** [comment] 2022-02-25 11:43
> release\scripts\startup\bl_operators\add_mesh_torus.py
> 
> 
> 
> We could simply hide away the align dropdown box by checking if the operator was called from the 3D view. But that's unelegant. And doesn't fix the align for the other primitives.
> 
> 
> 
> ![checkforeditor](https://user-images.githubusercontent.com/13919702/155679367-3d461c4e-4076-435c-8612-92827c4325c1.jpg)
> 
> 
> 
> 

This is a good idea logically, because when the operator is not called from the 3d view, which 3d view should it align too?, if there are multiple 3d views open

**Comment by ReinerBforartists** [comment] 2022-02-25 11:45
There can just be one primitive be created at one time. This is why it is so crazy design. And all other operators in the Adjust Last Operation panel works appwide ...

**Comment by vidu3k333** [comment] 2022-02-26 03:55
> Ah, i got it reproduced. Your description did mislead me. I thought the error pops already up when you create the primitive. But it appears when you adjust the Align from the Adjust Last Operator panel to View. And just when you use the adjust last operator from the toolbar.

It actually appears when I create the primitive. Here is the video proof:

https://user-images.githubusercontent.com/69661650/155827784-5f1eccf5-7633-40dd-bdd5-0e7cf878db8c.mp4

> Workaround: press F6 in the viewport. Here the switch to View works without error.

While that solved the issue when I'm adjusting parameters, the error box when I first putting in the model still worries me.

I ran in another problem while using F6 however, is it normal for the model to snap to the degrees like this? I still can fix it by using the Rotation Transform afterward but it just seems strange.

https://user-images.githubusercontent.com/69661650/155827993-173a3e90-675e-4a3b-abd4-7d7b47df79e3.mp4

.

**Comment by ReinerBforartists** [comment] 2022-02-26 08:04
It didn't let me rest, and i have meanwhile found out how to change the default. And why it throws an error for you with creating the primitive already. You managed to set the Align option to View in the preferences.

Turn it back to World, and the problem should be fixed for you.

![turnbacktoworld](https://user-images.githubusercontent.com/13919702/155835438-443deb8e-0add-4b06-90d1-77120e45c924.jpg)

**Comment by ReinerBforartists** [comment] 2022-02-26 09:59
Hmmmm. The more i think about it, the more this turns out as mission impossible. There can be multiple 3D views. With each another view alignment. So the only valid method remains to create the primitive from a 3d view, which makes this 3d view the active one. And then you can have a view alignment to this 3d view.

Well, we have made the error message not showing again. This is as close as we can get. Remains the known issue that aligning the view is not possible from the adjust last operator in the toolbar editor.

Let's add a known issue label at this task, and close it.

**Closed by ReinerBforartists** 2022-02-26 09:59 UTC
Labels: 2 - bug, 4 - needs work
