### ISSUE TITLE
blender render vs cycles render: objects differently shown

### ISSUE THREAD

**Issue by ReaderfRik** [Bforartists/Bforartists#252] opened 2018-08-08 20:10 UTC
2 objects in the same scene are each shown in a different way: nr 1 correctly rendered as wished, nr 2 simultaneously incorrect. When I switch to the other render method, nr 1 is incorrect and nr 2 correct.
I see it in the Rendered view and in the Materials view, see the 4 printscreens. Should I change some preset? Now all is still default.
![blender render in material](https://user-images.githubusercontent.com/29224963/43861647-c74dd8bc-9b57-11e8-9a0e-0a0889262389.jpg)
![blender render in rendered](https://user-images.githubusercontent.com/29224963/43861649-c783cb66-9b57-11e8-9d13-e8310d2de5f0.jpg)
![cycles render in material](https://user-images.githubusercontent.com/29224963/43861651-c7adea86-9b57-11e8-8333-3c49cfe50d15.jpg)
![cycles render in rendered](https://user-images.githubusercontent.com/29224963/43861652-c7d2ad9e-9b57-11e8-9340-1faeb1d0d4f4.jpg)

**Comment by ReinerBforartists** [comment] 2018-08-09 05:55
Hi,

This is intended behaviour. The viewport shading is different, and so it gives different results.

Viewport shading Material is meant to preview the material plus texture. It uses the viewport OpenGL renderer to render the content. It is not meant to preview the rendered result. It works within the bounds of OpenGL, and uses OpenGL shaders for that, and uses the viewport lighting. Which is not your lights in the scene.

Viewport shading Rendered renders with the chosen renderer, and gives a preview to the final rendering, including lighting and all material setups. This method uses the renderer that you choose to render the final result,  and calculates the lighting from the lights in the scene.

You cannot use Blender Internal materials for Cycles renderer and vice versa. That's why in your second image set the material is missing. And i personally would keep my fingers away from Blender Renderer anyways. This is a dying dinosaur, and will be removed with Blender 2.8.

We have by the way also a forum for such questions :) 

https://www.bforartists.de/forum

I hope this solves your problems. Closing.

Kind regards

Reiner

**Closed by ReinerBforartists** 2018-08-09 05:55 UTC

**Comment by ReaderfRik** [comment] 2018-08-09 06:32
Hi Reiner,

I'll study your quick and long answer, thanks a lot!
By the way, I thought having posted my question on the forum. Next time I
follow your link :)
Wish you success!

ReinerBforartists <notifications@github.com> schrieb am Do., 9. Aug. 2018
07:55:
