### ISSUE TITLE
Select Through patch - Can't select faces with select through

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2287] opened 2021-03-15 14:22 UTC
# Issue
![image](https://user-images.githubusercontent.com/35357409/111167727-6490b000-856f-11eb-97fb-88155d2b82d3.png)
When going into circle or box select, you can now use the Select Through mode - but you can't paint nor select multiselection of faces. 

To reproduce: with a scene where you join a cube and a sphere, invert the normals of the cube (sphere inside the cube), and then try to paint or box select faces, I can't select anything. It only works on individual selections, like click once, select one. 

# Solution
Maybe the patch didn't account for multiple selection modes? 
- Troubleshoot face mode, the patch seemed to showcase that it could, so something must be up.

**Comment by ReinerBforartists** [comment] 2021-03-15 16:48
Thanks for the observation. Well, obviously the patch has its limits. That's no bug then though. It would be a new feature request. Which is best done to Blender. But they unfortunately have abandoned this feature.

So there is little that we can do here, sorry. You could ask Iyad if he sees a chance to expand the patch. Or ask the original author. If this doesn't help, then it's a won't fix issue.

**Comment by Draise14** [comment] 2021-03-15 17:07
Ok, asked in the patch, maybe he'll answer. When @iyadahmed  is back from Holidays, I'll ask him about it also. 

**Related patch:**
[https://developer.blender.org/T73479](https://developer.blender.org/T73479)

**Active patch and UI discussion in Blender, with no conclusive code.** 
[https://developer.blender.org/T73479](https://developer.blender.org/T73479)

**Comment by ReinerBforartists** [comment] 2021-03-15 17:29
Our patch that i have applied is another one.

https://developer.blender.org/D6322

**Comment by Draise14** [comment] 2021-03-15 17:30
Fixed, my multi-clipboard system glitched there, sorry.

**Comment by ReinerBforartists** [comment] 2021-03-15 17:32
Okay :)

**Comment by ReinerBforartists** [comment] 2021-04-10 08:48
Just as a note, and because i had a closer look, the select through patch works in solid mode, and just in solid mode. It does NOT work in wireframe mode. In wireframe mode you can select through anyways.

So this has nothing to do with the select through patch. But is a completely new issue. And is best asked the Blender developers then.

I am tempted to close this issue. But i wait for your feedback here first.

**Comment by Draise14** [comment] 2021-04-10 16:55
Wait. Can you box or lassoo select faces in solid mode? I can't make it work.

**Comment by ReinerBforartists** [comment] 2021-04-10 18:02
Of course i can. That's the whole purpose of the patch. And here it works flawless :)

**Comment by Draise14** [comment] 2021-04-10 18:40
Something else must be up..

**Comment by ReinerBforartists** [comment] 2021-04-10 18:44
Time to rename the Bforartists folder in AppData\Roaming to Bforartists_old, and try with a fresh Bforartists i guess :)

**Comment by Draise14** [comment] 2021-04-10 21:52
Ok, did the factory reset - still have the same issue. 

Here is a video showing the problem: 
## [Watch on Youtube](https://youtu.be/uPaMzQotcjk)

**Comment by ReinerBforartists** [comment] 2021-04-11 07:26
Okay, now i can confirm the issue. It does not select in face mode anymore. I will have a look at it. Thanks for the video :)

**Comment by ReinerBforartists** [comment] 2021-04-11 09:44
Straight question. Shall we remove the patch again? It seems to introduce more trouble than goods ...

**Comment by ReinerBforartists** [comment] 2021-04-11 16:27
I fear this part to select faces was never working. And i have also no idea how to implement it. There is code part that deals with faces. It just doesn't work it seems.

There is a golden rule in development: don't implement what you don't understand. Plus this is a feature. And BFA doesn't develop feratures, but the UI. And this means we better remove the select through patch.

**Comment by ReinerBforartists** [comment] 2021-04-11 16:31
This issue has become obsolete. We will remove the select through patch. It makes too much trouble.

**Closed by ReinerBforartists** 2021-04-11 16:31 UTC
Labels: 2 - bug
