### ISSUE TITLE
3D View - Header - Transform has legacy operators

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3874] opened 2023-10-12 15:40 UTC
![image](https://github.com/Bforartists/Bforartists/assets/35357409/badb6f60-262d-4fda-adc2-12f3f4a4d200)

These technically are legacy, could have a legacy sub-menu per standards we use. 

Translate, Rotate, Scale

**Comment by Draise14** [comment] 2023-10-12 15:47
Probably a regression.. the space_3dview is becoming a behemoth to keep track. I'll talk with Iyad to make sure this file doesn't get merged unless spliced in with manual comparison.

**Comment by Draise14** [comment] 2023-10-12 15:48
Going through documentation for this menu, it's heavily out of date.

**Comment by ReinerBforartists** [comment] 2023-10-12 16:09
> Probably a regression.. the space_3dview is becoming a behemoth to keep track. I'll talk with Iyad to make sure this file doesn't get merged unless spliced in with manual comparison.

I told already numerous times how it works. Never merge into the python files when a conflict appears. But compare the old blender python file with the new blender python file, and then have a look in the bforartists python file to apply the difference. But not blindly of course ...

And yes, the manual is in big parts outdated. That's the price when you just fix the issues without updating the manual afterwards.

**Comment by Draise14** [comment] 2023-10-12 17:54
I wonder about the technical causes - a merge conflict happens and is detected after a merge command either from git or tortoise, so code gets merged, then conflicts highlighted in a diff compare system to then be manually resolved. The additionally step is comparing what's merging in to know exactly what's causing a conflict. 

So I guess, to know if a file is conflicted, you merge, see the conflict, revert conflicted file to original branch, then compare pulled branch with previous pulled branch to then splice in at conflict location. Yes, you've mentioned multiple times over and over. 

But eitherway, Iyad has been under a lot of stress lately, so that too might be cause for slips. Gotta resolve what we can when we can with eyes open I suppose - take it easy, and push through...

**Comment by Draise14** [comment] 2023-10-12 18:29
Aha, I think I know what could be good. Go through commit logs before hitting "Merge" so you know what you're gonna get. But that's gonna load Iyad with double work instead of tandem work...

**Comment by ReinerBforartists** [comment] 2023-10-12 18:49
No, this is not necessary. And is not only extra work but super confusing and not helpful at all.

The way is, you do the merge, and write these conflicts down. And then you start with fixing the C files.

Then you compare the old and new Blender python files for the python trouble makers. And then you can apply the changes/differences to the Bforartists python file. And when you keep your eyes open then you will quickly notice if it is a one liner or something more complicated.

In the first case simply copy over the one liner. In the latter case make a issue. Don't even try to solve everything while the merge.

Then make Bforartists compile without errors. Including a quick look into the console. 

And THEN comes the log. Which is super important. As you now find out the hard way. You better catch as much as possible. And all i can do is to point to it again and again ...

By the way, have you done the log for this week already? :)

**Comment by Draise14** [comment] 2023-10-12 20:39
Going through it at the moment, but I need lunch, will continue after.

**Comment by iyadahmed** [comment] 2023-10-12 21:11
> Aha, I think I know what could be good. Go through Blender commit logs before hitting "Merge" so you know what you're gonna get. But that's gonna load Iyad with double work instead of tandem work... 

For merging the space_view3d i look at file history of the blender one so I apply the new changes manually ^^, there's a possibility things slipped somehow but I do use the commit log method, but actually yes the problem is some things don't show in conflicts

What I did for the file is resolve all conflicts by keeping bfa code, 

The I check Blender commit log and I apply the changes manually

So yes the slips must have not showed as conflicts, lesson learned I have to not do any sort of merge for space_view3d.py and do it manually all the way

**Comment by ReinerBforartists** [comment] 2023-10-13 06:13
>The I check Blender commit log and I apply the changes manually

This step is nice to have for making an issue in case you get stuck, but should not be necessary in the first place. You already get a list of conflict files when you merge. And you have a backup of the Blender repository before the merge. 

Let's say in space_view3d.py we have a conflict.

What i personally then do now is to open the space_view3d.py Blender file in meld and compare it with its older version. And have a look where they differ. This is why keeping the Blender repository before the merge is so important.

And then i open the Bforartists files and try to apply these differences to our code. The class name will already give you a hint where the trouble is. space_view3d.py is mainly menus. As told, in case it's a one liner, a new operator for example, simply copy over. And when it's something more complicated, make an issue. And then you can also have a quick look into the log if you can find the corresponding commit, and link it in the issue.

**Comment by ReinerBforartists** [comment] 2023-10-22 08:50
This is a bigger operation. The move rotate scale operators shows in any transform menu. Not just in pose mode.

![transform](https://github.com/Bforartists/Bforartists/assets/13919702/9ce9c69f-50a9-4e71-8821-03c68e4c129d)

**Comment by Draise14** [comment] 2023-11-05 19:47
This is much bigger, these are shown in the "Base" area of the transform menu for the 3D View - meaning it also shows in Curves and Curve edit mode and others. Will rename.

**Comment by Draise14** [comment] 2023-11-05 21:16
Found the code for this, so will comment out to make sure it's out.

**Comment by Draise14** [comment] 2023-11-06 01:12
Redundency, no need for documentation. Fixed in relevant areas now.

**Comment by Draise14** [comment] 2023-11-06 01:12
Commit to master

**Comment by ReinerBforartists** [comment] 2023-11-06 08:45
Wasn't the job to also add it to a legacy menu then? :)

**Comment by Draise14** [comment] 2023-11-06 09:05
Already there under the navigation legacy header entries.

**Comment by ReinerBforartists** [comment] 2023-11-06 09:11
Still compiling here ^^

**Comment by Draise14** [comment] 2023-11-06 09:29
Already exists under Header>Navi>Legacy

We could move those into the base transforms if you'd like.

**Comment by ReinerBforartists** [comment] 2023-11-06 09:41
Ah, now i see what you mean. We have them in the navi menu. KK, let's close it again ^^

**Closed by ReinerBforartists** 2023-11-06 09:41 UTC
Labels: 0 - task, 4 - needs work
