### ISSUE TITLE
Properties Editor - Create a toggle to show/hide the "removed" Tools Tab

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2192] opened 2021-01-23 01:45 UTC
# Issue
We have some users need and search for the tools tab in the property shelf, something we have hidden on purpose due to redundency and also being broken, since it is connected to the 3D view but not related to any other active tool... which makes it pretty broken. He has mentioned it before, and I have tried to debate, but it seems there still isn't a clear solution here. 

The key issue is.. that it sometimes shows, then it doesn't. Maybe there is a code regression. 
And.. that it maybe should be a toggle, optional. 
Also, some addons only add/work from this panel, and not from the property shelf. 

![image](https://user-images.githubusercontent.com/35357409/105564638-14c10580-5cf1-11eb-8a5c-334f1b1d8a9f.png)
![image](https://user-images.githubusercontent.com/35357409/105564639-168ac900-5cf1-11eb-8956-b3e2032dd08f.png)
![image](https://user-images.githubusercontent.com/35357409/105564687-46d26780-5cf1-11eb-99d6-480df08b9f43.png)

Relevant issues:
#1411
#1278

# Feature Request
Add a toggle into the Property Editor right click menu to toggle this tab - to show/hide. 
Keep it default to hidden.

**Comment by ReinerBforartists** [comment] 2021-01-23 07:58
It should not show since the menu item is disabled. Please give me a way to reproduce it. Then i can have a look at it.

**Comment by Draise14** [comment] 2021-01-23 15:54
Hmm... Apparently...
1. save blend with a layout with tools tab open in Blender. 
2. Turn on Load UI in Bforartistsand load the blend
3. You will see the panel.

I have to confirm which version though, I thought we fixed this. Let me ask. And I'll try reproduce today. 

The user I think would like to have the option to toggle this disabled tab.

**Comment by ReinerBforartists** [comment] 2021-01-23 16:45
Just tested. The load UI method is not working here. I have saved a blend file, and loaded it with load UI ticked. And the tab is not showing.

As told in the closed issue, we won't resurrect this zombie here. Two locations in the UI to adjust the settings is more than enough.

**Comment by ReinerBforartists** [comment] 2021-03-03 16:54
Let's have a last look here if we can catch the baddie.

**Comment by ReinerBforartists** [comment] 2021-03-03 17:03
I was able to reproduce the problem. The panel content is showing as you describe. Save in Blender with tools tab open, and load the scene in Bforartists then with Load UI ticked. And then the properties editor shows the content of the hidden tools tab. There is no tools tab though in the tabs available. And when you click at a in the properties editor, then this ghost content vanishes. 

There is nothing that i could do here. This is tied to the read / write code. I guess we have yet another known issue.

So as sorry as i am, closing.

**Closed by ReinerBforartists** 2021-03-03 17:03 UTC
Labels: 0 - task

**Comment by Draise14** [comment] 2021-03-03 20:52
Valid enough!
