### ISSUE TITLE
Node Editors - Node labels panel missing till you run the ui relevant script

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1807] opened 2020-09-05 04:57 UTC
# Issue
![bforartists_BxtbStg8j0](https://user-images.githubusercontent.com/35357409/92297955-0f157f80-ef0a-11ea-9e1c-564e2aac334c.png)
When I start doing compositing, and want to do labeling on the nodes, the menu to do it under Item tab is hidden. I had a look at the code and ran the script from the color area (Edit Source) and it shows up after running it, but on default it's not there. I can't seem to get it there on the factory default also. 

It seems something is not registering that panel correctly. 

The color panel is also a sub panel for some reason in there... 

# Task
Check and see why the first labels panel is not showing up in the UI on first use and fix.

**Comment by Draise14** [comment] 2020-09-05 05:06
File:
space_node.py line 554 might have something to do with it, though I compared it to Blenders, not a lot is different..?

**Comment by ReinerBforartists** [comment] 2020-09-05 06:30
I have no idea what is going on here. Have you tried to use the Blender file? When the problem still exists then we need to look elsewhere ...

**Comment by ReinerBforartists** [comment] 2020-09-05 06:58
I cannot reproduce it. The labels shows just fine here. 

I stumbled across another quirk though. The background image shows just half XD

![nowaytoreproduce](https://user-images.githubusercontent.com/13919702/92299804-fa5ed900-ef55-11ea-8609-765d8ef69f37.jpg)

**Comment by ReinerBforartists** [comment] 2020-09-05 07:03
Ah, split viewer node had wrong settings. Must have touched the factor slider.

**Comment by ReinerBforartists** [comment] 2020-10-28 12:23
Hm, looking at your screenshot, can it be that you have a group selected? The label just shows for single nodes from what i know.

**Comment by ReinerBforartists** [comment] 2020-10-30 08:28
Searched through the code. Nothing obvious found. And i can still not reproduce it. So closing.

**Closed by ReinerBforartists** 2020-10-30 08:28 UTC
Labels: 2 - bug
