### ISSUE TITLE
Outliner - Collection Colours not showing in Blender File mode

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2927] opened 2022-03-16 22:44 UTC
![bforartists_J4J8ruq0Ur](https://user-images.githubusercontent.com/35357409/158703380-fcab0192-a5c4-440f-924c-c5c16549e705.png)

Right now, in the outliner in the Blender File mode, the colours don't show on collection. 

In Blender 3.2 this is not broken and shows colours correctly. 
![image](https://user-images.githubusercontent.com/35357409/158703516-0bed6a13-566f-4421-9dee-2e78792e56b1.png)

`Version 3.1.0` and `devbuild-05-03-2022`

**Comment by ReinerBforartists** [comment] 2022-03-17 07:30
-.-

Thanks for the report. Let's have a look if we can catch this.

**Comment by ReinerBforartists** [comment] 2022-03-17 08:58
Related https://github.com/Bforartists/Bforartists/issues/1835

But i could swear we had this case here before too ...

**Comment by ReinerBforartists** [comment] 2022-03-17 09:07
Ah, it's just in Blender file mode. And i think the cause is that we use another icon here. It's not the same group icon.

Investigating ...

![different](https://user-images.githubusercontent.com/13919702/158775451-432aa050-4b6b-4b1f-8608-bfabbe1d8421.jpg)

**Comment by ReinerBforartists** [comment] 2022-03-17 09:20
Fixed in master

![fixed](https://user-images.githubusercontent.com/13919702/158777755-48e6ae9e-8b9a-42e7-ad57-9db9a2712d55.jpg)

**Closed by ReinerBforartists** 2022-03-17 09:20 UTC
Labels: 2 - bug
