### ISSUE TITLE
Keymap - Experimental and Full Bforartist map - GP Delete conflict

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#237] opened 2018-07-13 00:43 UTC
![bforartists_2018-07-12_19-39-50](https://user-images.githubusercontent.com/35357409/42666582-9fd8c14a-860b-11e8-8b84-45a11ef97169.png)

What happens in the 3D View with the conflict from a default scene:
![bforartists_2018-07-12_19-42-37](https://user-images.githubusercontent.com/35357409/42666599-bd43e3b8-860b-11e8-9183-1b18684eae87.png)

In Object mode in the 3D View, the Delete key has a conflict with an entry in the Grease Pencil. It also is a double entry already in another mode (Edit GP pencil) - so one should be removed. 

It should be removed from the Grease Pencil global area. 

**Keymaps:**
- Experimental
- Bforartists Full

**Comment by ReinerBforartists** [comment] 2018-07-13 08:29
What's the keys in the Blender keymap here?

**Comment by ReinerBforartists** [comment] 2018-07-13 08:45
Ah, got it. Okay, now let's check how Blender deals it ...

**Comment by ReinerBforartists** [comment] 2018-07-13 08:51
We cannot remove this hotkey. It is needed. 

Blender has the odd hotkey D X here. So one possible key for our keymap would be D Delete. What do you think?

**Comment by Draise14** [comment] 2018-07-13 16:40
Nice catch. Yeah, that would make more sense to not have them conflict.

**Comment by ReinerBforartists** [comment] 2018-07-13 19:05
Okay, then i'll change the hotkey tomorrow :)

**Comment by ReinerBforartists** [comment] 2018-07-14 08:00
Hm, seems that the problem is even a bit bigger. The shot is from the standard keymap, which should not have this key at all
![allactiveframes](https://user-images.githubusercontent.com/13919702/42722477-cbd8c0be-874c-11e8-8475-320b172ed58c.jpg)
 O_O

**Comment by ReinerBforartists** [comment] 2018-07-14 08:06
This is how it looks in Blender. 

What's odd here is to have the same operator with two different hotkeys here. Shift X and D X


![blenderdeleteallactive](https://user-images.githubusercontent.com/13919702/42722519-9162241a-874d-11e8-82af-9a01d8731105.jpg)

**Comment by ReinerBforartists** [comment] 2018-07-14 08:15
The Shift X key is a double entry. It has the same functionality than the D X key. But just works in Edit Strokes mode. It also has no menu entry. So let's remove it from our keymaps.

**Comment by ReinerBforartists** [comment] 2018-07-14 09:56
Fixed in master

https://github.com/Bforartists/Bforartists/commit/cb60910a0c6a2f604c16aab9fc9b5823365c15cc

**Closed by ReinerBforartists** 2018-07-14 09:56 UTC
Labels: task
