### ISSUE TITLE
Need help with bforartist flatpak

### ISSUE THREAD

**Issue by tkaczz** [Bforartists/Bforartists#279] opened 2018-09-20 07:14 UTC
I forked almost two months ago official blender flatpak repo, and changed it to build bforartist instead. In my opinion it should work, bforartist is not so different from blender. As I currently tested it, dependencies are compiling without any error but I couldn't test bforartist. I have weak spec laptop, and building whole package is taking a bit too long, so I'd be gladly pleased when someone with more powerful rig would build it and test it.

Package is based on freedesktop sdk 1.6, so more people could use it. I had to set and build inner python environment, because built one was too old (python3.5).

My repo with fork
https://github.com/tkaczz/org.bforartists.Bforartists/tree/sdk-1.6-dev

Official flatpak manual about building, testing packages.
http://docs.flatpak.org/en/latest/first-build.html#build-the-application

If any help is needed, please ask.

**Comment by ReinerBforartists** [comment] 2018-09-20 08:57
Hi tkaczz,

As you may have already notices, i am lost with Linux. So i am of no help here, sorry.

You could also post this at the Bforartists forum: https://www.bforartists.de/forum

Kind regards

Reiner

**Comment by tkaczz** [comment] 2018-09-20 12:19
> 
> 
> Hi tkaczz,
> 
> As you may have already noticed, i am lost with Linux. So i am of no help here, sorry.
> 
> You could also post this at the Bforartists forum: https://www.bforartists.de/forum
> 
> Kind regards
> 
> Reiner

Thank you, done

**Comment by ktotheoz** [comment] 2019-04-14 09:07
Did the following commands:
```
flatpak-builder --install-deps-from=flathub build-dir org.bforartists.Bforartists.json
flatpak-builder --repo=test_repo --force-clean build-dir org.bforartists.Bforartists.json
```

Receiving the following error:
```
Removing files/bin
Renaming bforartists.desktop to org.bforartists.Bforartists.desktop
Error: error while moving file $(pwd)/.flatpak-builder/rofiles/rofiles-yj7vGm/files/share/applications/bforartists.desktop: File or directory not found
```

**Comment by tkaczz** [comment] 2019-04-14 09:36
I don't have linux install on my disk, so can't work on it now. I'll try to install it later.

I almost completely forgot about that flatpak project. As I understand it builds successfully, but has problem with doing post-build things?

**Comment by ktotheoz** [comment] 2019-04-14 09:40
Exactly.

**Comment by tkaczz** [comment] 2019-04-14 09:48
Very good, most hard work is done, script just need some polishing. Can you run bforartists binary? 
http://docs.flatpak.org/en/latest/first-build.html#build-the-application -> Test the build
It should be something like `flatpak-builder --run org.bforartists.Bforartists.json /bfoartistsBinarySomehereInBin/bforartists`

I'll try to work on it later, I have to install linux distro.

**Comment by ktotheoz** [comment] 2019-04-14 11:01
Executed command: ```flatpak-builder --run org.bforartists.Bforartists.json $(pwd)/bfaBuild/files/bin/bforartists```

Resulting error:
```
Can't parse '$(pwd)/bfaBuild/files/bin/bforartists': <data>:1:1: Processing error: unexpected character `\177', expected value```

**Comment by tkaczz** [comment] 2019-04-15 09:14
Flatpak SDK has been updated and default version that should be used is 18.08 but for now I'll try to fix current things with previous SDK (1.6).

**Comment by tkaczz** [comment] 2019-04-16 11:21
Okay probably I got this. In release folder in bforartists sources there is blender.desktop file when manifests is looking for bforartists.desktop. After this change:
```
-    "rename-desktop-file": "bforartists.desktop",
-    "rename-icon": "bforartists",
+    "rename-desktop-file": "blender.desktop",
+    "rename-icon": "blender",
```
build is passing but bforartists is crashing on launch but this is another issue.

**Comment by tkaczz** [comment] 2019-10-13 08:33
I have new rig so build times are drastically lower than on my previous craptop. I'm trying to fix it by using same json manifest as folks from blender flatpak are using for blender 2.80.

Changed few things and it builds ok, dunno about binary.

https://github.com/tkaczz/org.bforartists.Bforartists/tree/task-%232
https://github.com/tkaczz/org.bforartists.Bforartists/issues/

**Comment by naetherm** [comment] 2019-10-13 11:35
Tried to reproduce:
```
git clone https://github.com/tkaczz/org.bforartists.Bforartists.git bfa_flatpak
cd bfa_flatpak; git submodule update --init --recursive
flatpak install flathub org.freedesktop.Platform//19.08 org.freedesktop.Sdk//19.08
flatpak-builder build_dir org.blender.Blender.json

```
Received the following error during the execution of libtool:
```
src/libutil/error.c:60:10: error: ‘NULL’ undeclared here (not in a function)
   60 |    { ~0, NULL } /* end of list indicator */
      |          ^~~~
src/libutil/error.c:34:1: note: ‘NULL’ is defined in header ‘<stddef.h>’; did you forget to ‘#include <stddef.h>’?
   33 | #include <GL/glu.h>
  +++ |+#include <stddef.h>
```

**Comment by tkaczz** [comment] 2019-10-13 11:48
> Tried to reproduce:
> 
> ```
> git clone https://github.com/tkaczz/org.bforartists.Bforartists.git bfa_flatpak
> cd bfa_flatpak; git submodule update --init --recursive
> flatpak install flathub org.freedesktop.Platform//19.08 org.freedesktop.Sdk//19.08
> flatpak-builder build_dir org.blender.Blender.json
> ```
> 
> Received the following error during the execution of libtool:
> 
> ```
> src/libutil/error.c:60:10: error: ‘NULL’ undeclared here (not in a function)
>    60 |    { ~0, NULL } /* end of list indicator */
>       |          ^~~~
> src/libutil/error.c:34:1: note: ‘NULL’ is defined in header ‘<stddef.h>’; did you forget to ‘#include <stddef.h>’?
>    33 | #include <GL/glu.h>
>   +++ |+#include <stddef.h>
> ```

You're not switching to task-#2 branch.

**Comment by tkaczz** [comment] 2019-10-16 13:16
Found it why it crashed. I had to change directory name from blender to bforartists as in imgur post
https://imgur.com/a/6HAMdTz

**Comment by tkaczz** [comment] 2019-10-17 07:44
Had to change one line to mv /app/share/blender to /app/share/bforartists and it works!
https://imgur.com/a/8JvqaMx

**Comment by naetherm** [comment] 2019-10-17 08:10
Will test it this weekend.

**Comment by naetherm** [comment] 2019-10-19 06:23
Tested on branch ```task-#2```. Works for me.

**Comment by tkaczz** [comment] 2019-10-19 09:05
> Tested on branch `task-#2`. Works for me.

Already merged second task branch into master. Need to fix that icon yet.

**Comment by ReinerBforartists** [comment] 2020-02-26 11:53
Is this task fixed? If so then we should close it!

**Comment by tkaczz** [comment] 2020-03-11 10:51
Well flatpak is working, but there is a little problem with icon, but I'm now focused on other things. Feel free to fork my bforartists flatpak repo.

**Comment by ReinerBforartists** [comment] 2020-03-11 11:21
Many thanks for reporting back. And for your effort. 

I have forked your repository now as suggested. I will link the flatpak at the downloads page now, and have added you to the credits page. I wish i could have been of bigger help.

Again, many thanks. Closing the case now.

**Closed by ReinerBforartists** 2020-03-11 11:21 UTC
Labels: 1- Fixed, help wanted
