### ISSUE TITLE
Addon's Like Rigify and Autorig Pro Don't Work well in B4Artist 3.0 but works okay in B3D 3.0

### ISSUE THREAD

**Issue by EAZY5D** [Bforartists/Bforartists#2827] opened 2021-12-17 14:28 UTC
**Describe the bug**
The Title Explains it all, But here we go long version iJust as you want it 😈.
    When Generating Rigify Rigs it does not display the right, but funny thing is that if I copy and paste the rig group " and my object manager looks like "A long list of Cra*" " well it displays on-screen and obviously I can't use the rig like that. But it works normally in photoshop. Also Autorig Pro Would not even install in B4Artist but it displays on the addon menu

**Desktop (please complete the following information):**
The Operating system. Windows 10, Intel Iris Pro Graphics 580.

**Screenshots, Example Files**
Anything That happens after 26sec is just extra the first 26 sec shows the real problem.

https://user-images.githubusercontent.com/55167211/146560096-524cbfac-729f-4fdf-894b-ec1ed083cbf6.mp4

**Comment by Draise14** [comment] 2021-12-17 15:11
I just tried the devbuild to try reproduce the issue with Rigify. So far, no luck. Works just like in Blender for me. 

In summery, I can't reproduce. 
1. Activate Rigify
2. Generate Meta Rig
3. Generate rig from menu
4. New rig generates without a problem, no widgets are showing, only the new rig.  
![image](https://user-images.githubusercontent.com/35357409/146565087-4d6cbd22-4423-41b6-8bcf-e70feca91076.png)

Can you try the development build to see if the issue persists? And also, try clear the user data to factory settings to see if the problem also persists. You can make a backup of the user data from the Edit/Preferences and open the user data from there to copy and paste or just rename to backup. 

Concerning Autorig Pro, what is the error? If they do support 3.0, it should work in Bforartists. You may have to open the console to see the error (under Window in header).

**Comment by ReinerBforartists** [comment] 2021-12-17 16:47
Thanks for the report.

Draise already summarized our dilemma. The problem with Rigify is not ro reproduce. And Autorig is a paid addon, which we cannot afford.

As a note or better a further idea, Bforartists 3 is already based at Blender 3.1 alpha. Which may also break things. Could you please be so kind to test the autorig addon with the newest Blender builder 3.1 alpha version?

https://builder.blender.org/download/daily/

**Comment by EAZY5D** [comment] 2021-12-19 22:47
Auto rig Pro Is broken with 3.1 Just Tried it I can't even activate it.

**Comment by EAZY5D** [comment] 2021-12-19 22:50
> 

4. it does generate without problem it's Just the ViewPort widget are not showing Just as shown in the video. I'll try the development build and give you updates.

Thank you 😶

**Comment by EAZY5D** [comment] 2021-12-19 23:44
> I just tried the devbuild to try reproduce the issue with Rigify. So far, no luck. Works just like in Blender for me.
> 
> In summery, I can't reproduce.
> 
> 1. Activate Rigify
> 2. Generate Meta Rig
> 3. Generate rig from menu
> 4. New rig generates without a problem, no widgets are showing, only the new rig.
>    ![image](https://user-images.githubusercontent.com/35357409/146565087-4d6cbd22-4423-41b6-8bcf-e70feca91076.png)
> 
> Can you try the development build to see if the issue persists? And also, try clear the user data to factory settings to see if the problem also persists. You can make a backup of the user data from the Edit/Preferences and open the user data from there to copy and paste or just rename to backup.
> 
> Concerning Autorig Pro, what is the error? If they do support 3.0, it should work in Bforartists. You may have to open the console to see the error (under Window in header).

it does generate without problem it's Just the ViewPort widget are not showing Just as shown in the video. I'll try the development build and give you updates.
Thank you 😶

**Comment by ReinerBforartists** [comment] 2021-12-20 07:08
Thanks for checking. And many thanks for your patience :)

Now i see. And i can confirm the missing widgets in the Bforartists 3 release version. It does not finish the rig. But gives no error why. I can also confirm though that it is back working in the developer version. See below. So it must have been a hiccup in the rigify addon, which gots fixed meanwhile.

For the Autorig addon, as feared, the addon is simply not ready for Blender 3.1 yet. We are always one version ahead since we rely at the Blender master. Blender developers always makes a branch for the release version, and continues with the development in the master already. Means when they have Blender 3.0 released, then the master of Blender, and so also Bforartists, is already at Blender 3.1 alpha. And sometimes this can make trouble. As we now experience with the Autorig addon.

You need to be patient here i fear. There is nothing that we can do. This is the job of the addon developer.

I will close this issue now if you don't mind. There is simply nothing left to fix for us. But don't hesitate to ask if you have further questions.

Kind regards
Reiner

![worksfine](https://user-images.githubusercontent.com/13919702/146726241-f497e406-6fe1-41e3-9dd0-5949ee8d448c.jpg)

**Closed by ReinerBforartists** 2021-12-20 07:08 UTC
Labels: Addon, Needs more information

**Comment by EAZY5D** [comment] 2021-12-22 05:03
I was just able to download v 3.1 now and it works Okay. thank you

**Comment by ReinerBforartists** [comment] 2021-12-22 07:33
Perfect :)
