### ISSUE TITLE
Radeon ProRender Activation Failure

### ISSUE THREAD

**Issue by xzendor7** [Bforartists/Bforartists#2263] opened 2021-02-25 17:59 UTC
I tried installing the the AMD Radeon Blender Pro Render and received a an error

I used the addon feature to download the zip  file which went fine
When I click the activation radio button I get a Traceback Error.

I'm using Windows 10 and the Radeon RX 570 8GB Graphics Card

**Comment by ReinerBforartists** [comment] 2021-02-25 20:05
Hi xcendor7,

Thanks for the report. Does it work with Blender? It can be one of those rare cases where we run into a hardcoded Blender path somewhere.

**Comment by ReinerBforartists** [comment] 2021-02-26 09:13
Fails at newest Blender version too. I have reported the issue to the addon developer now.

https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/issues/213

I will close this issue now since there is nothing to fix for us. To fix the addon is the responsibility of the addon developer. But i will keep an eye at the issue. And will check with Bforartists again once the issue is fixed by the developers of the addon.

Kind regards
Reiner

![blendertraceback](https://user-images.githubusercontent.com/13919702/109280243-0cda1100-781b-11eb-83cf-16b89bfd5b32.jpg)

**Closed by ReinerBforartists** 2021-02-26 09:13 UTC
Labels: 0 - task
