### ISSUE TITLE
bforartists.de "Seite wurde nicht gefunden." everywhere

### ISSUE THREAD

**Issue by HUNT3Rdotme** [Bforartists/Bforartists#4418] opened 2024-06-29 22:33 UTC
Website is chock-full of 404 errors. Landing page, features list, downloads page, wiki, gallery, release notes, get involved page, Blender comparison, tutorials, about, impressum, privacy policy -- the only part of the site that seems to be available is the forum. Even the news page "seems we can’t find what you’re looking for."

**Comment by Draise14** [comment] 2024-06-30 00:18
Can confirm. I am not at the computer till Monday unfortunately.

**Comment by Blenux** [comment] 2024-06-30 00:28
Only seems to happen when not log in, there is a bbpress update, might be causing the issue?

**Comment by ReinerBforartists** [comment] 2024-06-30 06:29
Ah the fun :D

Many thanks for the report. Let's have a look which addon makes us so much fun.

**Comment by ReinerBforartists** [comment] 2024-06-30 06:35
Something was broken in the cache. Clearing it solved the issue. However, now we have some valid links that are crossed out. No idea what could be the cause.

**Comment by ReinerBforartists** [comment] 2024-06-30 06:47
Also this riddle is solved. Broken Link Checker needed to catch up

Closing as fixed. Many thanks for listening.

**Closed by ReinerBforartists** 2024-06-30 06:47 UTC
Labels: 0 - task, Webpage
