### ISSUE TITLE
Hip compiler is missing on Windows

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2833] opened 2021-12-25 07:47 UTC
We still miss a way to compile with HIP it seems. Completely overlooked that it moans about a missing compiler. But i can't find one. 

![hipcompiler](https://user-images.githubusercontent.com/13919702/147380243-1a34dd25-b80f-44cd-98e1-741f6567c0e2.jpg)

**Comment by ReinerBforartists** [comment] 2021-12-26 07:50
There is no HIP compiler for windows available yet. Blender uses a beta binary from AMD which is not available in the public. 

We need to wait if this gets released at one point.

**Comment by Draise14** [comment] 2022-05-26 23:27
Found a repository for the C++ HIP libraries to compile. Maybe this is key?
[https://github.com/ROCm-Developer-Tools/HIP](https://github.com/ROCm-Developer-Tools/HIP)

**Comment by iyadahmed** [comment] 2022-05-27 01:18
Indeed I think this is it
I think we just need to add hipcc tp path
And install clang and have its bin foldwr in path too 

https://releases.llvm.org/download.html

I have to try this later

**Comment by ReinerBforartists** [comment] 2022-05-27 06:27
The key is that the Blender developer uses a not publically available beta version, especially made for Windows. You would need to ask the Blender developers why they hold it back. This is imho against GPL. But might be one of those grey areas since this is an external library. But they have access to it, we not.

**Comment by iyadahmed** [comment] 2022-05-27 11:38
> The key is that the Blender developer uses a not public available beta version, especially made for Windows. You would need to ask the Blender developers why they hold it back. This is imho against GPL. But might be one of those grey areas since this is an external library. But they have access to it, we not.

Not sure if they still do this, the problem is lack of docs I believe they have a task to provide docs for building with hip on windows, but we can try to figure out ourselves :)

It seems that hip on windows was out for a while

**Comment by ReinerBforartists** [comment] 2022-05-27 12:19
I would be happy when you can figure this one out :)

**Comment by iyadahmed** [comment] 2022-05-28 21:16
We can't do something now

**Comment by ReinerBforartists** [comment] 2022-05-29 06:22
As told, i see this as a breach of the GPL. But i guess there is nothing that we can do here.

**Comment by Draise14** [comment] 2022-07-19 18:34
HIP seems to compile now? It is showing up on my windows build now. Would this make this task irrelevant?

**Comment by ReinerBforartists** [comment] 2022-07-20 06:35
Don't let you fool by the hip button. You still need the windows hip compiler at your local machine. No compiler, no functionality ...

**Comment by Draise14** [comment] 2022-07-20 14:50
Ah so you need to build the binaries too for it to actually work?

**Comment by ReinerBforartists** [comment] 2022-07-20 15:44
No, but the Windows hip compiler needs to be installed. And it does not come with the libs.

**Comment by Draise14** [comment] 2022-07-27 17:29
Got in touch with someone on the inside, I now have the HIP compilers. I'll upload them to Nextcloud.

**Comment by ReinerBforartists** [comment] 2022-07-27 17:37
This is great news :)

**Comment by Draise14** [comment] 2022-07-27 18:24
**HIP libraries:**
https://cloud.bforartists.de/index.php/s/TiQxHH4S8moiTA3

**Comment by ReinerBforartists** [comment] 2022-07-27 18:29
And this goes into the lib folder?

**Comment by Draise14** [comment] 2022-07-27 18:45
Everything we need is in the zip, but basically you have to edit the Cmake to point to the `include` folder, which contains the libs for HIP. I have yet to make a build with it to confirm..

**Comment by ReinerBforartists** [comment] 2022-07-28 06:02
Ah i see, So we can put it everywhere, and adjust the path then. Thanks :)

**Comment by ReinerBforartists** [comment] 2022-07-30 06:13
To point to the include path is not enough it seems. Let's wait for the compilation to finish, and then let's have a look in the cmake file what exact file is expected to be found.

![hipincludenotenough](https://user-images.githubusercontent.com/13919702/181877322-057b0b79-dc68-4f0d-8cf4-8570a77837a8.jpg)

**Comment by ReinerBforartists** [comment] 2022-07-30 06:34
Remains as is. The only hipcc file in the zip is in /bin . But also here, compile errors. We miss something vital. So also this developer build version will come without hip.

![hipcc](https://user-images.githubusercontent.com/13919702/181878039-1d7c5dc1-f3f0-48bc-b705-d0df8cdf36da.jpg)

**Comment by ReinerBforartists** [comment] 2022-07-30 06:47
Ah gotcha. Just put the whole content into the lib folder where all the other libs resides. You don't need to point to include neither. Files then are automatically found. I cannot test for functionality though. But it compiled without moaning now.

![hip1](https://user-images.githubusercontent.com/13919702/181878450-325877af-11ff-4441-908e-465a36131372.jpg)

![hipfolder](https://user-images.githubusercontent.com/13919702/181878454-5b26fa22-9b0e-4323-a7a9-7b329dc45985.jpg)

**Comment by iyadahmed** [comment] 2022-07-30 13:09
So it didn't complain about perl?

**Comment by iyadahmed** [comment] 2022-07-30 14:33
![image](https://user-images.githubusercontent.com/25552173/181919031-038e5aa5-ed57-46e7-8e5b-8b453935e127.png)

**Comment by iyadahmed** [comment] 2022-07-30 15:20
but yes I just replaced perl in hipcc.bat with full path to perl, adding perl to path didn't work

**Comment by ReinerBforartists** [comment] 2022-07-30 15:44
Hm, nope. Here it works without modifications ^^

**Comment by iyadahmed** [comment] 2022-07-30 17:53
Ah ok maybe because Im not using visual studio

**Comment by ReinerBforartists** [comment] 2022-07-30 18:57
Very likely :)

**Comment by Draise14** [comment] 2022-08-05 17:27
![image](https://user-images.githubusercontent.com/35357409/183129613-540c5350-5b57-4ca1-8eef-13287e77eaa4.png)

Just a note to self, this is the modification to compile with something like ninja instead of MSVS, just to be explicit.

**Comment by iyadahmed** [comment] 2022-08-05 18:08
should we clone this now?

**Comment by ReinerBforartists** [comment] 2022-08-05 19:02
What do you mean with clone? I still compile with VS. And here it works flawless :)

**Comment by iyadahmed** [comment] 2022-08-05 19:06
ah typo: *close

**Comment by Draise14** [comment] 2022-08-05 19:22
We have been compiling with Ninja to save more or less 25% of the compile time. It worked with MSVS indeed.

**Comment by ReinerBforartists** [comment] 2022-08-06 05:17
Well, VS might be slower. But it is officially supported. Ninja not. And it can happen that we introduce problems in the compiled result that we are not even aware of yet. That's why i stay at the conservative side where ever possible ...

**Comment by iyadahmed** [comment] 2022-08-06 06:54
should we close the issue is what I'm asking, now that we have hip working on windows

**Comment by iyadahmed** [comment] 2022-08-06 06:55
closed by accident still waiting for reply

**Comment by ReinerBforartists** [comment] 2022-08-06 07:29
I am still unsure what you mean with clone. The original HIP compiler is in the cloud. When you need to do local changes to it to make it working with your exotic solution, then this should happen local. I need the unaltered version for the official solution.

**Comment by iyadahmed** [comment] 2022-08-06 07:54
Mm clo*s*e the issue, mark it as fixed is what I mean

**Comment by ReinerBforartists** [comment] 2022-08-06 07:57
Well the original issue not having a hip compiler is resolved. We have :)

So in this regards we can close this issue.

**Comment by iyadahmed** [comment] 2022-08-06 08:00
Agree :)

**Closed** 2022-08-06 08:00 UTC
Labels: 0 - task
