### ISSUE TITLE
Topbar - Primitives - Image category operator hidden in the general version

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4596] opened 2024-08-26 22:24 UTC
![image](https://github.com/user-attachments/assets/0168c7ae-ef81-411e-a67f-59d65157b211)

```
C:\3D_Stuff\Bforartists 4.2.1\4.3\scripts\startup\bl_ui\space_topbar_toolbar.py:872
rna_uiItemO: unknown operator 'object.load_reference_image'
```

Seems we have a missing operator here. Might be due to the migration of images to planes to internal.

**Comment by ReinerBforartists** [comment] 2024-08-30 15:41
Lemme look here

**Comment by ReinerBforartists** [comment] 2024-08-30 15:51
This is a topbar manager issue it seems. It works fine when you open the toolbar separately.

Mh, that's me out here. I have no idea how this manager is made.

![topbarmanager](https://github.com/user-attachments/assets/ea8413bf-fac3-4fca-8ea8-182bf032c4a6)

**Comment by Draise14** [comment] 2024-08-30 15:53
It is a seperate document which needs to mirror the editor one. It has a slightly different ways of drawing though. But the button code should be the same or targeted to be the same.

**Comment by Draise14** [comment] 2024-08-30 15:54
Doing an update in one won't update the other, so things may have gone out of sync.

**Comment by ReinerBforartists** [comment] 2024-08-30 15:55
It's a bit more complicated. The solution is in the tooltip of the panel. It works as designed. The content shows when you are in edit mode.

Mh, we have of course a inconsistency compared with the standalone toolbar editor here. This content shows also in object mode. Question is if you want to change it. Or if we want to leave it alone.


![topbarmanager](https://github.com/user-attachments/assets/4f3f0e9c-103e-471d-a94f-d1f11f1de423)

**Comment by ReinerBforartists** [comment] 2024-08-30 15:56
> Doing an update in one won't update the other, so things may have gone out of sync.

YIKES!

I have fixed a topbar issue today, which might not be fixed in the other editor then :D

**Comment by ReinerBforartists** [comment] 2024-08-30 16:03
Okay, yeah, it is independent that way. That's what speaks against reusing the classes. Unfortunately the two versions are not to compare. Meld goes crazy. Sad that it is so different ....

Back ontopic. Shall we hide away the content in the standalone toolbar then too? Or do we leave it alone? We don't grey out usually. But in this case it shows that the content exists, but you are in wrong mode ...

![crazy](https://github.com/user-attachments/assets/891f32ed-a60b-43ca-a040-3cdb960de833)

**Comment by Draise14** [comment] 2024-08-30 16:10
There is an open task to update the editor to mirror settings and structure if the fixed topbar... I think.

**Comment by Draise14** [comment] 2024-08-30 16:41
Would be this one:  #4142

**Comment by ReinerBforartists** [comment] 2024-08-30 16:47
Ah i see. I fear this fish is nowadays too big for me. Sorry ^^

**Comment by ReinerBforartists** [comment] 2024-08-30 17:11
For me it's a thing of power nowadays. The refactoring that this issue is about is too big for me at the moment.

**Comment by ReinerBforartists** [comment] 2024-10-19 17:48
Still not answered: 

> Back ontopic. Shall we hide away the content in the standalone toolbar then too?

But yeah, same behaviour would be great. And we hide. We do not grey out. So task is still not fully fulfilled.

**Comment by ReinerBforartists** [comment] 2024-10-20 06:24
Renamed since the original topic was never true

**Comment by ReinerBforartists** [comment] 2024-10-20 08:18
Now the topbar and toolbar acts the same. Documenting ...

**Comment by ReinerBforartists** [comment] 2024-10-20 08:33
Fixed

**Closed by ReinerBforartists** 2024-10-20 08:33 UTC
Labels: 0 - task
