### ISSUE TITLE
When a shape in added with toolbar, the "parameters" dialog box does not appear

### ISSUE THREAD

**Issue by raindropsfromsky** [Bforartists/Bforartists#1326] opened 2019-12-30 05:39 UTC
**Desktop (please complete the following information):**
Windows 10 Home, 64 bit

**Bforartists version**
Nightly version, dated 29-12-2019.

**Describe the bug**
First, delete the default cube.

Now press **SHFT+A** and select **Mesh > Cylinder**. 
A cylinder appears in the 3D Editor. 
At the same time, its **Parameters** dialog box appears at left bottom of the 3D Editor.
Depending on the context, I have to adjust the number of vertices (8, 16, 32, etc).

This is the "OK" part (same as Blender).

Now delete the cylinder.

From the toolbar, click on the **cylinder** button.
A cylinder appears. 
But its **Parameters** dialog box does NOT appear at left bottom of the 3D Editor.
Without the dialog, I cannot adjust its parameters (e.g. number of vertices). **[BUG!]**

**Desired:**
The **Parameters** dialog box must always appear, regardless of how I add a shape: Through the menu system or using the toolbar.

**Comment by ReinerBforartists** [comment] 2019-12-30 07:25
Thanks for the report. This is unfortunately by design. It's a limitation from the Blender source code. Most Operators just executes in the editor type where they are called. And the Toolbar is another editor than the 3D view.

I haven't found a way around this limit yet. And this means that there is no way to show the parameters panel in the 3D view when you add a primitive from the Toolbar. But the parameters are not lost. You have to press the Last button then.

Hm, maybe we should readd the F6 button to the keymap. Then you can call the last operation panel by hotkey too.

![last](https://user-images.githubusercontent.com/13919702/71572093-d6511b00-2add-11ea-84e0-4bf6ffda9f56.jpg)

**Comment by raindropsfromsky** [comment] 2019-12-30 09:38
Sounds good.
But why call it "last operation" so pointedly?
Precisely speaking, it is "properties/settings/parameters for the CURRENT
command".
And the CURRENT command is always the last operation only, by definition.

Thus, on the whole, it looks like labeling the obvious.
IMHO just the gear symbol is sufficient.

When it is not in effect, gray it out.
For example, after adding the cylinder, I press a key that removes my
access to the cylinder's parameters.
Then this button should be grayed out.
If it is active, then clicking on it (or pressing *F6*) should pop up the
"parameters" dialog.

**Comment by ReinerBforartists** [comment] 2019-12-30 09:46
Okay, then i will (re) add F6 for calling it.

This is the Blender term for it. Adjust last operation. Also found in the Edit menu in the top bar. We may change the one or another tool name. But this element is too common. When we change its name, then the Blender users will not know it anymore.

![last](https://user-images.githubusercontent.com/13919702/71576662-a3b11d80-2af1-11ea-9775-b7f685f377db.jpg)

**Comment by Draise14** [comment] 2019-12-30 11:28
I wonder... can you chain operators on the toolbar buttons with python? 
Like... Add cube THEN adjust Last Operation? 

Can you even do that with any kind of button or addon?

**Comment by ReinerBforartists** [comment] 2019-12-30 11:34
Not that i know of. The Blender code structure is weird and limited.

**Comment by ReinerBforartists** [comment] 2019-12-30 11:36
Postponing, the change in the keymap would conflict with the changes that i have in the toolbar branch at the moment.

**Comment by raindropsfromsky** [comment] 2019-12-30 11:51
When called with F6, the dialogue should be in fully expanded form, so that
the user does not have to click once more to expand it. He can straightaway
start adjusting the parameters.

**Comment by ReinerBforartists** [comment] 2019-12-30 13:10
Is :)

**Comment by Draise14** [comment] 2019-12-30 13:31
I did a little digging and found that you can chain operators. You just.. gotta declare the list and define the custom operator to do that from the button. 

My only wall I hit was that.. I can't seem to invoke the` bpy.ops.screen.redo_last()` operator correctly. 

![bforartists_2019-12-30_08-27-40](https://user-images.githubusercontent.com/35357409/71583882-419aed00-2ade-11ea-9ba0-da0af2a3b0a7.png)

I've attached a modified toolbar with a way to chain operators (it adds a cube and torus then tries to repeat_last, but it still holds the repeat_last operator issue. _I'm.. not versed enough in invoking these things to fix._ 
![bforartists_2019-12-30_08-29-36](https://user-images.githubusercontent.com/35357409/71583953-86268880-2ade-11ea-936a-2b026df48599.png)

[space_toolbar_chainedoperator.zip](https://github.com/Bforartists/Bforartists/files/4009870/space_toolbar_chainedoperator.zip)

My idea is.. you can run the original operator, then it should invoke the repeat_last operator from a chain so that the window always pops up after using it on operators from the toolbar.

**Comment by ReinerBforartists** [comment] 2019-12-30 14:02
Does this method call the last operator in the 3d view?

**Comment by Draise14** [comment] 2019-12-30 14:18
No, tried it in a panel button and I get the same issue. As mentioned, maybe I don't know how to call the panel operator as it might be invoked some other way. I have to investigate more...

**Comment by Draise14** [comment] 2019-12-30 15:36
![bforartists_2019-12-30_10-17-52](https://user-images.githubusercontent.com/35357409/71587929-a578e200-2aed-11ea-8093-fafabcf279e7.png)

Sigh. I can call the redo_last panel on button press, but registering the new operator only pulls that panel of that new operator, not the sub operator and its panel.

**Comment by ReinerBforartists** [comment] 2019-12-30 16:45
We don't need it at the last operator. We need it at creating a primitive, so that the Adjust Last Operation panel appears in the 3D view. But i guess you will be stuck there too.

As told, i tried before, and haven't found a working solution. But feel free to investigate. That's how you collect experience. And maybe you find a way :)

**Comment by ReinerBforartists** [comment] 2020-01-22 10:17
Fixed in master, reassigned the hotkey F6 to call the adjust last operation panel under the mouse.

![last](https://user-images.githubusercontent.com/13919702/72885700-b7bef800-3d08-11ea-9b75-678814587bb2.jpg)

**Closed by ReinerBforartists** 2020-01-22 10:17 UTC
Labels: 0 - task
