### ISSUE TITLE
Outliner - Referenced Linked Library icon is confusing. 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2523] opened 2021-06-30 16:05 UTC
#Request
![image](https://user-images.githubusercontent.com/35357409/123994079-a6186000-d992-11eb-9651-4bda60d20513.png)

The referenced library icon is a little confusing. I keep seeing it and thinking the linked library is broken. 

Can we change the referenced library icon for something a little more telling? Like a blue ghost or a chain link to show that it's a linked library in a linked library.. not a red ban line to show that it "could be broken, or is broken". 

To see these icons:
1. Make a library with linked data. 
2. Link the linked data from the library. 
3. Go to Blender File view in outliner, see the red icon.

**Comment by ReinerBforartists** [comment] 2021-06-30 19:11
This is for consistency reason and by design. The red line means off. On is without this red line. Compare it with Blender, then you know what is confusing ;)

**Comment by Draise14** [comment] 2021-07-02 20:41
Sure, I'll make a bare bones and upload next week. 

Just for more context, here is the broken library icon: 

**Broken Library Icon:**
![image](https://user-images.githubusercontent.com/35357409/124326406-ea9b2b80-db4b-11eb-82a9-6affeaff60db.png)

It's very similar to a linked linked library.

**Comment by ReinerBforartists** [comment] 2021-09-25 07:50
Even after the tenth time of dancing around this issue don't see how we could improve this icon without breaking consistency with the rest of the software. Off is the red bar. Broken is with pieces apart. There is no better way to make it clear.

Sometimes there is no better solution, sorry. Closing as won't fix.

**Comment by Draise14** [comment] 2021-09-25 14:52
My initial proposal would be this:
- File with the arrow, and a link icon, the two rings or chain. That's it. 

We use this link icon symbol to link constraints. The link symbol is a green L from one light square to another dark square. 

**Second proposal:**

- Have the same link icon but change the second orange square to the file in symbol. 
- OR change the red to green like the link green. 

![image](https://user-images.githubusercontent.com/35357409/134775554-2f13e3db-6073-49f2-b73b-86490aa8c8c7.png)

**Red** means broken, warning, remove. Link is not broken, it's not a warning, and it doesn't mean it should be fixed or removed. 

A **Green** line would means it's consistent with linking. As.. it's linked, green like the linked icons. You could just change the red line to green to be consistent with the link icons since.. it's linked data!  

Please don't close this yet, this really slows production down when it comes to working with large scenes (2-3 gigs of data or more linked in from various files). I speak from experience, and some reports of other users also being confused have reported this. It's not just me.

**Comment by ReinerBforartists** [comment] 2021-09-25 15:45
A Green line does not indicate off. Green stands for ON. So with a red bar the linking is OFF. For deactivated. That's what the red bar stands for. Delete is a red cross.

![off](https://user-images.githubusercontent.com/13919702/134777392-3bec6a9e-7e5b-4d8e-83d2-33481c64745c.png)

**Comment by Draise14** [comment] 2021-09-25 16:00
But a referenced library is not OFF at all, it's is ON, linked.. it's working, it's a linked linked library. This is why it's confusing.

**Comment by ReinerBforartists** [comment] 2021-09-25 16:02
Off is off. So what do you mean then? Didn't you want to provide a example data set?

**Comment by Draise14** [comment] 2021-09-25 16:10
Here is the sample file:
[https://drive.google.com/file/d/1jFb2wJ6LxR1O6fLMSKDx1hb0WNeDvcRi/view?usp=sharing](https://drive.google.com/file/d/1jFb2wJ6LxR1O6fLMSKDx1hb0WNeDvcRi/view?usp=sharing)

Here is what it contains in the `linked linked.blend`:
![image](https://user-images.githubusercontent.com/35357409/134778082-07853989-f851-4270-931d-d9c86fc3d942.png)

1. A source file (cube in a collection)
2. A linked file (collection linked into another collection as instance)
3. A linked linked file (the collection with the linked instance now linked in)

Go to Blender File in the outliner, you can see the linked linked data is showing red when it is in fact showing that it SHOULD be working fine, ei, green or something else. Here it's implying that it's hidden or broken or turned off, when in reality it's just referenced linked data working correctly.

**Comment by ReinerBforartists** [comment] 2021-09-25 16:15
There is no such icon to see.
![nosuchicon](https://user-images.githubusercontent.com/13919702/134778312-247aef25-95fe-44c2-a691-cf8a5229d78a.jpg)

**Comment by ReinerBforartists** [comment] 2021-09-25 16:17
There is such an icon to see O_O

Let's have a look in Blender

![tosee](https://user-images.githubusercontent.com/13919702/134778360-769168d5-d757-482e-af84-5d3f604eddd1.jpg)

**Comment by ReinerBforartists** [comment] 2021-09-25 16:22
In Blender the link icon is greyed out. Inactive. This means OFF. 

You really want me to turn an OFF icon to ON?


![blender](https://user-images.githubusercontent.com/13919702/134778535-7798b798-ea75-4840-8b3f-db8dba7c09cb.jpg)

**Comment by Draise14** [comment] 2021-09-25 16:35
It's ghosted, not off. I think this is what is implied with Blender, but I also don't think it's a good UX. Blender does it also wrong. 

UX must come first. When you work, you want to know what library is referenced. Seeing something off is telling you a misdirection, that the library is either off or broken.. when in reality it's in the scene, on, working, referenced. The icon needs to show the UX that it's referenced. Regardless what Blender says - the UX of the iconography needs to be clear. 

Add a Ghost icon, dim the linked library icon like blender, add green link with the boxes, anything other than red. It's not off at all. 

It would be a misdirection to the user if it remains "off", and believe me, it has caused many many headaches when working with referenced linked data that I had to eventually just localize and link once on a project 280 gigs large, and this was only for 2 minutes of animation...

**Comment by Draise14** [comment] 2021-09-25 16:44
The icons should be **"Referenced Linked Data"**. Meaning.. it should imply it's linked, ok, use the linked file symbol, and that it should be referenced.. so anything that symbolizes that it's referenced and linked will be useful (chain, arrow, green, ghost, etc). Not off.

**Comment by ReinerBforartists** [comment] 2021-09-25 16:50
Hmmmm :D

I haven't worked with linked data at this level yet. So i don't really have much to add. But when Blender delivers the icon as off, then i make a red bar across it :)

I will have a second look at it when i find the time for.

**Comment by Draise14** [comment] 2021-09-25 16:54
Thank you Reiner. You're awesome. Yeah.. it was one of those little things that caused a lot of broken data and messes when under pressure. Thanks for listening.

**Comment by ReinerBforartists** [comment] 2021-09-25 16:57
You just need to feed me with enough data ;)

The icon is called library data indirect. And then it is clear that we need another icon. It is not off. The state of the original icon did mislead me when shaping the icon.

![indirect](https://user-images.githubusercontent.com/13919702/134779865-b546ac57-55c6-4605-8c1d-46fa11448853.jpg)

**Comment by Draise14** [comment] 2021-10-15 16:02
Thanks for sharing the screen captures of these updates, and for also doing this task!!! Man, will make life that much easier. It's all in the details.

**Comment by ReinerBforartists** [comment] 2022-04-03 09:05
I have to reopen this task since the Blender devs have changed this to a single icon. And simply grey it out. Super hard to read. Dunno what they think here. That you make a screenshot every time you work with this and check the greyscale value?

Maybe we can revert this change, and readd the now removed icon with our green arrow. Not sure though. First we have to find it in the list of commits.


![icon](https://user-images.githubusercontent.com/13919702/161420232-faa9a6cd-30aa-4297-bcb5-4b28be3c6beb.jpg)

**Comment by ReinerBforartists** [comment] 2022-04-03 09:22
Ah, i will make a new task for this, and link to the old task.

**Closed** 2022-04-03 09:26 UTC
Labels: Feature request, 0 - task, 1- Fixed
