### ISSUE TITLE
Can't move stencil texture in Sculpt mode.

### ISSUE THREAD

**Issue by CyberFoxHax** [Bforartists/Bforartists#1329] opened 2020-01-10 07:46 UTC
Stencil texture can't be moved around in sculpt mode using Bforartists keybindings.

Observations:
Industry Standard: You can move the stencil texture with right click alone.
Bforartists: Ctrl+Shift+Right Drag > Lasso selection

**Comment by ReinerBforartists** [comment] 2020-01-10 08:41
Confirmed. Transform for stencil maps in sculpt mode does not work. This needs a fix.

We could have a look if we can use the industry compatible keybinding in Bforartists here.

**Comment by CyberFoxHax** [comment] 2020-01-11 01:43
How about let the stencil texture capture the rmb event?

**Comment by ReinerBforartists** [comment] 2020-01-11 08:22
Then you can't navigate anymore.

**Comment by CyberFoxHax** [comment] 2020-01-11 08:39
only while mouse is over the texture

**Comment by ReinerBforartists** [comment] 2020-01-11 08:50
That's not how it works, sorry. You can either have the hotkey to move the texture, or to have it to navigate :)

**Comment by ReinerBforartists** [comment] 2020-01-22 09:27
Hm, the hotkeys are there. Interesting O_O

![hotkeysexists](https://user-images.githubusercontent.com/13919702/72881859-da99de00-3d01-11ea-98d0-b6577e95422e.jpg)

**Comment by ReinerBforartists** [comment] 2020-01-22 09:38
Works as intended now. Main task has magically become invalid. Nice ^^

We could switch the controls between move primary and secondary stencil texture. But that would be another task then.

What remains is the lasso select hotkey. But this one is not so easy to remove. Global thing. However, it's inconsistent to have shift ctrl right mouse in two of three modes, and the third mode is with alt then. Yet another task to fix.

The best solution however would be to create stencil brush controls buttons in the tool shelf.

Creating a few tasks now. And closing this one as invalid.

**Closed** 2020-01-22 09:39 UTC
Labels: 2 - bug, 8 - invalid
