### ISSUE TITLE
Website - Can't log in to forums

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2912] opened 2022-03-01 14:06 UTC
I currently can't seem to log into the website. I have tried from phone and desktop, with little or no success. Not sure what is up. 

I got one cookie issue, but then allowed cookies - and it repeats the process : log in, success to refresh, then the website is not logged in.

Tested on Chrome/Firefox and Android Firefox

**Comment by ReinerBforartists** [comment] 2022-03-01 16:55
I have no idea what is going on here. Have i told before that i hate Wordpress? ^^

**Comment by ReinerBforartists** [comment] 2022-03-01 17:05
Refresh the browser with ctrl + f5 , then please try again.

I had a new optimization plugin installed. Fingers crossed that this was the cause. I can at least now log in with my dummy account again.

**Comment by Draise14** [comment] 2022-03-01 17:31
Ok, seems to be working now. Testing on phone. Cool. Looks like it's working.

**Comment by Draise14** [comment] 2022-03-01 17:49
Wait, this is tricky. Website logs in, then I switch to the forum, and I'm logged out.

**Comment by ReinerBforartists** [comment] 2022-03-01 17:56
-.-

Next step: abandon the webpage ...

**Comment by ReinerBforartists** [comment] 2022-03-01 18:01
Just that i have asked. Have you cleared your private cache with ctrl + f5?

**Comment by ReinerBforartists** [comment] 2022-03-01 18:20
I have just cleared once again the caches. And now my dummy account is back in the forums again. It does not log out with the switch anymore. 

Please test.

**Comment by Draise14** [comment] 2022-03-01 18:41
Looks like it's working on my end. Finally can log into the forums.

**Comment by Draise14** [comment] 2022-03-01 18:41
And posted something

**Comment by ReinerBforartists** [comment] 2022-03-01 19:33
Excellent. So this quirk seems to be fixed. Phew!

Thanks for the report. Closing :)

**Comment by Draise14** [comment] 2022-03-03 11:58
Ok.. it's back again. Something changed. I can no-longer log in again.

**Comment by ReinerBforartists** [comment] 2022-03-03 14:01
Not here :/

**Comment by ReinerBforartists** [comment] 2022-03-03 14:05
Cache again. There was a plugin update yesterday. 

This means that something is still faulty. It should not be required to manually delete the cache. But for now it is back working.

**Comment by ReinerBforartists** [comment] 2022-03-03 16:46
Now it's again not working. Great.

**Comment by ReinerBforartists** [comment] 2022-03-03 17:01
It's not the cache. I have turned off any caching for now.

**Comment by ReinerBforartists** [comment] 2022-03-03 20:00
Found a missing option so far and clicked at some "repair" options. Currently the dummy account is working again. I will recheck tomorrow.

**Comment by ReinerBforartists** [comment] 2022-03-04 08:28
I don't get it catched :/
Well, the page is not completely broken. You can log in to the forum. This means you can post at it. But not so sure about the PM System. And the main page shows me logged out, except i am logged in as an admin. And that's not how it should be. 

I will have a look to roll back to a previous server state next week. We will loose the one or another posting by that. But i fear this is simply an incompatibility with one of the addons and the current Wordpress version. And i have this much addons installed and this much settings that it is virtually impossible to find the cause. Especially since there is no working error logging.

I fear we have to redo the page at one point.

**Comment by ReinerBforartists** [comment] 2022-03-04 10:32
Blasphemic question, do we really need a forum and a image gallery with user login? The page would be immediately this much faster too ...

**Comment by ReinerBforartists** [comment] 2022-03-04 10:39
This is so crazy. At the moment it works ...

**Comment by ReinerBforartists** [comment] 2022-03-06 07:31
Hm. I had just a pm from a normal user. My dummy account is a developer account. Possible that this is the culprit. To have a Developer account is managed by a third party addon. I will investigate into it before i reset the server.

**Comment by ReinerBforartists** [comment] 2022-03-06 17:43
Rolled back for a month now. Let's have a look if the user problem persists.

**Comment by ReinerBforartists** [comment] 2022-03-07 08:59
Looking good so far. Fingers crossed ...

**Comment by ReinerBforartists** [comment] 2022-03-07 09:07
368dw5s7terASDFASDF!!!!


![shotdown](https://user-images.githubusercontent.com/13919702/157000981-6b6d7581-4b19-4158-9c7c-bca3c6b31cb0.jpg)

**Comment by ReinerBforartists** [comment] 2022-03-07 09:09
Crazy enough, when i surf to the main page, and come back, then the theming is back working again. Ah, cache ...

**Comment by ReinerBforartists** [comment] 2022-03-07 09:30
Now what's left is to wait a bit if some of the problems comes back. Please test if the page works again as intended.

**Comment by ReinerBforartists** [comment] 2022-03-08 10:35
Closing this task as resolved. Login should work again.

The shot down layout is another issue, and i work at it right now.

**Closed by ReinerBforartists** 2022-03-08 10:35 UTC
Labels: 2 - bug, 4 - needs work, Webpage
