### ISSUE TITLE
The Addon toolbar does not identify the Addons provided in its tabs. Its GUI also does not show the Addon name.

### ISSUE THREAD

**Issue by raindropsfromsky** [Bforartists/Bforartists#2531] opened 2021-07-03 15:51 UTC
**Describe the bug**
When multiple addons are installed, their tabs do not show meaningful labels. It is impossible to tell which Addons are available in the strip.
![image](https://user-images.githubusercontent.com/9047168/124359608-51e7d700-dc43-11eb-928a-8f5ed8791337.png)

Some of the tabs are totally blank. Some of them contain only one or two letters from which you cannot guess the name of the Addon.

Secondly, when we select a particular Addon, its GUI pops up at the left.
But the name of the Addon does not appear at the top of the GUI!
For example, which Addon are we using here? 
(Rather, what is this Addon supposed to do??)
![image](https://user-images.githubusercontent.com/9047168/124359858-5c56a080-dc44-11eb-8e0b-cef472e0a37b.png)

Thus we remain totally unaware of which Addon we are using! 

**Suggested solution:** 

1. Provide a 2-line tooltip, which shows 
(a) 1st line - name of the Addon and 
(b) 2nd line - its main functionality 

2. Always provide the name of the Addon at the top of its GUI. <br> Use a larger font and different background to distinguish this as the Addon's name label.

**Desktop (please complete the following information):**
Windows 10, Home 64 bit. 

**Screenshots, Example Files**
See above

**Comment by ReinerBforartists** [comment] 2021-07-03 15:55
This is a Blender feature, not a bug. And there is unfortunately nothing that we can change here, since a change would break addon compatibility. Sorry ^^

So as sorry as i am, i have to close this request. 

Mh, there is an addon around that helps with the issue. https://www.youtube.com/watch?v=4DwMwso9MR8

**Closed by ReinerBforartists** 2021-07-03 15:55 UTC
