### ISSUE TITLE
Icons: lock and unlock for transforms has bad iconology

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#825] opened 2019-04-25 21:42 UTC
## Issue
The lock icon is... bonkers right now. When unlocked, it looks locked. When locked, it shows a random box with a face on it that doesn't make sense. Also, the iconology is mostly lineart, no colour, no siluette. 

**Screenshots, Example Files**
![bforartists_2019-04-25_16-36-47](https://user-images.githubusercontent.com/35357409/56770087-b613d400-6778-11e9-94c9-739e77288c0b.png)

## Solution
Update and change the iconology, either to a simple lock that opens and closes and highlights the state by colour.

**Comment by ReinerBforartists** [comment] 2019-04-26 05:28
Ah, have they changed the icons again? -.-

**Comment by ReinerBforartists** [comment] 2019-04-26 06:55
Closing as duplicate of

Grease Pencil object - Tools tab - Brush Panel - Wrong icon to create new brush #821

**Comment by ReinerBforartists** [comment] 2019-04-26 07:15
Is own task, so reopeing.

**Comment by ReinerBforartists** [comment] 2019-04-26 07:28
This one is also a bit longer around already.

**Comment by ReinerBforartists** [comment] 2019-04-26 07:56
Fixed in master

![lockfixed](https://user-images.githubusercontent.com/13919702/56792304-937dcb80-6809-11e9-8ba7-e22c7f057454.jpg)

**Closed** 2019-04-26 07:56 UTC
Labels: 2 - bug
