### ISSUE TITLE
Materials Library VX error when Preview and Apply

### ISSUE THREAD

**Issue by SuperUserNameMan** [Bforartists/Bforartists#2595] opened 2021-08-06 12:02 UTC
**Describe the bug**
Hello,

I'm following your youtube tutorial ["Bforartists 2 Quickstart material two materials at one mesh"](https://www.youtube.com/watch?v=cCSMKuI8ZdY).

At ~30 seconds, you show how to use the Material Library VX to create a new "Aluminium Polish" material for the legs of the table.

I've done like you shown, but when I click "Preview" on the Materiel Library VX, I get an error, and the dummy-sphere of the Materials Library VX box remains all white. (edit : also the RGB node does not appears into the nodes-graph).
Clicking "Apply" also gives an error.

````
bpy.ops.object.editmode_toggle()
bpy.ops.object.editmode_toggle()
bpy.context.space_data.context = 'MATERIAL'
bpy.context.scene.matlib.mat_index = 7
Python: Traceback (most recent call last):
  File "/opt/bforartists/3.0/scripts/addons/materials_library_vx/__init__.py", line 962, in invoke
    return self.execute(context)
  File "/opt/bforartists/3.0/scripts/addons/materials_library_vx/__init__.py", line 1028, in execute
    success = matlib.apply(context, True)
  File "/opt/bforartists/3.0/scripts/addons/materials_library_vx/__init__.py", line 576, in apply
    self.get_material(name, linked)
  File "/opt/bforartists/3.0/scripts/addons/materials_library_vx/__init__.py", line 502, in get_material
    with bpy.data.libraries.load(self.current_library.path, link, False) as (data_from, data_to):
TypeError: load() takes exactly 1 positional argument (3 given)

location: <unknown location>:-1

````

**Desktop (please complete the following information):**
LinuxMint 20.2 (Ubuntu Focal 20.04).
Bformartists 2.9.3 installed from the `.deb` you provided.
GPU : 
````
OpenGL vendor string: AMD
OpenGL renderer string: AMD KABINI (DRM 2.50.0, 5.4.0-80-generic, LLVM 12.0.0)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 21.0.3
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
````

**Screenshots, Example Files**
![image](https://user-images.githubusercontent.com/9801802/128507873-df881a04-7990-4bf7-8972-01a8a389528e.png)

**Comment by iyadahmed** [comment] 2021-08-06 12:15
Hello thanks for report, working on a fix now

**Comment by SuperUserNameMan** [comment] 2021-08-06 12:31
I've just tried your fix. It works !
Thank you !

**Comment by SuperUserNameMan** [comment] 2021-08-06 12:37
I talk too fast.
"Preview" works, but when I click "Apply", I get this error :

````
Python: Traceback (most recent call last):
  File "/opt/bforartists/3.0/scripts/addons/materials_library_vx/__init__.py", line 962, in invoke
    return self.execute(context)
  File "/opt/bforartists/3.0/scripts/addons/materials_library_vx/__init__.py", line 1025, in execute
    success = matlib.apply(context)
  File "/opt/bforartists/3.0/scripts/addons/materials_library_vx/__init__.py", line 536, in apply
    if (len(objects)==1 and dummy.select):
AttributeError: 'Object' object has no attribute 'select'

location: <unknown location>:-1

````

**Comment by iyadahmed** [comment] 2021-08-06 12:41
> I talk too fast.
> 
> "Preview" works, but when I click "Apply", I get this error :
> 
> 
> 
> ````
> 
> Python: Traceback (most recent call last):
> 
>   File "/opt/bforartists/3.0/scripts/addons/materials_library_vx/__init__.py", line 962, in invoke
> 
>     return self.execute(context)
> 
>   File "/opt/bforartists/3.0/scripts/addons/materials_library_vx/__init__.py", line 1025, in execute
> 
>     success = matlib.apply(context)
> 
>   File "/opt/bforartists/3.0/scripts/addons/materials_library_vx/__init__.py", line 536, in apply
> 
>     if (len(objects)==1 and dummy.select):
> 
> AttributeError: 'Object' object has no attribute 'select'
> 
> 
> 
> location: <unknown location>:-1
> 
> 
> 
> ````

Yes this is another issue, it has to be `select_get()`
instead of `select`
Due to change in Blender API

**Comment by SuperUserNameMan** [comment] 2021-08-06 12:44
yep, with `select_get()` it works now. :-D

I'm going to finish the tutorial to see if everything is fine

**Comment by iyadahmed** [comment] 2021-08-06 12:46
> yep, with `select_get()` it works now. :-D
> 
> 
> 
> I'm going to finish the tutorial to see if everything is fine

Awesome!, let us know how it goes :D

**Comment by ReinerBforartists** [comment] 2021-08-06 15:51
What is this select_get issue? It's not in the pull request from what i can see.

**Comment by iyadahmed** [comment] 2021-08-06 15:55
> What is this select_get issue? It's not in the pull request from what i can see.

https://github.com/Bforartists/Bforartists/commit/eaf35e40a9c0793f63477f386b44d3ee700bd3b7

**Comment by ReinerBforartists** [comment] 2021-08-06 15:56
Ah, thanks, found it :)

**Comment by ReinerBforartists** [comment] 2021-08-06 16:08
https://developer.blender.org/T90483

Issue reopened. I will close it when the Blender developers have fixed the problem.

**Comment by iyadahmed** [comment] 2021-08-13 22:41
Submitted patch to blender waiting for accept

**Comment by ReinerBforartists** [comment] 2021-09-22 11:36
Not to provoke or to reproduce. Let's finally close this one. We can reopen it in case it strikes back.

**Closed by ReinerBforartists** 2021-09-22 11:36 UTC
Labels: 2 - bug, Blender Bug
