### ISSUE TITLE
Brushes Panel - Toggle custom path visibility

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2264] opened 2021-02-25 19:30 UTC
# Request
![image](https://user-images.githubusercontent.com/35357409/109206472-e31ade80-7775-11eb-9901-ed6a9d679832.png)
Add another button that you can press to shoe/hide the thumbnail path. 

### Reason
Since we might have custom thumbnails, and using them might be a standard with BFA, maybe we can hide the thumbnail path to streamline the UI a bit, yet have the ability to show/hide it.

**Comment by ReinerBforartists** [comment] 2021-02-25 20:04
Lemme think a while about this. I smell some caveats like similar UI elements and consistency. But the idea is not bad. Hide away what is not needed :)

**Comment by ReinerBforartists** [comment] 2021-02-26 07:30
This would require a new checkbox. I always struggled to add one to the C code. We could add one in our addon solution, a python property. But this would be global then.
The other possible way would be to make this a popup panel. Fuzzy to use then. It would not stay open.

**Comment by Draise14** [comment] 2021-02-27 03:20
A global toggle sounds fine by me. I think per brush would be quite annoying.

**Comment by ReinerBforartists** [comment] 2021-03-03 10:53
Hm, The button besides the image browser is already a toggle. But it does turn off the custom icon then when hiding the string. Hmmhmm.

**Comment by ReinerBforartists** [comment] 2021-03-03 10:55
I cannot proper test it since the brush image gets lost, even after saving the startup file.

@Draise14 , what is the trick here? How do you store custom brush icons?

**Comment by ReinerBforartists** [comment] 2021-03-03 10:58
This path cannot be correct. Let's have a look if i can reproduce this with Blender ...

![incorrectpath](https://user-images.githubusercontent.com/13919702/109795889-cbc96e80-7c17-11eb-828a-77cce6d9bae9.jpg)

**Comment by ReinerBforartists** [comment] 2021-03-03 11:35
Reported to Blender. Postponing until the bug is fixed. 

https://developer.blender.org/T86231

**Comment by ReinerBforartists** [comment] 2021-03-04 11:23
Bug is fixed. Waiting for the next merge before continuing here.

**Comment by ReinerBforartists** [comment] 2021-04-09 10:01
After thinking this forward and backward for more than one time, the string edit box is a strong visual hint that this icon is custom and edited. And the paths are important to know where the custom icons are located. So it is no good idea to hide this path edit box.

We can revisit this problem once Brushes - Improve thumbnails #2233 is solved. I still have my doubts here.

So for now, closing as won't fix.

**Comment by Draise14** [comment] 2021-04-09 13:39
The icon that turns on top right to reset to default after toggling to custom is not enough? I would say the double feedback to the custom icon is unnecessary.

**Comment by ReinerBforartists** [comment] 2021-04-09 15:43
I personally find the information where the icon is stored more important than possible visible noise. As told, let's revisit this issue once you manage to implement custom brushes icons.

**Comment by Draise14** [comment] 2021-04-09 17:25
Nice. I just had a look at the brushes system, it's also postponed, but I am setting up the project and studying the code.

**Comment by ReinerBforartists** [comment] 2021-04-09 19:10
You can always remove the postponed label at any time. When you start the work at it, then assign yourself, and remove it :)

**Comment by ReinerBforartists** [comment] 2021-06-14 06:54
Everytime i stumble across this issue it's a thorn in my side. I am still convinvced that this modification would be a downgrade in usability. And it is not a consistent solution.

We cannot implement buttons to hide single UI elements. Panels yes, tabs yes, checkboxes with the elements to hide right behind it, yes. Since this usually activates the element and is contextual. But not Buttons far away from the element that you want to hide just to visually hide it while it is still active. To show or hide elements should happen by context or in panels/menus. Everything else just has to end in confusion and extra work. And is not consistent with the rest of the UI anymore.

So we will not implement a extra button here just to show or hide this element.

I tried if we can get rid of the edit box part of the prop. To just show the file browser button. But this didn't work. The python operator does not open a file browser. I guess we would need to create a extra C prop. And then we could place the browse button below the custom icon button.

**Comment by ReinerBforartists** [comment] 2021-06-14 07:10
Woah, this prop isn't even to identify. This whole system goes as one gigantic spaghetti through several files.

**Comment by ReinerBforartists** [comment] 2021-06-14 07:47
Mission impossible. The string is required for the browser.

Closing this issue finally. We won't fix it. It stays as it is.

**Closed by ReinerBforartists** 2021-06-14 07:47 UTC
Labels: 0 - task

**Comment by Draise14** [comment] 2021-06-14 15:36
No problem.. It's janky anyway.
