### ISSUE TITLE
Add patch version back to product version in .exe properties details tab on Windows

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3344] opened 2022-12-07 17:41 UTC
We usually change the version info in the winblender.rc file. To my surprise i found that our info is missing. It is back at the Blender version string. May be a regression. May be intended since we now have the same versioning than Blender. But there might still be the case where we release a point release, and Blender not. So i would prefer the old way ...

release\windows\icons\winblender.rc

But before, let's have a look if this change was intended or not.

![rcfile](https://user-images.githubusercontent.com/13919702/206253660-ac0136ef-ce26-4cd7-8a4c-1bcb14c0f3fc.jpg)

**Comment by ReinerBforartists** [comment] 2022-12-07 17:46
Hmm. The difference is small. We miss one digit. I guess we can live with it as long as we don't do a own point release. But when we do then we are in trouble.

@iyadahmed do you see a way to use our bfa string here instead of the blender string?

![small](https://user-images.githubusercontent.com/13919702/206255176-8aef395b-97df-4a97-87f3-0eb3c475702b.jpg)

**Comment by iyadahmed** [comment] 2022-12-08 08:40
I will look into it asap, but i suppose this works as intended just like blender minus the blender name and blender foundation text

**Comment by iyadahmed** [comment] 2022-12-08 08:40
I did this change a while ago so that version info is automatic just like Blender makes it easier to release

**Comment by ReinerBforartists** [comment] 2022-12-08 08:47
Yes i noticed. But what if we will have a Bfa 4.0.2 release and Blender is stuck in version 4.2.1? At the moment we are tied to the Blender release numbers with your changes. Or do i overlook something?

**Comment by iyadahmed** [comment] 2022-12-08 11:39
Yes we are tied but we can set the RC_3 variable, I will make it asap

**Comment by ReinerBforartists** [comment] 2022-12-08 11:40
No hurry. It may become an issue in future releases :)

**Comment by iyadahmed** [comment] 2023-03-01 17:48
Fixed in master

**Closed by iyadahmed** 2023-03-01 17:48 UTC
Labels: 0 - task
