### ISSUE TITLE
Tweak Mode - Add Select Through toggle

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2288] opened 2021-03-15 14:34 UTC
# Request
![image](https://user-images.githubusercontent.com/35357409/111169733-3ad88880-8571-11eb-8bdb-783f1a251ab9.png)
The select through mode look useful, so far. But you can't toggle it in the tweak mode - only in other select modes. 

But you CAN have it activated in tweak mode. Current workaround is a little odd:
1. go to circle/lasso/box select
2. turn it on
3. go back to tweak select
4. use in tweak mode
5. Repeat steps to toggle off

# Task
Add the toggle also to Tweak mode

**Comment by ReinerBforartists** [comment] 2021-03-15 16:50
Interesting observation. Not sure if this couldn't be counted as unexpected behaviour :)

I have added the patch. But i am not able to continue the development at it. And a simple toggle wouldn't do it in this case i fear.

**Comment by Draise14** [comment] 2021-03-15 17:06
Hmm.. ok. I asked the dev who did this for some pointers. 

**Related patch:**
[https://developer.blender.org/T73479](https://developer.blender.org/T73479)

**Active patch and UI discussion in Blender, with no conclusive code.** 
[https://developer.blender.org/T73479](https://developer.blender.org/T73479)

**Comment by ReinerBforartists** [comment] 2021-03-15 17:27
Thanks. Let's have a look how this turns out :)

**Comment by ReinerBforartists** [comment] 2021-04-10 08:44
I had a quick look here. And you simply can't select through with the tweak tool.  Your screenshot shows a wireframe view. And here you can select through anyways, even without the select through patch. That's most probably where you get the impression that select through works. It does not.

I have even added the toggle to the tweak tool for a short moment to really test it. There is simply more involved than just adding the toggle. What is missing is the bit in view3d_select.c. Here we have defined the  select through parts for box , lasso and circle select. But not for tweak. And as told, i can just apply the patch. My C fu is simply not strong enough to continue development at this patch.

And thinking even further, for tweak it doesn't really make sense to select through. More the opposite, it would highly disturb when it would pick elements from the backside in solid view. And as told, in wireframe you are able to select through anyways.

So as sorry as i am, closing this issue. Won't fix.

![throughnotworking](https://user-images.githubusercontent.com/13919702/114264153-8e5fba00-99e9-11eb-8780-c9b632c815d2.jpg)

**Closed by ReinerBforartists** 2021-04-10 08:44 UTC
Labels: 5 - Postponed, Feature request

**Comment by Draise14** [comment] 2021-04-10 16:52
It is more for using the box or lassoo select while in tweak mode. You have to change modes to turn on/off and you are still in tweak mode when using those act once operators. It doesn't do anything for tweak mode.... Only affects box or lassoo while in tweak mode. 

The alternative is... Switch tweak mode to box, switch off, switch back to tweak mode, then I can use both box or lassoo select in tweak mode with select through on or off intentionally. A really big work around. 

I turn on in box select mode.. it caries over to tweak + act once box mode in tweak. Now try turn off without leaving tweak. Impossible.

**Comment by ReinerBforartists** [comment] 2021-04-10 18:00
I think you don't understand. As told, it does not work in tweak mode :)

**Comment by Draise14** [comment] 2021-04-10 18:02
I will have to record to show the problem. it doesn't work with the tweak operator, correct, but you can use box or lassoo when in tweak mode..the select through bleeds and there is no way to toggle.

**Comment by ReinerBforartists** [comment] 2021-04-10 18:07
This is odd. Mh, can it be that you use a custom keymap here? With the BFA map you cannot use box or lasso anymore while in tweak mode. The hotkeys activates the select tools in the toolshelf.

 It does definitely not bleed for me. I have tested it intensively.

**Comment by ReinerBforartists** [comment] 2021-04-10 18:10
Ah wait, you mean lasso select with right mouse? Yes. This one selects through then. But that's not to prevent. And has nothing to do with the tweak tool. It is the old lasso select operator. And this one has no UI entry. When you use the regular lasso select tool in the toolshelf, then you have your toggle.

**Comment by Draise14** [comment] 2021-04-11 01:21
So.. basically.. I have to remember if "select through" is on/off when in tweak mode when using lasso or box select in Tweak after having it set being in another selection mode? I have to intentionally switch back and guess so? Just.. leave the UX like that?

Watch UX issue here on [Youtube](https://youtu.be/qwN_pYpqmQc)

**Comment by ReinerBforartists** [comment] 2021-04-11 07:12
I know what you mean, i have understood what the issue is. But this is as told an issue where the old tools collide with the new tools. And the old tools does not have an UI entry where we could add the select through flag. There is no space or place to do so since they are hotkey only. When you use these old tools, then at your own danger. The new tools already have this switch.

The alternative would be to remove the select through patch again. And i won't do that.
