### ISSUE TITLE
Toolbar Editor - Oneclick Exposed button to collapse/show/hide toolbar groups

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1502] opened 2020-04-28 14:42 UTC
# Issue
A user in Discord pointed out that they love the toolbar, but it would be awesome to have the option to toggle and hide certain toolbars with a single mouseover and click for screen realestate. 

I have two toolbars on my default for maximum use of the toolbar, but it's noisy sometimes and usually, with maximum use of the toolbar exposed, all the useful things can't fit on one line requiring dragging, an awkward UX, or even two or more toolbars sometimes - this idea to collapse/hide/show menus for when you need them is actually.. a good idea. 

It would be great to be able to do this with one click:
![PureRef_2020-04-28_09-38-16](https://user-images.githubusercontent.com/35357409/80500582-fe3d7780-8933-11ea-8f73-7fd3c29d3fe0.png)

# Solution
Add a button that is able to show/hide the tool group and make all other toolbars float left.

### Notes
Is this even possible? Like a conditional in the panels that show's hides with a tickbox or button press?

**Comment by ReinerBforartists** [comment] 2020-04-28 15:45
Hmm. Should be possibe. But this would add even more buttons to the UI, and add to the noise instead of decreasing it.

**Comment by ReinerBforartists** [comment] 2020-04-28 15:48
Before i forget, please continue to post requests. But remember that the current focus is at tutorials and documentation. What i still do is to remove inconsistencies and bugs. But i will not start to add features before the manual isn't completed. And this is still a task for months. So it will take a pretty while until i tackle this issue.

**Comment by Draise14** [comment] 2020-04-28 15:49
Sure, no problem. Best to have them here before forgetting. I'll just postpone this. No problem. 

Here is another idea in line, without making clutter, add visibility/collapse controls in the submenu of that group. 
![Uploading PureRef_2020-04-28_10-48-21.png…]()

**Comment by ReinerBforartists** [comment] 2020-04-28 15:50
Yup, that's what has jumped into my mind here too immediately :)

**Comment by ReinerBforartists** [comment] 2020-11-06 11:55
Ah, not doable this way. We have collapsed menus here. That's why you see the Toolbars Primitive menu title first. The operators cannot show at this level.

![expandcollapse](https://user-images.githubusercontent.com/13919702/98363209-e35c6600-202e-11eb-8037-6fba386ce124.jpg)

The very best solution to hide a complete toolbar is to go here, and simply turn it off :

![here](https://user-images.githubusercontent.com/13919702/98363218-e8211a00-202e-11eb-8c03-5bb0534ed58f.jpg)

Which leads me to this task here to make the type menu more accessible

https://github.com/Bforartists/Bforartists/issues/1501

I will close this issue now. Single hide functionality would just crowd the menus for no reason. And we have it already with the type menu.

**Closed by ReinerBforartists** 2020-11-06 11:55 UTC
Labels: 5 - Postponed, Feature request

**Comment by Draise14** [comment] 2020-11-06 15:02
Wait wait wait.. so this is not going to be implemented? No way to quickly collapse (not toggle) a menu without digging into a menu and a sub menu? 

Not even a sub level menu? 

The old workflow is not adequate nor fast enough. Maybe if it was accessible, but even then.. it is still disconnect unless you tie a name to a group of icons - but the UX is disconnect.

**Comment by Draise14** [comment] 2020-11-06 15:06
This is just requesting one iconized entry to show/hide the icons of an already toggled tool group, and this one entry would be in the same menu as the sub-groups. There would be no overcrowding. 

Right now... to go to the head group toggles to dig through more than 7 or more entries (slow) to then read and memorize which group has what name to then quickly toggle (show/hide) it... is clunky.

**Comment by ReinerBforartists** [comment] 2020-11-06 16:46
Hm, your question makes me wonder how often you really change the content of the toolbars. It was designed to have a way to set it up, not to switch it all three seconds. You can turn off the toolbars in the type menu. There is no difference in deactivating and hiding. When it is deactivated then it is hidden. That's already the functionality that you ask for.

**Comment by Draise14** [comment] 2020-11-06 16:49
Problem is real estate. I have had a number of users and myself included have everything turned on almost, and it just does not fit on one row. I then double row it, other users do not. Instead of scrolling the toolbar, or making it a double row, we would/could just hide a group not in use and access the others that are turned on - quick focus for a workflow. 

Also, it's a useful habit from other software like from Maya.

**Comment by ReinerBforartists** [comment] 2020-11-06 16:51
I have no doubt that it bugs you. But the solution to your problem is the type menu :)

**Comment by Draise14** [comment] 2020-11-06 16:53
It's not a solution, or else this request would not exist and be asked for by a number of users...  because it takes a few seconds to use it, instead of micro seconds.

**Comment by ReinerBforartists** [comment] 2020-11-06 17:10
I respect your opinion, But again, how often do you customize your menus? When you change your menus all the time then you do it imho wrong.

I know that you want it to be like in trueSpace. Clicking at a bar besides the toolbar. But this behaviour is not to achieve with the Blender UI solution without to pay a high price in form of precious header space. There is no missing functionality, and not a single grain of speed gain to win here. Since the hide menu item would also be a sub menu that you need to reach first. It's just not as comfortable as you want it to be.

But it would add three more menu items and a ton more code to the toolbar. More stuff to document. More everything for no reason. For the same thing that you can already achieve by turning the toolbar simply off.

And that's why i have closed this task. It makes no sense from the UI design perspective really. Please respect that.

There is the other task still open where i try to make the Type menu more accessible.

**Comment by Draise14** [comment] 2020-11-06 17:35
Righteo. In the end, I thoguht it was only one entry in the sub menu on it's hamburger. Not 3. A show/collapse toggle. The mockup was just a mockup. 

Just here advocating for those who asked for it. All good. We are "be for artists" after all, but yeah. If the type menu had less clicks it might serve the same efficiency as proposed here. Good enough compromise.

**Comment by ReinerBforartists** [comment] 2020-11-06 17:36
Maybe i find other ways to improve things here. But that's another task then.
