### ISSUE TITLE
Geometry Nodes - Add - Points - New Points to Curves node

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3732] opened 2023-09-04 17:54 UTC
![bforartists_uZKfsiT5AO](https://github.com/Bforartists/Bforartists/assets/35357409/d4ab8376-c9fd-410d-8367-1d42388f8ddd)

New node, new love. Icon, Add shelf and documentation. 

<details>
<summary>Details</summary>

SHA-1: 48b08199d5dde4efb7c4d08342017a6c77df056c

* Geometry Nodes: Points to Curves node

New node to converts groups of points to curves. Groups
of points defined as `Curve Group ID` attribute. `Weight` in curve
is used for sort points in each group. Points of result curves
propagate attributes from original points. Implicit conversion
of other geometry types is not supported currently.

Pull Request: https://projects.blender.org/blender/blender/pulls/109610

</details>

**Comment by ReinerBforartists** [comment] 2023-09-07 09:29
That was it i guess. Can't make icons anymore. Unassigning.

![nomoreicons](https://github.com/Bforartists/Bforartists/assets/13919702/1febea24-13b1-49fd-bbe1-dc1eb07d3b04)

**Comment by ReinerBforartists** [comment] 2023-09-07 09:37
The new icon is in our files repository in the iconset bforartists_2, row 28 folder, POINTS_TO_CURVES

https://github.com/Bforartists/files/tree/master/iconset_bforartists_2/row%2028

**Comment by ReinerBforartists** [comment] 2023-09-07 10:27
Ah, found the cause. I have cleaned up my system and uninstalled Blender 2.90 before a few weeks. But this was the version specified in the system variables :D

Phew, you really need to take so much into account ...

Anyways, Icon creation is back working.

**Comment by ReinerBforartists** [comment] 2023-09-07 16:17
Fixed in master
![pointstocurves](https://github.com/Bforartists/Bforartists/assets/13919702/489863f8-eb7f-46c4-af0e-407d5e2678a5)

**Closed by ReinerBforartists** 2023-09-07 16:17 UTC
Labels: 0 - task
