### ISSUE TITLE
Outliner icon layout

### ISSUE THREAD

**Issue by seanr** [Bforartists/Bforartists#2200] opened 2021-01-25 15:38 UTC
**Describe the bug**
The icons to the right of the items in the list are separated by the width of a full icon, making it look like there's a missing one and causing unnecessary horizontal scrolling.

**Desktop (please complete the following information):**
Mac OS 11.0.1

**Screenshots, Example Files**
<img width="321" alt="Screen Shot 2021-01-24 at 8 58 21 PM" src="https://user-images.githubusercontent.com/199713/105727859-7fdd2880-5ef9-11eb-9dd9-bbd91134a489.png">

**Comment by seanr** [comment] 2021-01-25 15:54
Looks like stock Blender's dev build has the same issue.
<img width="321" alt="Screen Shot 2021-01-25 at 10 53 15 AM" src="https://user-images.githubusercontent.com/199713/105729820-9c7a6000-5efb-11eb-90d2-a4686a15832f.png">

That's ugly, IMO, but maybe lower priority since it's not actually broken, just bad design. ;)

**Comment by ReinerBforartists** [comment] 2021-01-25 16:49
Yes that's by design. And i don't see a way to fix this really. In the empty space at the left you will see an icon appear when you go into edit mode for example. And it would be bad when the whole content would start to jump around then. And same goes for the empty space at the right before the toggles. See it as a separator :)

I will keep the issue open. Maybe Draise and Iyad also wants to say something here.

**Comment by iyadahmed** [comment] 2021-01-26 11:03
I think I agree with Reiner, but I see some ideas here to make it a different way without the gap, we could keep it as a task I think

**Comment by ReinerBforartists** [comment] 2021-01-26 11:54
Okay :)

**Comment by seanr** [comment] 2021-04-05 00:54
I think maybe there's some confusion on this one? The edit icon ends up all the way to the left in edit mode:

<img width="416" alt="Screen Shot 2021-04-04 at 8 51 27 PM" src="https://user-images.githubusercontent.com/199713/113526325-a49fed00-9587-11eb-838a-d08c81c89058.png">

What I'm talking about is the gap between "Walls.003" and the ▽ icon to the right in that screenshot.

**Comment by ReinerBforartists** [comment] 2021-04-05 05:48
Thanks for clarification. Also this is by design. This is called whitespace, and increases the readability. When all elements are behind each other, without a gap, then it is harder to read.

Thiseffectcanbeseenwhenyouleavethegapsawaybetweenthewordsinasentence :)

**Comment by seanr** [comment] 2021-04-06 23:34
Well, as a designer, I certainly understand the importance of whitespace (or dark gray space, in this case :D), but I think the amount of space is excessive. It is actually a bit of an issue in that horizontal spaces is limited, especially with a lot of nesting - it makes you have to scroll that panel sideways more often.

**Comment by ReinerBforartists** [comment] 2021-04-07 06:00
It remains a difficult matter. I find it the right amount :)

**Comment by ReinerBforartists** [comment] 2021-06-14 09:24
Had a dive at this, but couldn't find where this is defined. I fear this is something for Iyad. If even.

**Comment by ReinerBforartists** [comment] 2021-11-12 09:35
Decision time. This issue lasts too long already. I still don't see a way for improvements. And  I am not able to do changes here anyways. So let's finally close this issue.

**Closed by ReinerBforartists** 2021-11-12 09:35 UTC
Labels: 0 - task
