### ISSUE TITLE
[macOS] Command / Control buttons not using macOS configuration

### ISSUE THREAD

**Issue by ivnnv** [Bforartists/Bforartists#2030] opened 2020-11-28 22:44 UTC
Hi,
First of all thanks for making this port, this is exactly what Blender needed to be a usable program 👍🏽 

But im experimenting an issue I dont know if its intentional, but it makes really difficult to have a fluent workflow:

On macOS I have my keyboard configured with changed modifier keys to have them mapped just as windows has for copy, paste, undo, redo etc.
![keyboard](https://user-images.githubusercontent.com/23552631/100527470-08c63500-31d3-11eb-916a-b1655d78f3f2.png)

They work fine in Blender (and any other program) and I can undo/redo doing regular ctrl+z / ctrl+shift+z
![blender](https://user-images.githubusercontent.com/23552631/100527433-c00e7c00-31d2-11eb-8289-5071940bf169.png)

But seems Bforartist doesnt respect that configuration and has its own bind?
![bforartist](https://user-images.githubusercontent.com/23552631/100527440-d74d6980-31d2-11eb-879a-0505aa7e9746.png)

Is there a way to change this mappings or is this something that needs to be fixed?

**Comment by ReinerBforartists** [comment] 2020-11-29 06:50
Hi ivnnv,

Thanks for the report. I have unfortunately no Mac to test such things. And i have honestly no idea how this is meant to work. You could try to use the Blender keymap, and see if it works there.

**Comment by ivnnv** [comment] 2020-11-29 15:31
Hi Reiner,
Yeah I have tested your suggestion and the Blender keymap works as expected for those basic shortcuts but, you know... that keymap kinda s**cks, so I have remapped all copy/paste/undo/redo shortcuts to use `command` (aka `oskey` as they seem to be named after in the attached .py file).

Heres the exported keymap file in case you want to add the modifications to the default `Bforartists` macos keymap.
[Bforartists-macOS-keymap.py.zip](https://github.com/Bforartists/Bforartists/files/5612375/Bforartists-macOs-keymap.py.zip)

**Comment by ReinerBforartists** [comment] 2020-11-29 16:48
Yes i know, i just wanted to know if the Blender keymap works as expected :)

 I will have a look at it, and then decide what to do. But no promises.

**Comment by seanr** [comment] 2020-12-02 20:39
I use the Blender keymap, just adding some extra ones here and there. If I add my own, those doesn't know anything about mapping ⌘ to ^ but I never really expected them to, TBH. I've never used the BFA keymap, since it made more sense to use the one used in basically every tutorial out there. ;)

**Comment by ReinerBforartists** [comment] 2020-12-03 08:44
I am no friend of the usual Blender hotkey tutorials that just explains what key to press. And the good ones, which explains the tools and steps instead of the shape of the hotkey letters, are also good to follow with Bforartists. But that's another chapter :)

I had a look at it now, and there is unfortunately nothing that we could do here. Just the default Blender keymaps are supported to take Mac oskey into account. It's hardcoded. Even when i would add this changes to the Bforartists keymap and get it to work, a single change in our keymap would invalidate these changes then. And the keymap would show ctrl again instead of oskey. Since reading and writing of custom keymaps doesn't support it.

It's a design mistake in the keymap manager from what i can tell. The only thing that you could do is to write a bug report to Blender, and tell them that with custom keymaps the rewrite from ctrl to oskey doesn't work on mac. But they would most probably close it immediately as works as designed.

I don't see a proper way to solve this one at our end. Sorry. The only thing that we could do is to include your keymap as an alternative for the mac users. For the price that we need to maintain two keymaps then. But that's a minor issue. What do you think?

**Comment by ReinerBforartists** [comment] 2020-12-05 11:32
Okay, will grab the keymap and add it to Bforartists.

Thanks for the report and thanks for the file. I have added you to the credits now too :)

**Closed by ReinerBforartists** 2020-12-05 11:32 UTC
Labels: 0 - task
