### ISSUE TITLE
Addon Destructive Extrude bug

### ISSUE THREAD

**Issue by emilsvfx** [Bforartists/Bforartists#107] opened 2018-03-24 05:57 UTC
This Addon don't work in BFA 9.6.0 but it works in BFA 9.5.0.

BUG
https://i.imgur.com/cuow7V8.png

https://gumroad.com/l/cQjUX
https://blenderartists.org/forum/showthread.php?409837-Destructive-Extrude-BETA

**Comment by ReinerBforartists** [comment] 2018-03-24 07:40
Hi emilsvfx,

Thanks for the report. 

The attribute error points towards a problem in the addon. They have changed some behaviours in Blender 2.79a. And Bforartists is based at Blender 2.79a. There are quite a few addons in old versions that works with Blender 2.79, and not in a. 

So to verify the problem, could you please check if the addon works in Blender 2.79a?

And could you please check if a new version of the addon exists? Maybe the problem is already solved.

The second problem is, we cannot afford to buy commercial addons for bug fixing. So chances that we can fix something here are very low. We would need the script. But in this case, as told, the error message points towards a problem in the script anyways. And that would be a job for the addon developer.

**Comment by emilsvfx** [comment] 2018-03-24 08:07
how i understand it  is in beta version. 
But i checked B 2.79a it works how it should work.

**Comment by ReinerBforartists** [comment] 2018-03-24 08:33
Thanks for testing. Could you be so kind to attach the script here that works in Blender 2.79a?

**Comment by emilsvfx** [comment] 2018-03-24 08:57
https://we.tl/bSyp41WBDd

INFO
https://gumroad.com/l/cQjUX
https://blenderartists.org/forum/showthread.php?409837-Destructive-Extrude-BETA

**Comment by ReinerBforartists** [comment] 2018-03-24 09:34
Thanks. Let's have a look what we can do.

You can by the way attach files here by simply dragging it into the text field. At least up to a size limit and with the most common formats. Images should be no problem.

**Comment by ReinerBforartists** [comment] 2018-03-24 09:45
Okay, i have bad news. The script works indeed in official Blender 2.79a. But it does not work in the Blender Master version anymore. And Bforartists is based at the Blender master. This means there is unfortunately nothing that we can do here. We cannot port Bforartists back to the Blender 2.79b release version.

As sorry as i am, closing. Can't fix.

![destructive](https://user-images.githubusercontent.com/13919702/37862622-571c10d6-2f50-11e8-9196-488daf228901.jpg)

**Closed by ReinerBforartists** 2018-03-24 09:45 UTC
Labels: Addon, bug

**Comment by ReinerBforartists** [comment] 2018-03-24 09:52
Forgot to add, please contact the addon author. He migth be able to help.

**Comment by emilsvfx** [comment] 2018-03-24 10:03
Thats ok,
How interesting, I think that the Blender Masters the same as it turns out that not. :)
Well at least that is a known that cause this issue.
