### ISSUE TITLE
Toolbar Editor - Quick Toggles only show on activated toolbar

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1996] opened 2020-11-15 23:35 UTC
# Issue 
![bforartists_tX6oHYxCu1](https://user-images.githubusercontent.com/35357409/99199637-91be8480-276e-11eb-8b11-4ec5c129a632.png)

I have loved the new updates. The new button boxes with the dropdown that can essentially activate on mouse over is a real time saver. 

I also like the quick toggles. 

My only concern is that the quick toggle activate for all the toolbars, even disactivated ones, not only the activated toolbars. 

# Request
For the quick toggles, can only the activated toolbar group show it's quick toggle when you turn them on?

**Comment by ReinerBforartists** [comment] 2020-11-16 08:14
This is by design.

I thought about your solution to implement a toggle for every single toolbar. But this leads to confusion which toggle is now for what toolbar and why it doesn't hide what i want to hide. And so i made the decision to have either none or all of them.

**Comment by ReinerBforartists** [comment] 2020-11-17 16:55
I'm closing this one now. As told, single toggles will just lead to confusion why parts of a toolbar are still there but you have pressed the toggle ...

**Closed by ReinerBforartists** 2020-11-17 16:55 UTC
Labels: Feature request

**Comment by Draise14** [comment] 2020-11-17 17:09
Wha? It's confusing having all the quick toggles all on when you have disactivated the toolbar groups that shouldnt' even be shown at all. It acts like an override to the user configuration. If I turned on the quick toggles, it's to collapse and show what the user has configured, not act as a turn on/off alternative like we already have in the toolbar drop down panels. 

It's not an alternative to tuning on/off the groups, it to collapse and show what's already activated... this was the original design request.  Right? 

If so, maybe we should update the name of the quick toggles and/or point out that it overrides the show/hide toolbar group selectors.

**Comment by ReinerBforartists** [comment] 2020-11-17 17:15
Well. I am not keen to manage regular bug reports that the toggles are broken. 

With the current way it is clear what toggle turns on and off what content. With the ability to turn off toggles it would not be clear what content depends to what toggle anymore. So best is to show either al of them or none of them.

**Comment by ReinerBforartists** [comment] 2020-11-17 17:21
To add, i think you misunderstand what the toggles are. They are not buttons to turn on or off toolbars that are already on. These toggles are nothing else than the buttons to turn on or off the eight toolbar types.

**Comment by Draise14** [comment] 2020-11-17 17:41
Yeah I get it. You have made on/off toggle alternative to the first dropdown, not a show/hide "activated" quick toggles per the previous feature requests for quick toggles. Sorry, just confused my expectation with the implementation of something similar. 

It's just confusing seeing two methods to the same in this case, if the quick toggles are on, then maybe hide the dropdown list buttons - like an alternative to the same instead of a "show/hide activated" as expected UX from other software. 

Or, instead of calling them "Quick toggles", have them as "Exposed Toolbar Toggles" or to clarify they are an alternative to the dropdown list in the tooltip.

**Comment by ReinerBforartists** [comment] 2020-11-17 19:06
Sorry that i did not met your expectations. It's the difference between what you want and what you achieve. And we cannot hide the first menu. You need a place to turn on or off the quick toggles.

I needed a short and pregnant name. Expose Toolbar Toggles is already ways too long for my flavour ^^
