### ISSUE TITLE
Process name is "blender" on Linux

### ISSUE THREAD

**Issue by iyadahmed** [Bforartists/Bforartists#3564] opened 2023-06-02 11:44 UTC
I'm now on Fedora Linux 38 and building Bforartists from master shows "blender" as executable name
![image](https://github.com/Bforartists/Bforartists/assets/25552173/35a68584-45a5-47f7-bd0c-b14a4488b2f7)

**Comment by Blenux** [comment] 2023-06-04 02:19
Was this under Wayland?, has I notice this in Plasma Wayland also (with a Wayland Icon), X11 it comes up bforartists.

**Comment by ReinerBforartists** [comment] 2023-06-04 06:00
This could be the cause. I just cannot test it.

intern\ghost\intern\GHOST_SystemWayland.cc

![cause](https://github.com/Bforartists/Bforartists/assets/13919702/f387b036-fb91-4bce-bd3b-bb36c0a40481)

**Comment by ReinerBforartists** [comment] 2023-06-05 06:28
Merged. 

For the future, You can connect such issues with the merge when you create a branch from this issue. Then this issue auto closes when the merge is done.

![creatrebranch](https://github.com/Bforartists/Bforartists/assets/13919702/7bac26b2-bade-4962-868e-8be968254133)

**Closed by ReinerBforartists** 2023-06-05 06:28 UTC
Labels: 2 - bug
