### ISSUE TITLE
Outliner - Outliner ID Data Operation right click context menu missing Asset entries

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2758] opened 2021-11-04 14:58 UTC
# Issue
Blender Outliner ID Data operation (right click on material or anything not a collection, object, or world) has entries in Blender to mark assets. In Bforartists this is not true. 

**Blender - 17 Oct**
![image](https://user-images.githubusercontent.com/35357409/140336749-68d7b8e4-f1a0-43bf-a8fc-d0dd5a0cde79.png)

**Bforartists**
![image](https://user-images.githubusercontent.com/35357409/140336757-4b9b79d3-4f25-41ea-a1b0-efe2b5741872.png)

Ideally you should be able to mark all asset data block types from the outliner like you can in Blender.

**Comment by ReinerBforartists** [comment] 2021-11-04 16:46
Interesting find. Confirmed. Investigating.

**Comment by ReinerBforartists** [comment] 2021-11-04 16:55
Hm, not to find where this appends from

**Comment by ReinerBforartists** [comment] 2021-11-04 18:05
Not to catch. I have no idea where this menu part resides, and why it is not showing. The original menu does not contain this part in Blender neither.

Unassigning for now.

**Comment by Draise14** [comment] 2021-11-04 19:46
Ah, is this also an experimental thing? Let me confirm.

**Comment by ReinerBforartists** [comment] 2021-11-04 19:58
No, it shows in the regular Blender version. But it appends from somewhere. And i cannot find this menu.

**Comment by ReinerBforartists** [comment] 2021-11-05 16:43
Next round ...

**Comment by ReinerBforartists** [comment] 2021-11-05 18:30
Ah finally found the cause. This one dodged twice behind the Cmake cache ...

The content is the right click menu from Blender, which we have turned off since it is a useless double.

To do. Get rid of paste data blocks, which is the same command than paste. And so a double in this menu. Interestingly it carries the hotkey.  Ah, Blender right click menu mess ....

![fubarasusual](https://user-images.githubusercontent.com/13919702/140560291-2514548d-59d6-4fb7-aae3-98b88c82eda8.jpg)

**Comment by ReinerBforartists** [comment] 2021-11-06 07:29
Sheesh, this bug is crazy. Again i run into a black hole here. OUTLINER_MT_context_menu does not contain our five new menu items ...

**Comment by ReinerBforartists** [comment] 2021-11-06 07:57
Fixed in master

![fixed](https://user-images.githubusercontent.com/13919702/140602564-19169cbf-c06e-4f41-8fdf-6a738f9ce98f.png)

**Closed by ReinerBforartists** 2021-11-06 07:57 UTC
Labels: 2 - bug, 0 - task, 4 - needs work
