### ISSUE TITLE
Disappearing Icon

### ISSUE THREAD

**Issue by Neshiah474** [Bforartists/Bforartists#1816] opened 2020-09-10 17:19 UTC
I downloaded BforArtists 2.5 for OSX. An icon appeared on my desktop. After starting up the iMac the icon was, and is, consistently, gone. It doesn't prevent using the app, just a minor thing.
High Sierra 10.13.6. LATE 2009 21.5 iMac. ATI Radeon HD 4670 256 MB

**Describe the bug**
A clear and concise description of what the bug is, and how to reproduce it.

**Comment by ReinerBforartists** [comment] 2020-09-10 19:03
Thanks for the report. Sean, could you be so kind to have a look if you can do something here? :)

**Comment by seanr** [comment] 2020-09-12 04:42
I need much more info than was posted here. Please include screenshots if possible but more generally a description of what the icon was, when it appeared, and when it disappeared. There should not have been a desktop icon created at all other than the mounted DMG if you have Finder set to show those on the desktop, assuming you installed by dragging the Bforartists icon to the Applications shortcut in the DMG (this is a pretty typical Mac app install process and is the same as Blender). If the icon was just the mounted DMG, that is expected behavior (by design of the OS) as with any other such installer.

**Comment by ReinerBforartists** [comment] 2020-09-14 06:25
Thanks sean. When i understand your description right, then this is expected behaviour.

I think it is safe to close this report as invalid then. We can reopen the report at any point in case Nesiah474 provides us with more information.

Thanks for the report

**Closed by ReinerBforartists** 2020-09-14 06:25 UTC
Labels: 2 - bug
