### ISSUE TITLE
"No detected card" with External Video Card - 3.1.2 Official Release - Cuda problem

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2946] opened 2022-04-06 20:18 UTC
> Thank you for your work ✊🏼 I installed it and wanted to see how it performs but then i realized that it doesn't recognize my external graphic card (rtx 3070 laptop version) neither for cuda nor for OptiX. It says "No compatible GPUs found for Cycles".Just wanted to give feedback.

>  i have tried now with the [blender] 3.2 beta that was released 3 weeks ago and it works as it should be. But in your version it doesn't even show my CPU 😱 I attached the screenshots then you can see yourself also ✌🏽

Bforartists:
![image](https://user-images.githubusercontent.com/35357409/162062833-9c09cf14-201e-4beb-900a-080c21ea0477.png)

Blender:
![image](https://user-images.githubusercontent.com/35357409/162062880-1ba5fcfb-655e-4ee5-9d59-7b97dd43f24e.png)

> **Devbuild-02-04-2022** is working ✌🏽
> My CPU is i7-10870H and GPU RTX 3070.
> Ps. I have the latest Intel and Nvidia graphic drivers.

Looks like something was missed in the release. My Nvidia graphics card is detected, but it is internal. So I am not sure where to begin. I have had the user (on twitter) to test blender 3.2 (works) and the latest devbuild (works) - but the official release it doesn't detect the external graphics. Maybe you'd have a clue?

**Comment by Draise14** [comment] 2022-04-06 23:19
![image](https://user-images.githubusercontent.com/35357409/162089294-645afe90-25da-4957-92a4-be81e2141c0f.png)

Huh, ok, got the same issue on my end with 3.1.2

**Comment by ReinerBforartists** [comment] 2022-04-07 06:44
Not here. Here it works as expected O_O

![works](https://user-images.githubusercontent.com/13919702/162136633-cac227fb-96bf-40e3-b4b0-e60631da84ff.jpg)

**Comment by ReinerBforartists** [comment] 2022-04-07 07:07
Mh, it can be that the cuda version that i use to compile is outdated. Officially Blender uses 11.4 now, and i am still at 11.2 at Windows. But then you would have had trouble with 3.1.0 already. It's still the same version. Curious.

**Comment by ReinerBforartists** [comment] 2022-04-07 09:08
As expected, there is no way to update Cuda at Ubuntu 20.04 anymore. Phew. This is a tough one. It can take weeks to get a new VM installation up and running. And migrating to Ubuntu 21 will produce a Deb again that will not run at other more conservative linux distributions -.-

**Comment by ReinerBforartists** [comment] 2022-04-07 09:15
Here is a version that is compiled with Cuda 11.4 and Optix 7.4. Please test

https://cloud.bforartists.de/index.php/s/f8DdZaw4SajHawM

**Comment by ReinerBforartists** [comment] 2022-04-07 09:19
Mh, the rounded corners tells me that it is not Windows. Is it Linux? As told, here we have a big problem at the moment ...

**Comment by ReinerBforartists** [comment] 2022-04-07 09:23
By the way ... https://devtalk.blender.org/t/blender-gpu-not-found-cycles-cuda/12556/14

I just don't fully understand what he does here ^^

**Comment by ReinerBforartists** [comment] 2022-04-07 09:51
Maybe this is one of the regressions that made Blender 3.1.2 necessary. And maybe the fix for the regression did not make it into our final release. In this case the next dev build might fix the issue.

**Comment by Draise14** [comment] 2022-04-07 12:04
I'll give the environment path variable a test now that I reproduce the issue. Yeah there is not much else  we can do here. 

This may have been because when 3.1.2 came out Bforartists merge was a week behind? He can make it work on the list dev build so here is going the next one can too!

**Comment by ReinerBforartists** [comment] 2022-04-07 15:59
Yes, maybe the merge at sunday will fix it. I will create a new release version in case it does. No GPU rendering is showstopper bug ...

**Comment by Draise14** [comment] 2022-04-07 16:13
I'll test it once online. Latest I'm using is **devbuild-02-04-2022**

**Comment by ReinerBforartists** [comment] 2022-04-08 06:08
> Here is a version that is compiled with Cuda 11.4 and Optix 7.4. Please test

https://cloud.bforartists.de/index.php/s/f8DdZaw4SajHawM

Urgent! Somebody needs to test it. I can't, for me it works.

The question for me is, is it Cuda, or is it missing code. In the latter case i need to do a merge.

**Comment by Draise14** [comment] 2022-04-08 13:15
Testing

**Comment by Draise14** [comment] 2022-04-08 13:21
CUDA good, Optix missing still. I don't have a HIP card available, but also not detected - but to be expected.

**Comment by ReinerBforartists** [comment] 2022-04-08 15:46
Many thanks,

HIP does not work at Windows. This is a known issue. Blender uses a beta version that is not publically available.

So this time Cuda is working again? That's at least something. I have compiled with Optix 7.4 already. And this might not fit together. I will try to compile with Optix 7.3 again.

**Comment by ReinerBforartists** [comment] 2022-04-08 16:04
Do we have somebody to test the linux version?

**Comment by ReinerBforartists** [comment] 2022-04-08 16:32
Here is the new Windows version with Cuda 11.4 and Optix 7.3 https://cloud.bforartists.de/index.php/s/F3po9743N36DfCJ

**Comment by ReinerBforartists** [comment] 2022-04-08 16:48
And here comes the Linux version https://cloud.bforartists.de/index.php/s/Q9riP6C8yCkR6yJ

Please test if possible !

**Comment by Draise14** [comment] 2022-04-08 16:50
Tested Windows version. Got both! Woo! Optix and CUDA green.

**Comment by ReinerBforartists** [comment] 2022-04-08 17:03
\o/

So the cause was simply a too low cuda version. Phew. This means that i will build a new version tomorrow. And do the merge afterwards. Thanks for testing :)

Linux remains a problem though. I couldn't manage to install the required Cuda 11.4. It is the newest version 11.6. Fingers crossed ...

**Comment by ReinerBforartists** [comment] 2022-04-08 18:32
Friends, has somebody of you actually tested this? ^^

I have Cuda showing in the prefs, but it doesn't render anymore with the GPU -.-

Well, i can now at least reproduce the problem. But i have no clue why the cl.exe is not found. I guess i will do the merge first. And check if the rendering is back working then.

This version makes really trouble ...

![fails](https://user-images.githubusercontent.com/13919702/162500950-6bbf07d7-395d-4730-9361-83e0ccf82826.jpg)

**Comment by Draise14** [comment] 2022-04-08 18:40
Wait. I haven't done a stress test. Another user gave a test: green light but not a lot of detail (windows)

 I'll do a stress test in a bit. Cooking lunch atm

**Comment by ReinerBforartists** [comment] 2022-04-08 18:45
It's the same problem than in the release version 3.1.2. So as told, let's do a merge. Then have a second look at the problem. In best case the merge fixes the issue.

**Comment by ReinerBforartists** [comment] 2022-04-09 05:56
Devbuild from 02.04.2022 before the release worked fine. Release build 3.1.2 fails. Let's have a look if the blender compagnion where i have merged from works or fails ...

**Comment by ReinerBforartists** [comment] 2022-04-09 06:30
Blender renders fine. So it is not my setup. And not cuda. But must be something in the merged code.

Let's reinvestigate the changes from the latest merge before adding even more code with a new merge.

**Comment by ReinerBforartists** [comment] 2022-04-09 07:31
What the heck is going on here? I wanted to check the error text again. And now it works O_O

![gpuworks](https://user-images.githubusercontent.com/13919702/162561778-a8315131-1cbe-4dff-96f2-e83cc7f1995d.jpg)

**Comment by ReinerBforartists** [comment] 2022-04-09 07:34
@Draise, please do a stress test ^^

**Comment by ReinerBforartists** [comment] 2022-04-09 08:55
What about the mac version? Does Cuda work here?

**Comment by Draise14** [comment] 2022-04-09 17:21
Render works on both the Cuda and Optix version with latest download.

**Comment by ReinerBforartists** [comment] 2022-04-09 18:27
Perfect. Thanks for testing. Pushing the next release version now.

**Comment by ReinerBforartists** [comment] 2022-04-10 09:08
New version is online. Closing ...

**Closed by ReinerBforartists** 2022-04-10 09:08 UTC
Labels: 2 - bug
