### ISSUE TITLE
3D View - UnboundLocalError: local variable 'act_mode_item' referenced before assignment with hide editortype menu

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3369] opened 2023-01-07 06:27 UTC
![image](https://user-images.githubusercontent.com/35357409/211134569-21926f9d-6393-4121-a3a2-e099d93e47b9.png)

Video:
https://user-images.githubusercontent.com/35357409/211134540-abdc99c4-8036-4324-b61c-75e88b3673b2.mp4

Symptom
![image](https://user-images.githubusercontent.com/35357409/211134528-6f4d9dfd-3975-4699-bb66-de110884cf6a.png)

Line **927-1139** of the` space_view3D.py` is a duplicate - and doesn't have the variables defined. These shouldn't even exist.
https://github.com/Bforartists/Bforartists/commit/ff2afcbaea0949ebbfb12e24d1afdf7bdab8015a#diff-5721932d25525125b6fcf3a8e6adf87a8b16f2ce8488a85e15ae071cb2795e98

How to reproduce:
- Shot/Hide the editor toggles.

**Comment by ReinerBforartists** [comment] 2023-01-07 07:17
I have changed the title to reflect the problem a bit better. Two times bug in the title doesn't fit. 

And the cause is the hide editortype menu ...

![hideeditortype](https://user-images.githubusercontent.com/13919702/211138965-c0f5d1ab-f70f-46ee-b768-e53986e2ba1d.jpg)

**Comment by ReinerBforartists** [comment] 2023-01-07 07:22
Yup, you merged the code into the wrong class i would say :)

This menu here comes from us. There shouldn't be any Blender code in it ...

> # bfa - show hide the editormenu
> class ALL_MT_editormenu(Menu):
>     bl_label = ""
> 
>     def draw(self, context):
>         self.draw_menus(self.layout, context)
> 
>     @staticmethod
>     def draw_menus(layout, context):
> 
>         row = layout.row(align=True)
>         row.template_header()  # editor type menus

**Comment by Draise14** [comment] 2023-01-07 07:28
And fixed.

**Closed** 2023-01-07 07:28 UTC
Labels: 2 - bug, 1- Fixed
