### ISSUE TITLE
Addon Extreme PBR Nexus no previews

### ISSUE THREAD

**Issue by Blenderblunder** [Bforartists/Bforartists#3547] opened 2023-05-29 06:49 UTC
When using the add-on Extreme PBR Nexus in Bforartists 3.4.1 (based on Blender Alpha 3.6) the add-on works correctly.

When using Bforartists 3.5.1 (also based on Blender Alpha 3.6) the previews of the materials do not show. 

The add-on works under Blender 3.5.1 

I have contacted the developer who suggests the following: 

 "So I think at this point you should report what happened to the Bforartist guys. In this case it should simply be a Bug that was present in the Alpha version, this bug is not very easy to identify as I think it is in blender's "C" code, you should report it on their page
"https://github.com/Bforartists/Bforartists/issues"

Saying that the icons in bpy.types WindowManager don't load correctly, like in Blender 3.6 Alpha.

I think this happens to many addons that use previews loaded in bpy.types.WindowManager"

I am using Mac Pro, Monterey 12.6.1, AMD RX6600 

Thank you

**Comment by ReinerBforartists** [comment] 2023-05-29 09:20
Hey Blenderblunder,

Thank you for your report. Please keep in mind that we are always one version ahead since we rely at the Blender Main branch. In this case version 3.5.1 is already based at the code from Blender 4 Alpha. And i am pretty sure that they will change some things under the hood regarding addons. 

We have unfortunately nobody to check the Mac issue. So could you please check if the addon works with the newest Alpha version of Blender? If yes, then we need to investigate further. If not then we need to find the cause at our end.  And the issue is then best reported to Blender directly.

Blender 4.0.0 Alpha can be found here: https://builder.blender.org/download/daily/

Kind regards
Reiner

**Comment by Draise14** [comment] 2023-05-29 14:06
Yeah, Bforartists 3.5.1 is really Blender 3.6.0+. If it is not working in Blender 3.6.0 or 4.0.0, then it may have troubles with BFA.

**Comment by Blenderblunder** [comment] 2023-05-30 05:47
Hi Reiner and Draise,
First, thanks for responding and for all your work on Bforartists which makes Blender usable. I just had that reinforced by loading the Blender 4 Alpha and trying to navigate around it, what a mess!
No need to apologise either, you can't really be expected to support addons but I will let the developer know the outcomes too. 
Anyway, the Extreme PBR Nexus add-on does work in Blender 4 Alpha with all the previews showing. It did take a very long long time for the render kernels to compile in Cycles though and the viewport is pretty clunky (using metal backend on an Intel Mac). 
I don't know if any of that helps but it does seem like there is a glitch somewhere as it works in BFA 3.4.1 and in Blender 3.5.1 and Blender Alpha 4 but not in  Bforartists 3.5.1.  However, the developer did have an issue with Blender 3.6 Alpha and had to write a patch to bring back the previews. This patch doesn't work on BFA 3.5.1. 
Hope this is clear but given it works in all versions of Blender proper, maybe it is something amiss in BFA? Or with the Mac?
Kind regards
Stephen

**Comment by ReinerBforartists** [comment] 2023-05-30 07:02
Many thanks Stephen. 

This is a paid addon, right? Any chance that we can get our hands at it? I need to see the exact error message in action ...

**Comment by Blenderblunder** [comment] 2023-05-30 07:39
HI Reiner

Thanks for your quick response. 

It is a paid add-on - and an absolutely excellent one for dealing with textures without having to mess about with nodes (although it uses them in the background). 

I could provide the zip but it is around 71mb and you need to activate it by going to the developer’s website and registering your computer, so I don’t think it would work to just load it in. 

What I will do though is contact Andrew the developer and ask him if he would give you permission to use it for test purposes. He is very responsive and helpful (plus - really a great method to use materials and textures with a very useful library)

Hang about while I email him, he is in Italy I think. I am in Australia, not sure how the timezones will line up. 

Here is his promo page on Blender Market for your reference. 

https://blendermarket.com/products/extreme-pbr-addon-for-blender-279-2 <https://blendermarket.com/products/extreme-pbr-addon-for-blender-279-2>

Best
Stephen

**Comment by ReinerBforartists** [comment] 2023-05-30 09:53
> It is a paid add-on 

Yes, but we are volunteer driven, we cannot buy it. And as told, it is not illegal to give this addon away. It is GPL :)

**Comment by Blenderblunder** [comment] 2023-05-30 10:36
Hi Reiner,

I understand you can’t buy it and fair enough.

 I can provide it to you, but I don’t think you will be able to activate it as it requires going to his website, registering it and with the provided passcode, entering the username and passcode into the add-on dialogue to activate it. Otherwise it doesn’t work. 

That’s why I have asked him if he could provide it to you for free for test purposes. Haven’t heard back but meanwhile I can give you the zip file to see if you can install it and activate it. 

Here is a link to it.

https://cloudstor.aarnet.edu.au/plus/s/GFHukk9HWlZiHft <https://cloudstor.aarnet.edu.au/plus/s/GFHukk9HWlZiHft>

The password is:

***@***.***

Hope that helps

Cheers
Stephen

**Comment by Blenderblunder** [comment] 2023-05-30 11:53
Hi Reiner,

Yes, just had a look at the GPL regulations - makes me wonder how you could actually sell an add-on under those circumstances. 

But, good news - Andrew just got back and will be happy to provide a working version, or a way around it.

He asked if you could contact him directly? His email is:

***@***.*** ***@***.***>

Thank you once again for chasing all this up. I am sure you have other things to do!

Best

Stephen

**Comment by ReinerBforartists** [comment] 2023-05-30 11:59
> ***@***.*** ***@***.***>

I fear this is not a valid email adress. Thank you Github XD

Sometimes the whole world is in the way. And Github protects passwords and email adresses in the conversation it seems. So one more loophole to go i guess ...

You could join our Discord server, and talk to Draise directly about the issue. I might be around too, but no promises: [discord.com/invite/yKuR77v](https://discord.com/invite/yKuR77v)

**Comment by Blenderblunder** [comment] 2023-05-30 12:20
My apologies, I copied his email address from my email application. 

I think it is most likely to get an answer or help from him directly, or at least, be able to activate the add-on. 

Thank you for your offer to speak to Draise. I am, embarrassingly, not on Discord - and not at all sure how it works, so that could take a while.  But I also fear I wouldn’t be able to tell them much beyond - it doesn’t work. 

I have written to Andrew via email and am awaiting a reply but I now realise what I think he meant was to contact him through the assistance page on his website here:

https://extreme-addons.com/assistance/ <https://extreme-addons.com/assistance/>

There is a chat function at the bottom right, an orange field with a white talk bubble. He is there at the moment. 

Totally understand if you have lost patience with the issue at this stage though.

Best
Stephen

**Comment by ReinerBforartists** [comment] 2023-05-30 12:21
Sometimes life is complicated ^^

**Comment by Blenderblunder** [comment] 2023-05-30 12:23
Always - in my humble opinion.

Andrew just also emailed me to suggest going through his website but he also provided this email

***@***.*** ***@***.***>

Hopefully, he will have some answers, or you for him!

Best

Stephen

**Comment by Draise14** [comment] 2023-05-30 16:34
> Hi Reiner and Draise, First, thanks for responding and for all your work on Bforartists which makes Blender usable. I just had that reinforced by loading the Blender 4 Alpha and trying to navigate around it, what a mess! No need to apologise either, you can't really be expected to support addons but I will let the developer know the outcomes too. Anyway, the Extreme PBR Nexus add-on does work in Blender 4 Alpha with all the previews showing. It did take a very long long time for the render kernels to compile in Cycles though and the viewport is pretty clunky (using metal backend on an Intel Mac). I don't know if any of that helps but it does seem like there is a glitch somewhere as it works in BFA 3.4.1 and in Blender 3.5.1 and Blender Alpha 4 but not in Bforartists 3.5.1. However, the developer did have an issue with Blender 3.6 Alpha and had to write a patch to bring back the previews. This patch doesn't work on BFA 3.5.1. Hope this is clear but given it works in all versions of Blender proper, maybe it is something amiss in BFA? Or with the Mac? Kind regards Stephen

Blender unfortunately does official releases from a branch, and they use SVN with the dependencies that has only one trunk, the most recent. There are no official branches of the dependencies for official releases, so 4.0.0 has been merged and updated and the most recent dependencies are now in Bforartists based on 4.0.0, and it may no-longer compile with the 3.6.0 branch of Blender and it's dependencies that we no-longer have. I don't know what Blender does internally to keep the deps static per official branch - but we don't have that system. We always work with the most recent main of Blender and the most recent version of the dependencies in the main - on a weekly basis - for longevity. Maybe it's time to test on the devbuilds to see if the addon works? When BFA 3.5.1 came out, 4.0.0 wasn't merged to master yet, but the week after it was. Since then a few weeks has gone by with the latest worked from 4.0.0. So if the patch doesn't work with 3.5.1 official (closer to Blender 3.6.0), try the devbuild which is now closer to Blender 4.0.0 now. Metal gets constant updates, so.. devbuilds might be the best bet, blender unfortunately changes these code bases per week, and depending on the date we merge or work the official release from, it may or may not work.. 

You can find the devbuilds set by date here:
https://www.bforartists.de/download/

**Comment by ReinerBforartists** [comment] 2023-05-30 16:50
Good points. Thanks for bringing this onto the table.

I would vote to close this issue down then. In hope that one of the future mac developer builds may bring the fix. 

@Blenderblunder, maybe you could even try to compile Bforartists by yourself. It's a bit work though to get all the dependencies working.

>  I don't know what Blender does internally to keep the deps static per official branch - but we don't have that system.

They stored the old dependencies for every Blender version somewhere. But they seem to have moved it with the new structure. Need to dig again ...

**Comment by Blenderblunder** [comment] 2023-05-31 04:25
HI Reiner and Draise

Thank you for following this up, appreciate it. 

From what I can understand, it seems little can be done at this stage but that a future release - V4 - is likely to fix the issue. This makes sense as Blender v4 does work with the add-on. 

For the time being, I can continue using BFA 3.4.1 and hope a fix eventuates. 

You mention possibly compiling the software myself Reiner, it is interesting you mention that. I have never done such a thing but I can read, and follow instructions. (Your comment about getting the dependencies to work had me worried though, I didn’t even know what they were until I googled them a moment ago - so no software expert.)

So - I won’t do it now but, as I am hoping to upgrade to Mac Silicon (as soon as they bring out something Mac Pro equivalent) and as BFA does not have a Mac Silicon version only Intel, I was thinking I might be forced to compile the code myself at that point. If I do, I will let you know, as we could make it generally available. (Assuming I can figure out how to do it and that would be useful to the project.)

Meanwhile, thanks again for your help and I am hopeful v4 should provide a fix. 

And thanks of course, for the whole BFA project, it is a blessing. Everytime I use Blender’s native UI I end up shouting at the screen in frustration at the mad lack of organisation. 

Cheers
Stephen

**Comment by ReinerBforartists** [comment] 2023-05-31 07:07
Okay, i will close down this thread now. Thank you :)

It's not this hard. Blender has a detailled description in its wiki. All you have to do is to adjust the paths a bit.

https://wiki.blender.org/wiki/Building_Blender/Mac

This for example:

```
mkdir ~/blender-git
cd ~/blender-git
git clone https://projects.blender.org/blender/blender.git
cd blender
make update
```

Looks like this then:

```
mkdir ~/bforartists-git
cd ~/bforartists-git
git clone https://github.com/Bforartists/Bforartists
cd bforartists-git
make update
```

**Closed** 2023-05-31 07:08 UTC
Labels: 6 - wontfix, Needs more information

**Comment by Blenderblunder** [comment] 2023-05-31 07:18
Ok, thanks Reiner - not this time around, unless v4 doesn’t work but I will definitely when I move to an Apple silicon machine and will let you know if it is successful so you can distribute it. 

Cheers
Stephen
