### ISSUE TITLE
Blenderkit addon fails to enable

### ISSUE THREAD

**Issue by slippystance** [Bforartists/Bforartists#1884] opened 2020-10-18 13:04 UTC
Summary:
In v251 of Bforartists, the Blenderkit addon throws an error when being enabled

Steps to repro:
1.  Install a fresh version of Bforartists 251 (Blender 2.91 Alpha)
2.  Launch Bforartists
3.  Go to Preferences->Addons
4.  Enable Blenderkit (it's included in the Blender distribution package)

Expected:  Addon can be enabled
Actual:  Addon fails to enable and error is throw (see attached screenshot)

Notes:  

* I installed a vanilla Blender 2.91 alpha and tried the same thing, no issues occurred enabling or using the addon.
* I installed Bforartist 2.0 (2.83 Blender) and tried the same thing, no issues occurred.

**Desktop (please complete the following information):**
Windows 10, 1080ti

**Screenshots, Example Files**
If applicable, please add Example material. A screenshot, a blend file, Or even a short video.
![image](https://user-images.githubusercontent.com/57046940/96368186-644ad080-1107-11eb-84e5-aba4295d8609.png)

**Comment by ReinerBforartists** [comment] 2020-10-18 15:47
Hi slippystance,

Thanks for the report. But i cannot reproduce the problem here. The addon activates just fine. Could you please download the newest developer build, and check if the problem persists?

![blenderkit](https://user-images.githubusercontent.com/13919702/96372998-026f8280-116a-11eb-9bab-f32f12d1dd2a.jpg)

**Comment by slippystance** [comment] 2020-10-18 16:36
bkit.json file was the culprit
deleting the file and then re-enabling blenderkit fixed the issue.

I think this is a legacy issue that carried over when Blenderkit was a separate addon from Blender (unlike now where it's included with Blender).

So as I migrated from 1 version of b4 to the next and carried stuff over from the previous build, Blenderkit may have choked.

**Comment by ReinerBforartists** [comment] 2020-10-18 18:51
Ah, great. Thanks for letting us know. Closing the thread, nothing to do here :)

**Closed by ReinerBforartists** 2020-10-18 18:51 UTC
Labels: 0 - task
