### ISSUE TITLE
 3D View - New Transform Keymap - Snap Base

### ISSUE THREAD

**Issue by Blenux** [Bforartists/Bforartists#3572] opened 2023-06-08 04:56 UTC
In 4.0 they have added the ability to where to snap from during transform operations in the 3D View.

```
This commit implements a new modifier key (`B`) for the transform
operators.

This new key allows changing the 'Snap Base' of a transform by snapping
it to a defined point in the scene.
```
[Commit Here](https://projects.blender.org/blender/blender/commit/3010f1233b2#diff-59f32140e4ac19318635946a285353d9490300c9)

https://github.com/Bforartists/Bforartists/assets/25260650/7fb26ad1-e609-4800-b85a-12b395cef953

**Comment by Draise14** [comment] 2023-06-08 16:06
I was wondering about this one. Shame you gotta hit a modal to make it work - but nice catch to add it.

**Comment by ReinerBforartists** [comment] 2023-06-29 16:06
Shouldn't this have a menu entry?

**Comment by Draise14** [comment] 2023-07-19 01:03
I can't seem to reproduce the box select hotkey conflict.. will have to test further.

**Comment by ReinerBforartists** [comment] 2023-07-19 06:18
It is not that the one works and the other not. It is that i end too often in box select with this tool then, and need to press d for tweak again.

**Comment by Draise14** [comment] 2023-07-19 12:46
Maybe instead of B for snap, could be S? S is not used in object mode from what I recall. But then.. edit mode. S is extrude. 

Though since this is a transform modal and a blender-esque UX, coming from other software indeed you won't use it a lot.

**Comment by ReinerBforartists** [comment] 2023-07-19 15:43
Alt B would be free. But i keep it in your hands. You can also simply close the issue.

**Comment by Draise14** [comment] 2023-07-19 17:21
Hmm.. I think with this case, I will close since the conflict is a post-operation issue after a rarely accessed modal chained operation, so B will be box select by association most times. And if this were to be resolved, we would technically have to resolve X, Z, ALT, CTRL, etc.. since they too are used in object mode when not in modal mode for other operations. 

Additionally, during the modal transformation there is no technical hotkey conflict - and in Bforartists, the modal keys are only available while transforming, and the transform modals are not sticky, ei, you move, place, modals are immediately gone. You access them only after you've decided you're transforming with modals by holding down mouse and sticking to modal mode - so you gotta intentionally stick to moving to then learn to hit B for another mindset of operations - those are not exposed to object mode. So it is not necessarily accessed often. So B to snap bounding as association won't be the UX by default, so fallback to Box select is still ok.. 

And.. well the Blender hotkeys that are sticky to modals...  it's the same issue, or similar, and if you're a Blender hotkey user in Bforartists, let Blender worry bout that conflict. 

_Come to think of it... wish they made this snap to bounding as it's own transform operator_

**Closed** 2023-07-19 17:33 UTC
Labels: 0 - task
