### ISSUE TITLE
Setting up Units for Millimetres

### ISSUE THREAD

**Issue by Kagukara** [Bforartists/Bforartists#3695] opened 2023-08-21 23:29 UTC
When setting up Bforartists for millimetres it doesn't recognise the already set parameters if an object (Cude for instance) hasn't been placed, or after quitting and reopening the application. I have tested this on version `3.6.1` and `3.6.0` AppImages.
#
**Steps to Reproduce**
1. Launch bforartists AppImage (no .config files)
2. Add Cube from the Header
- If you don't add a Cube now, your Cube after setting up Millimetres will be:
- - Scale X,Y,Z = 1.000 and Dimensions: X,Y,Z = 2000 mm
- - Unit Scale is still 0.001 and Length is Millimetres
- Adding and then deleting the Cube also works
3. Go to Scene → Units in Properties side menu
4. Change Unit Scale to 0.001
5. Change Length to Millimetres
6. Go to Overlays in the Viewport Header
7. Change Grid Scale to 0.001
8. Go to View and change Clip Far to 10000 mm
9. Add another Cube from the Header
- Cube is Scale X,Y,Z = 1.000 and Dimensions: X,Y,Z = 2 mm
- Deleting and re-adding a Cube will keep its Scale and Dimensions
10. Edit → Save Startup File → Save Startup File
```
Writing homefile: "/home/richard/.config/bforartists/4.0/config/startup.blend" ok
Info: Startup file saved
```
- Saving with the Cube still in the scene doesn't matter
11. File → Quit → Don't Save
```
Saved session recovery to "/tmp/quit.blend"
Writing userprefs: "/home/richard/.config/bforartists/4.0/config/userpref.blend" ok
Info: Preferences saved

Bforartists quit
```
- Saving the file and renaming it to userpref.blend and replacing the existing one doesn't help
12. Launch bforartists appimage (.config now has files)
```
Read prefs: "/home/richard/.config/bforartists/4.0/config/userpref.blend"
```
13. Add Cube from the Header
- - Cube is now Scale X,Y,Z = 1.000 and Dimensions: X,Y,Z = 2000 mm
- - Unit Scale is still 0.001 and Length is Millimetres
- Changing back Unit Scale to 1.0 and Length to Meters the Cube is: 
- - Scale X,Y,Z = 1.000 and Dimensions: X,Y,Z = 2000 m

At step 13 the only way for the Cube to be scaled properly is to Load Factory Settings and redo steps 2 → 8. Load Factory Settings doesn't delete the `startup.blend` file in `~/.config/bforartists/4.0/config/` so you'll have cubes set to 2000 mm unless you either Load Factory Settings or remove the `startup.blend` from `~/.config/bforartists/4.0/config/`.
#
**Temporary Fix**
- Set these parameters and Save Startup File
- - Unit Scale: 1.00
- - Length: Meters
- - Grid Scale: 0.001
- - Clip Near: 0.01 m
- - Clip Far: 1000 m

Just have to work in meters for the time being.
#
**System Information**
* OS: `Arch Linux`
* Kernel: `6.4.11-arch2-1`
* GPU: `AMD Radeon RX 7900 XTX (gfx1100, LLVM 18.0.0, DRM 3.52, 6.4.11-arch2-1)`
* GPU Driver: `4.6 Mesa 23.3.0-devel (git-71a2d651c1)`
* AppImage Version: `Bforartists-3.6.1.glibc2.28-x86_64.AppImage`

**Comment by Draise14** [comment] 2023-08-22 00:01
Thanks for the detailed report!!! I'm having difficulty understanding the issue here though. 

What is the goal? 

I have done the unit measurements and file startup savings trying to copy what you're doing, but I don't see any inconsistencies and I cannot reproduce the issue. 

1. Adding a cube will always be scale 1.000 and the dimensions will be 2000mm or 2m, depending on scene units. Object scale is a software unit that's internal, and when you apply scale, you can keep scale to 1.000 at 2mm to store in the startup - and when you scale back up to 2m and it would be 1000.000 scale. Scale of an object out is a relative scale to world scale in internal units, not scene units. 
2. Changing view clip and grid size does not affect anything other than the camera clip and grid overlay. 

Here is an example where the dimensions changes to scene units, but the scale remains the same. 
![bforartists_dmhyB0AZCX](https://github.com/Bforartists/Bforartists/assets/35357409/a96c9959-6a43-43d6-9069-bbb5570ea616)

Here is an example of the object scaled to 0.001 - with the correct dimensions listed based on scene units. Units are ok. 
![bforartists_9Sf50qp74r](https://github.com/Bforartists/Bforartists/assets/35357409/552af3fa-1d14-4137-80f2-f408af41b9fa)

Here I save the startup with an applied scale of the 2mm cube, set the scene units to mm and saved startup, it says it's 2mm wide when loading again. Cannot reproduce the issue. 
![image](https://github.com/Bforartists/Bforartists/assets/35357409/17b0ae5e-f06e-48a3-894f-1e42eb6def8c)
![image](https://github.com/Bforartists/Bforartists/assets/35357409/976beca2-1a03-4d95-90d4-206522b91bb4)

Could you do some screen captures of your issue to help understand it a bit better - so I can reproduce? Right now I can't seem to find the problem. Thank you for the detailed explanation, yet a screen capture could speak a thousand words.

**Comment by Kagukara** [comment] 2023-08-22 00:16
I watched this video for setting up millimetres. [How to : Setup Blender into millimetres (mm) - Blender Tutorial](https://youtu.be/ZI49VIcISaw) 

Default factory settings:
![default](https://github.com/Bforartists/Bforartists/assets/43391109/b91dd8e0-916f-4bc6-836a-6c5164e90537)

How it looks at step 9:
![how-it-should-look](https://github.com/Bforartists/Bforartists/assets/43391109/24cc307a-2fc0-43fa-892a-7c3405f53969)

How it looks at step 13:
![not-correct](https://github.com/Bforartists/Bforartists/assets/43391109/10e22aa8-8359-43d7-a3d6-f8e47bc14f92)

**Comment by Draise14** [comment] 2023-08-22 00:18
![image](https://github.com/Bforartists/Bforartists/assets/35357409/8c4cbbc2-de76-4efb-a6e7-b0ee6fc52ec2)

If you add a new cube at unit scale 0.001 then the new cube will be scale 1.000 at 2mm. 

If you save a 2m cube in the startup, it will be 2000mm large, best to delete it and add a new cube.

**Comment by Kagukara** [comment] 2023-08-22 00:21
> If you add a new cube at unit scale 0.001 then the new cube will be scale 1.000 at 2mm.
Correct.

> If you save a 2m cube in the startup, it will be 2000mm large
This was not the case. New Cubes will be 2000 mm the Cube that was 2 mm before would still be 2 mm on startup. Like I said in my steps to reproduce.

**Comment by Draise14** [comment] 2023-08-22 00:24
Cannot reproduce. I save the saved the startup with the new units, and the new cube is 2mm. 

![bforartists_wTUqmSvAUK](https://github.com/Bforartists/Bforartists/assets/35357409/5a46567c-b5fe-4102-8aa7-72f01d4a331a)

**Comment by Draise14** [comment] 2023-08-22 00:27
**Note:**This may be a new build of Bforartists, and we are currently working on 3.6.2, so this may be an issue from earlier builds. Will try the appimage now.

**Comment by Kagukara** [comment] 2023-08-22 00:42
Here is a video of the steps (video had to be compressed so I could upload it, but is still readable):
https://github.com/Bforartists/Bforartists/assets/43391109/e0822c24-4337-445b-bffc-223da9a251a3

**Comment by Draise14** [comment] 2023-08-22 00:44
Confirmed, the appimage has the issue, but not the latest builds. 3.6.2 should come out later this week and this shouldn't be an issue. Must have been a Blender issue that bleed through, and a reason they did a point release.

**Comment by Kagukara** [comment] 2023-08-22 00:47
Thank you for the confirmation, and great to hear that its not present in the latest build. Will come back to confirm myself when it releases, and then close the issue if it is fixed.

**Comment by Draise14** [comment] 2023-08-28 17:38
I have tested the steps in Blender 3.6.2, the issue remains. I also tested in the latest release candidate for Bforartists 3.6.2 appimage, same issue. But since this is now escalated to a Blender issue - there is not much we can do. I recommend you report this directly to Blender here: https://projects.blender.org/

**Comment by Draise14** [comment] 2023-08-28 17:53
Found blender 4.0.0 on the 28-08-2023 doesn't have the issue on Windows... so.. I really don't know what's up here, will postpone. Next weekend, could you test the devbuild?

**Comment by Kagukara** [comment] 2023-08-28 18:53
Tried to instal [blender-develop-git](https://aur.archlinux.org/packages/blender-develop-git) from the aur. `DISABLE_CUDA=1`, `DISABLE_OPTIX=1` and `DISABLE_USD=1` disable so it could start building.

Like all the other blender packages on arch and the aur it failed to build. Not sure why this is the case, but I have a feeling it something to do with me using mesa-git drivers or something. As this was the case a while ago I opted to looking for an appimage for blender which lead me to bforartists. Sorry I cannot test blender 4.0.0/devbuild unless there is an appimage.

**Comment by ReinerBforartists** [comment] 2023-08-29 06:49
Appimage for 3.6.2 is up. https://github.com/Bforartists/Bforartists/releases/tag/v3.6.2

**Comment by Kagukara** [comment] 2023-08-29 09:02
The issue is still there in 3.6.2 AppImage.

**Comment by ReinerBforartists** [comment] 2023-10-23 10:31
>I have tested the steps in Blender 3.6.2, the issue remains.

@Kagugara , @Draise14 , is this issue reported to Blender already? When it's a Blender bug then there is little that we can do except reporting it.

**Comment by Kagukara** [comment] 2023-10-23 10:48
Blender has now been fixed in the arch repository now allowing me to download the [package](https://archlinux.org/packages/extra/x86_64/blender/). I have changed it to millimetres and it works as intended. This is blender version 3.6.4.

**Comment by ReinerBforartists** [comment] 2023-10-23 12:41
Many thanks @Kagukara. Blender 4 is at its way, and will arrive in around two weeks. I hope that this version brings the fix then.

**Comment by Kagukara** [comment] 2023-11-19 22:11
This issue still persists in `Bforartists_401-.glibc2.35-x86_64.AppImage`. I have rechecked Blender 3.6.5 this issue doesn't happen. I'm unable to build the `blender-git` package on the aur as it segfaults.

**Comment by Draise14** [comment] 2023-11-19 22:30
Would a build on an Arch distro help you test? I wonder if this is an issue due to compiling the Appimage from Debian based build - then trying to use it on an Arch distro?

**Comment by Kagukara** [comment] 2023-11-19 22:33
If I could get a PKGBUILD file that would be nice, as the bforartists packages on the aur are flagged out of date. Or if you're talking about building the appimage on an arch distro that might also help if its easier.

**Comment by Draise14** [comment] 2023-11-20 15:08
> This issue still persists in `Bforartists_401-.glibc2.35-x86_64.AppImage`. I have rechecked Blender 3.6.5 and this issue doesn't happen. I'm unable to build the `blender-git` package on the aur as it segfaults.

Could you also check in Blender 4.1 per chance?

**Comment by ReinerBforartists** [comment] 2023-11-25 07:51
> This issue still persists in `Bforartists_401-.glibc2.35-x86_64.AppImage`. I have rechecked Blender 3.6.5 and this issue doesn't happen. I'm unable to build the `blender-git` package on the aur as it segfaults.

The problem here is that Blender 3.6.5 is version 3.6.5 of the code. But we are already at the Blender 4.1.0 code with Bforartists. And this is no valid comparison. We would need to check if the problem also exists in the Blender 4.1.0 code. And for that we need a working Arch version compiled from the Blender master.

We are simply in trouble here since nobody uses Arch in our team. And on top of it , Arch is a very own beast when it comes to compiling Blender / Bforartists as you just have found out. So it can happen that we will simply not find a solution here.

**Comment by ReinerBforartists** [comment] 2024-02-10 10:16
I will close this now as known issue. There is unfortunately nothing that we can do at our end.

**Comment by Kagukara** [comment] 2024-02-17 17:49
I have been able to install blender 4.1.0 and this doesn't happen, it is only happening in bforartists. @ReinerBforartists

**Comment by ReinerBforartists** [comment] 2024-02-18 06:41
Many thanks for getting back here. I could reopen it, but we have still simply no idea where this comes from :/

**Comment by Kagukara** [comment] 2024-02-18 15:17
Would it be possible if someone on the bforartists team could maintain the aur package? As it could be an issue with the appimage and compiling from source maybe a possible fix. At the moment the `bforartists-git` has no maintainers, and both are flagged out of date.

[https://aur.archlinux.org/packages/bforartists-git
](https://aur.archlinux.org/packages/bforartists-git)
[https://aur.archlinux.org/packages/bforartists](https://aur.archlinux.org/packages/bforartists)

**Comment by ReinerBforartists** [comment] 2024-02-18 16:57
As told, we don't have any Arch users in our team anymore. The one who did this has left the team. And so we don't have somebody who is able to maintain it. Sorry.

**Comment by Draise14** [comment] 2024-02-19 20:26
I have Garuda on virtual that may load Bforartists without GPU (last known working version: 3.6.2). It's an arch distro, maybe that can be troubleshooted there. Will do a compile and see.

**Comment by Draise14** [comment] 2024-02-19 20:29
![image](https://github.com/Bforartists/Bforartists/assets/35357409/96763324-09e1-4120-9700-e5eb6e49c08e)

Ah, scratch that. No-longer works due to Blender updating OpenGL.

**Comment by Kagukara** [comment] 2024-02-19 21:55
Try using distrobox, I just remembered that existed. I made a container using `distrobox create --image debian:12.5`, downloaded the .deb from the website and did `sudo apt install ~/downloads/bforartists_402.deb`. But when I go to run the program I get `/opt/bforartists/bforartists: error while loading shared libraries: libxkbcommon.so.0: cannot open shared object file: No such file or directory`.

**Comment by Kagukara** [comment] 2024-02-19 22:12
I got it working with distrobox inside a debian 12.5 container. I had to install `libxkbcommon-x11-0` and `libsm6` in the container via `sudo apt install`.

I redid the initial steps and still get the same result.

**Comment by Draise14** [comment] 2024-02-19 22:45
I've got Hyper-V working on W11 and it is accessing the GPU nicely - so Bforartists loads there now. So I will make the environment and try compile from source, see if it's the Appimage or something else. 

This is really obscure, because technically we haven't touched this part of the code that would store or do alter anything like this.

**Comment by Draise14** [comment] 2024-02-19 23:15
Ok, can confirm, this issue persists in the Windows build too.

**Comment by Draise14** [comment] 2024-02-19 23:36
Ok, double checked in Blender. Same issue. So yeah, this is a blender issue from main.

**Comment by Kagukara** [comment] 2024-02-20 01:14
> @Kagukara Please report to Blender! I can maybe report it tomorrow.

Its already reported here: https://projects.blender.org/blender/blender/issues/108385 as I said in this comment: https://github.com/Bforartists/Bforartists/issues/3695#issuecomment-1774927353

> Ok, double checked in Blender. Same issue. So yeah, this is a blender issue from main.

How come the issue doesn't happen in Blender for me though? I've tried it in 3.6.5, 4.0.2, 4.1 and 4.2.

**Comment by Draise14** [comment] 2024-02-20 14:51
https://github.com/Bforartists/Bforartists/assets/35357409/da39139e-bbe4-42a3-af06-bf00705df926

> You aren't setting "default unit of millimeters". You are setting a default unit system of "Metric" and preferred length value of "Millimeters". The "Length" input does not change how big new items will be created, it only changes how the values are shown:

This is from a build in the Blender main from yesterday.

I think the size of the default object being unpredictable, as yes, it is unpredictable... is probably a bug and unintended UX directly inherited from Blender. Looking at the code, everything should be created to 1 scene unit in each axis (2 scene units total). Scene units are agnostic to the display of the scene unit scale for the measurements ratio, agnostic to the measurement type, and agnostic to the grid view, or _should_ be agnostic. The geometry are set by one scene unit scale on all axis (+1x, -1x, +1y -1y +1z -1z). 

https://github.com/Bforartists/Bforartists/assets/35357409/4d10a98a-dc19-4d93-94f5-d1a42173d57a

This will have to be fixed by upstream from Blender directly, since the unpredictability can be reproduced in Blender.

**Comment by Kagukara** [comment] 2024-02-20 17:19
I don't quite understand what you've said but, it looks like you know what is going on and understand whats happening.

As to how its working for me I've provided a video:

https://github.com/Bforartists/Bforartists/assets/43391109/9052f40d-f055-4f66-9a13-1bf72cfeb5b5

Before  doing "Save Startup File" the cube shown as larger (dimensions: X,Y,Z = 2000mm), once you've "Save Startup File" and restarted blender all newly created cubes are now dimensions: X,Y,Z = 2mm. Doing this in bforartists keeps the dimension at 2000mm even after doing "Save Startup File" and restarting.

Are you able to replicated this?

**Comment by Draise14** [comment] 2024-02-20 18:00
Can confirm, it is as expected in Bforartists. Cube comes in at 2 blender/scene units, regardless of unit scale precision or measurement drawing in the GUI, or grid. It is agnostic, which is correct and expected UX. Tooltip mentions the precision of the scale, not the default spawn dimensions of objects - so getting a new object scale is bizzare.

I have confirmed in Blender though... that it is broken. 
![imagen](https://github.com/Bforartists/Bforartists/assets/35357409/4409f4ea-72fc-4277-98f5-3aaabc8b6890)

When you scale the UI up to 1.000 in Blender again, save startup again, the object will spawn at 20mm instead of 2 scene units of 2m. So If I save startup after that again at 0.001, the 20mm "scene unit" will then be 0.02mm, and the new spawned cube will be at another dimension of 20mm, also broken. Blender is storing new scene unit scales, which makes resetting scene units strangely a 3 setting jiggle. And for some reason the grid scale is affecting how the objects are spawning, when it should only be the grid overlay setting. These by UX, should be entirely agnostic. 

![imagen](https://github.com/Bforartists/Bforartists/assets/35357409/e9b1b697-1daf-4c1f-88d5-7afbb9fb6ccd)

**Comment by Kagukara** [comment] 2024-02-20 19:36
Thank you for looking at this further and providing a more in-depth explanations. 

If bforartists is working as intended, how would I go about setting up millimetres so that when you add a cube it adds it at 2x2x2mm with the grid being 1mm per square?

Is there a setting to change the default size the objects are being added as or is it not possible/a different way?

**Comment by Kagukara** [comment] 2024-02-20 19:43
I've also updated the video so it doesn't cut off, from my understanding and the video I still get a different result from the latest tests you've provided.

**Comment by Draise14** [comment] 2024-02-20 20:06
![imagen](https://github.com/Bforartists/Bforartists/assets/35357409/71a33c44-b7b5-424d-b80e-63743d764767)

There is currently no _intended_ (thus documented) method to set the default size of an added object. 

Though I could build this into Bforartists as intented in the GUI code, and add that to the tooltip... and make it predictable, without needing to save startup too.

**Comment by ReinerBforartists** [comment] 2024-04-20 08:19
This would imho be a job for an addon then. Not the main UI. We promised feature parity with Blender. And this one could bring us into trouble. But this would be a new task then.

The initial task, well, it is nothing that we could fix at our end. It is a fundamental how Blender works. Can we close it?

**Closed** 2024-04-20 10:32 UTC
Labels: 5 - Postponed, Blender Bug / Issue, Known Issue

**Comment by Draise14** [comment] 2024-04-22 03:37
Will add it to the power user tools addon.
