### ISSUE TITLE
Limiting inserted faces does not work when you are using INSET

### ISSUE THREAD

**Issue by DarthMoulByte** [Bforartists/Bforartists#1585] opened 2020-05-31 22:21 UTC
**Describe the bug**
Inset Faces does not work when you press the B key to control limits of inserted faces

**Desktop (please complete the following information):**
Windows 10, GPU nvidia GT-720 

**Screenshots, Example Files**
![Z08FD8Wgi8](https://user-images.githubusercontent.com/24207840/83363903-a941b680-a362-11ea-8513-59e1f8cb838a.gif)
![U3T5buHl5v](https://user-images.githubusercontent.com/24207840/83364023-adba9f00-a363-11ea-8086-156095983c12.gif)

[video tutorial youtube](https://youtu.be/WlaMfIgS2ns)

**Comment by ReinerBforartists** [comment] 2020-06-01 08:40
Thanks for the report. But i cannot reproduce a problem here. Maybe i misunderstand what you mean? What exact step is failing?

B is box select with both, the Blender keymap and the Bforartists keymap. It does not toggle the Boundary, and does not control limits of inserted faces. So what is the problem? You can untick Boundary in the last operator panel.

**Comment by DarthMoulByte** [comment] 2020-06-01 17:30
I could no longer recreate the problem
Image 1, where I uncheck the box does not alternate Boundary
regardless of whether or not it was the shortcut.
maybe my file had something wrong, I could no longer recreate the fault
but during this week it did not work correctly today I tried again and it already works,
and I used my own build and it worked on my file, but b4artist didn't work well
You can close this thread, I will be pending if it happens to me once more and I will record a video, I will try to collect more data, this time I was taken by surprise.

and there is not much to explain, the image speaks for itself, unchecking the box did not do its job and not checking it either, the second image is from a YouTube video, where you can see how it works well

**Comment by ReinerBforartists** [comment] 2020-06-01 19:01
Ah, these bugs are the meanest. But better one time too often reported than never ^^

Feel free to reopen it when you are able to reproduce the problem. I will close this task for now. Thanks :)

**Closed by ReinerBforartists** 2020-06-01 19:01 UTC
Labels: 0 - task
